// Code generated by ent, DO NOT EDIT.

package authbinding

import (
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the authbinding type in the database.
	Label = "auth_binding"
	// FieldId holds the string denoting the id field in the database.
	FieldId = "id"
	// FieldBindingId holds the string denoting the binding_id field in the database.
	FieldBindingId = "binding_id"
	// FieldAuthBackend holds the string denoting the auth_backend field in the database.
	FieldAuthBackend = "auth_backend"
	// FieldScope holds the string denoting the scope field in the database.
	FieldScope = "scope"
	// FieldCredentialRef holds the string denoting the credential_ref field in the database.
	FieldCredentialRef = "credential_ref"
	// FieldDateUpdated holds the string denoting the date_updated field in the database.
	FieldDateUpdated = "date_updated"
	// FieldDateErased holds the string denoting the date_erased field in the database.
	FieldDateErased = "date_erased"
	// FieldDateCreated holds the string denoting the date_created field in the database.
	FieldDateCreated = "date_created"
	// FieldAccountId holds the string denoting the account_id field in the database.
	FieldAccountId = "account_id"
	// FieldProjectId holds the string denoting the project_id field in the database.
	FieldProjectId = "project_id"
	// EdgeAccount holds the string denoting the account edge name in mutations.
	EdgeAccount = "account"
	// EdgeProject holds the string denoting the project edge name in mutations.
	EdgeProject = "project"
	// Table holds the table name of the authbinding in the database.
	Table = "authbinding"
	// AccountTable is the table that holds the account relation/edge.
	AccountTable = "authbinding"
	// AccountInverseTable is the table name for the Account entity.
	// It exists in this package in order to avoid circular dependency with the "account" package.
	AccountInverseTable = "account"
	// AccountColumn is the table column denoting the account relation/edge.
	AccountColumn = "account_id"
	// ProjectTable is the table that holds the project relation/edge.
	ProjectTable = "authbinding"
	// ProjectInverseTable is the table name for the Project entity.
	// It exists in this package in order to avoid circular dependency with the "project" package.
	ProjectInverseTable = "project"
	// ProjectColumn is the table column denoting the project relation/edge.
	ProjectColumn = "project_id"
)

// Columns holds all SQL columns for authbinding fields.
var Columns = []string{
	FieldId,
	FieldBindingId,
	FieldAuthBackend,
	FieldScope,
	FieldCredentialRef,
	FieldDateUpdated,
	FieldDateErased,
	FieldDateCreated,
	FieldAccountId,
	FieldProjectId,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the AuthBinding queries.
type OrderOption func(*sql.Selector)

// ById orders the results by the id field.
func ById(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldId, opts...).ToFunc()
}

// ByBindingId orders the results by the binding_id field.
func ByBindingId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBindingId, opts...).ToFunc()
}

// ByAuthBackend orders the results by the auth_backend field.
func ByAuthBackend(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthBackend, opts...).ToFunc()
}

// ByScope orders the results by the scope field.
func ByScope(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScope, opts...).ToFunc()
}

// ByCredentialRef orders the results by the credential_ref field.
func ByCredentialRef(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCredentialRef, opts...).ToFunc()
}

// ByDateUpdated orders the results by the date_updated field.
func ByDateUpdated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateUpdated, opts...).ToFunc()
}

// ByDateErased orders the results by the date_erased field.
func ByDateErased(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateErased, opts...).ToFunc()
}

// ByDateCreated orders the results by the date_created field.
func ByDateCreated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateCreated, opts...).ToFunc()
}

// ByAccountId orders the results by the account_id field.
func ByAccountId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountId, opts...).ToFunc()
}

// ByProjectId orders the results by the project_id field.
func ByProjectId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectId, opts...).ToFunc()
}

// ByAccountField orders the results by account field.
func ByAccountField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccountStep(), sql.OrderByField(field, opts...))
	}
}

// ByProjectField orders the results by project field.
func ByProjectField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProjectStep(), sql.OrderByField(field, opts...))
	}
}
func newAccountStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldId),
		sqlgraph.To(AccountInverseTable, FieldId),
		sqlgraph.Edge(sqlgraph.M2O, false, AccountTable, AccountColumn),
	)
}
func newProjectStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldId),
		sqlgraph.To(ProjectInverseTable, FieldId),
		sqlgraph.Edge(sqlgraph.M2O, false, ProjectTable, ProjectColumn),
	)
}
