// Code generated by ent, DO NOT EDIT.

package authbinding

import (
	"context"
	"fmt"
	"time"
	"uuid"

	"github.com/lesomnus/cxz/internal/ent/predicate"
	"github.com/protobuf-orm/ent"
	"github.com/protobuf-orm/ent/dialect/sql"
)

// Mutation represents an operation that mutates the AuthBinding nodes in the graph.
type Mutation struct {
	op             ent.Op
	typ            string
	binding_id     *string
	auth_backend   *string
	scope          *string
	credential_ref *string
	date_updated   *time.Time
	date_erased    *time.Time
	date_created   *time.Time
	clearedFields  map[string]struct{}
	account        *uuid.UUID
	clearedaccount bool
	project        *uuid.UUID
	clearedproject bool
	predicates     []predicate.AuthBinding
}

// NewMutation creates a new Mutation for the AuthBinding entity.
func NewMutation(op ent.Op) *Mutation {
	return &Mutation{
		op:            op,
		typ:           "AuthBinding",
		clearedFields: make(map[string]struct{}),
	}
}

// Predicates returns the list of predicates set on the mutation.
func (m *Mutation) Predicates() []predicate.AuthBinding {
	return m.predicates
}

// SetBindingId sets the "binding_id" field.
func (m *Mutation) SetBindingId(s string) {
	m.binding_id = &s
}

// BindingId returns the value of the "binding_id" field in the mutation.
func (m *Mutation) BindingId() (r string, exists bool) {
	v := m.binding_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetBindingId resets all changes to the "binding_id" field.
func (m *Mutation) ResetBindingId() {
	m.binding_id = nil
}

// SetAuthBackend sets the "auth_backend" field.
func (m *Mutation) SetAuthBackend(s string) {
	m.auth_backend = &s
}

// AuthBackend returns the value of the "auth_backend" field in the mutation.
func (m *Mutation) AuthBackend() (r string, exists bool) {
	v := m.auth_backend
	if v == nil {
		return
	}
	return *v, true
}

// ResetAuthBackend resets all changes to the "auth_backend" field.
func (m *Mutation) ResetAuthBackend() {
	m.auth_backend = nil
}

// SetScope sets the "scope" field.
func (m *Mutation) SetScope(s string) {
	m.scope = &s
}

// Scope returns the value of the "scope" field in the mutation.
func (m *Mutation) Scope() (r string, exists bool) {
	v := m.scope
	if v == nil {
		return
	}
	return *v, true
}

// ResetScope resets all changes to the "scope" field.
func (m *Mutation) ResetScope() {
	m.scope = nil
}

// SetCredentialRef sets the "credential_ref" field.
func (m *Mutation) SetCredentialRef(s string) {
	m.credential_ref = &s
}

// CredentialRef returns the value of the "credential_ref" field in the mutation.
func (m *Mutation) CredentialRef() (r string, exists bool) {
	v := m.credential_ref
	if v == nil {
		return
	}
	return *v, true
}

// ResetCredentialRef resets all changes to the "credential_ref" field.
func (m *Mutation) ResetCredentialRef() {
	m.credential_ref = nil
}

// SetDateUpdated sets the "date_updated" field.
func (m *Mutation) SetDateUpdated(t time.Time) {
	m.date_updated = &t
}

// DateUpdated returns the value of the "date_updated" field in the mutation.
func (m *Mutation) DateUpdated() (r time.Time, exists bool) {
	v := m.date_updated
	if v == nil {
		return
	}
	return *v, true
}

// ResetDateUpdated resets all changes to the "date_updated" field.
func (m *Mutation) ResetDateUpdated() {
	m.date_updated = nil
}

// SetDateErased sets the "date_erased" field.
func (m *Mutation) SetDateErased(t time.Time) {
	m.date_erased = &t
}

// DateErased returns the value of the "date_erased" field in the mutation.
func (m *Mutation) DateErased() (r time.Time, exists bool) {
	v := m.date_erased
	if v == nil {
		return
	}
	return *v, true
}

// ClearDateErased clears the value of the "date_erased" field.
func (m *Mutation) ClearDateErased() {
	m.date_erased = nil
	m.clearedFields[FieldDateErased] = struct{}{}
}

// DateErasedCleared returns if the "date_erased" field was cleared in this mutation.
func (m *Mutation) DateErasedCleared() bool {
	_, ok := m.clearedFields[FieldDateErased]
	return ok
}

// ResetDateErased resets all changes to the "date_erased" field.
func (m *Mutation) ResetDateErased() {
	m.date_erased = nil
	delete(m.clearedFields, FieldDateErased)
}

// SetDateCreated sets the "date_created" field.
func (m *Mutation) SetDateCreated(t time.Time) {
	m.date_created = &t
}

// DateCreated returns the value of the "date_created" field in the mutation.
func (m *Mutation) DateCreated() (r time.Time, exists bool) {
	v := m.date_created
	if v == nil {
		return
	}
	return *v, true
}

// ClearDateCreated clears the value of the "date_created" field.
func (m *Mutation) ClearDateCreated() {
	m.date_created = nil
	m.clearedFields[FieldDateCreated] = struct{}{}
}

// DateCreatedCleared returns if the "date_created" field was cleared in this mutation.
func (m *Mutation) DateCreatedCleared() bool {
	_, ok := m.clearedFields[FieldDateCreated]
	return ok
}

// ResetDateCreated resets all changes to the "date_created" field.
func (m *Mutation) ResetDateCreated() {
	m.date_created = nil
	delete(m.clearedFields, FieldDateCreated)
}

// SetAccountId sets the "account_id" field.
func (m *Mutation) SetAccountId(u uuid.UUID) {
	m.account = &u
}

// AccountId returns the value of the "account_id" field in the mutation.
func (m *Mutation) AccountId() (r uuid.UUID, exists bool) {
	v := m.account
	if v == nil {
		return
	}
	return *v, true
}

// ResetAccountId resets all changes to the "account_id" field.
func (m *Mutation) ResetAccountId() {
	m.account = nil
}

// SetProjectId sets the "project_id" field.
func (m *Mutation) SetProjectId(u uuid.UUID) {
	m.project = &u
}

// ProjectId returns the value of the "project_id" field in the mutation.
func (m *Mutation) ProjectId() (r uuid.UUID, exists bool) {
	v := m.project
	if v == nil {
		return
	}
	return *v, true
}

// ClearProjectId clears the value of the "project_id" field.
func (m *Mutation) ClearProjectId() {
	m.project = nil
	m.clearedFields[FieldProjectId] = struct{}{}
}

// ProjectIdCleared returns if the "project_id" field was cleared in this mutation.
func (m *Mutation) ProjectIdCleared() bool {
	_, ok := m.clearedFields[FieldProjectId]
	return ok
}

// ResetProjectId resets all changes to the "project_id" field.
func (m *Mutation) ResetProjectId() {
	m.project = nil
	delete(m.clearedFields, FieldProjectId)
}

// ClearAccount clears the "account" edge to the Account entity.
func (m *Mutation) ClearAccount() {
	m.clearedaccount = true
	m.clearedFields[FieldAccountId] = struct{}{}
}

// AccountCleared reports if the "account" edge to the Account entity was cleared.
func (m *Mutation) AccountCleared() bool {
	return m.clearedaccount
}

// AccountIds returns the "account" edge Ids in the mutation.
// Note that Ids always returns len(Ids) <= 1 for unique edges, and you should use
// AccountId instead. It exists only for internal usage by the builders.
func (m *Mutation) AccountIds() (ids []uuid.UUID) {
	if id := m.account; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetAccount resets all changes to the "account" edge.
func (m *Mutation) ResetAccount() {
	m.account = nil
	m.clearedaccount = false
}

// ClearProject clears the "project" edge to the Project entity.
func (m *Mutation) ClearProject() {
	m.clearedproject = true
	m.clearedFields[FieldProjectId] = struct{}{}
}

// ProjectCleared reports if the "project" edge to the Project entity was cleared.
func (m *Mutation) ProjectCleared() bool {
	return m.ProjectIdCleared() || m.clearedproject
}

// ProjectIds returns the "project" edge Ids in the mutation.
// Note that Ids always returns len(Ids) <= 1 for unique edges, and you should use
// ProjectId instead. It exists only for internal usage by the builders.
func (m *Mutation) ProjectIds() (ids []uuid.UUID) {
	if id := m.project; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetProject resets all changes to the "project" edge.
func (m *Mutation) ResetProject() {
	m.project = nil
	m.clearedproject = false
}

// Where appends a list predicates to the Mutation builder.
func (m *Mutation) Where(ps ...predicate.AuthBinding) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the Mutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *Mutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.AuthBinding, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *Mutation) Op() ent.Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *Mutation) SetOp(op ent.Op) {
	m.op = op
}

// Type returns the node type of this mutation (AuthBinding).
func (m *Mutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *Mutation) Fields() []string {
	fields := make([]string, 0, 9)
	if m.binding_id != nil {
		fields = append(fields, FieldBindingId)
	}
	if m.auth_backend != nil {
		fields = append(fields, FieldAuthBackend)
	}
	if m.scope != nil {
		fields = append(fields, FieldScope)
	}
	if m.credential_ref != nil {
		fields = append(fields, FieldCredentialRef)
	}
	if m.date_updated != nil {
		fields = append(fields, FieldDateUpdated)
	}
	if m.date_erased != nil {
		fields = append(fields, FieldDateErased)
	}
	if m.date_created != nil {
		fields = append(fields, FieldDateCreated)
	}
	if m.account != nil {
		fields = append(fields, FieldAccountId)
	}
	if m.project != nil {
		fields = append(fields, FieldProjectId)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *Mutation) Field(name string) (ent.Value, bool) {
	switch name {
	case FieldBindingId:
		return m.BindingId()
	case FieldAuthBackend:
		return m.AuthBackend()
	case FieldScope:
		return m.Scope()
	case FieldCredentialRef:
		return m.CredentialRef()
	case FieldDateUpdated:
		return m.DateUpdated()
	case FieldDateErased:
		return m.DateErased()
	case FieldDateCreated:
		return m.DateCreated()
	case FieldAccountId:
		return m.AccountId()
	case FieldProjectId:
		return m.ProjectId()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *Mutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	return nil, fmt.Errorf("unknown AuthBinding field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *Mutation) SetField(name string, value ent.Value) error {
	switch name {
	case FieldBindingId:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBindingId(v)
		return nil
	case FieldAuthBackend:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAuthBackend(v)
		return nil
	case FieldScope:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetScope(v)
		return nil
	case FieldCredentialRef:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCredentialRef(v)
		return nil
	case FieldDateUpdated:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDateUpdated(v)
		return nil
	case FieldDateErased:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDateErased(v)
		return nil
	case FieldDateCreated:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDateCreated(v)
		return nil
	case FieldAccountId:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAccountId(v)
		return nil
	case FieldProjectId:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetProjectId(v)
		return nil
	}
	return fmt.Errorf("unknown AuthBinding field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *Mutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *Mutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *Mutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown AuthBinding numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *Mutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(FieldDateErased) {
		fields = append(fields, FieldDateErased)
	}
	if m.FieldCleared(FieldDateCreated) {
		fields = append(fields, FieldDateCreated)
	}
	if m.FieldCleared(FieldProjectId) {
		fields = append(fields, FieldProjectId)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *Mutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *Mutation) ClearField(name string) error {
	switch name {
	case FieldDateErased:
		m.ClearDateErased()
		return nil
	case FieldDateCreated:
		m.ClearDateCreated()
		return nil
	case FieldProjectId:
		m.ClearProjectId()
		return nil
	}
	return fmt.Errorf("unknown AuthBinding nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *Mutation) ResetField(name string) error {
	switch name {
	case FieldBindingId:
		m.ResetBindingId()
		return nil
	case FieldAuthBackend:
		m.ResetAuthBackend()
		return nil
	case FieldScope:
		m.ResetScope()
		return nil
	case FieldCredentialRef:
		m.ResetCredentialRef()
		return nil
	case FieldDateUpdated:
		m.ResetDateUpdated()
		return nil
	case FieldDateErased:
		m.ResetDateErased()
		return nil
	case FieldDateCreated:
		m.ResetDateCreated()
		return nil
	case FieldAccountId:
		m.ResetAccountId()
		return nil
	case FieldProjectId:
		m.ResetProjectId()
		return nil
	}
	return fmt.Errorf("unknown AuthBinding field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *Mutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.account != nil {
		edges = append(edges, EdgeAccount)
	}
	if m.project != nil {
		edges = append(edges, EdgeProject)
	}
	return edges
}

// AddedIds returns all Ids (to other nodes) that were added for the given edge
// name in this mutation.
func (m *Mutation) AddedIds(name string) []ent.Value {
	switch name {
	case EdgeAccount:
		if id := m.account; id != nil {
			return []ent.Value{*id}
		}
	case EdgeProject:
		if id := m.project; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *Mutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	return edges
}

// RemovedIds returns all Ids (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *Mutation) RemovedIds(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *Mutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearedaccount {
		edges = append(edges, EdgeAccount)
	}
	if m.clearedproject {
		edges = append(edges, EdgeProject)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *Mutation) EdgeCleared(name string) bool {
	switch name {
	case EdgeAccount:
		return m.clearedaccount
	case EdgeProject:
		return m.clearedproject
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *Mutation) ClearEdge(name string) error {
	switch name {
	case EdgeAccount:
		m.ClearAccount()
		return nil
	case EdgeProject:
		m.ClearProject()
		return nil
	}
	return fmt.Errorf("unknown AuthBinding unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *Mutation) ResetEdge(name string) error {
	switch name {
	case EdgeAccount:
		m.ResetAccount()
		return nil
	case EdgeProject:
		m.ResetProject()
		return nil
	}
	return fmt.Errorf("unknown AuthBinding edge %s", name)
}
