// Code generated by ent, DO NOT EDIT.

package session

import (
	"github.com/lesomnus/cxz/resource"
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	"github.com/protobuf-orm/ent/schema/field"
)

const (
	// Label holds the string label denoting the session type in the database.
	Label = "session"
	// FieldId holds the string denoting the id field in the database.
	FieldId = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDesc holds the string denoting the desc field in the database.
	FieldDesc = "desc"
	// FieldAgent holds the string denoting the agent field in the database.
	FieldAgent = "agent"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldRuntimeId holds the string denoting the runtime_id field in the database.
	FieldRuntimeId = "runtime_id"
	// FieldClientId holds the string denoting the client_id field in the database.
	FieldClientId = "client_id"
	// FieldDateUpdated holds the string denoting the date_updated field in the database.
	FieldDateUpdated = "date_updated"
	// FieldDateErased holds the string denoting the date_erased field in the database.
	FieldDateErased = "date_erased"
	// FieldDateCreated holds the string denoting the date_created field in the database.
	FieldDateCreated = "date_created"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldListed holds the string denoting the listed field in the database.
	FieldListed = "listed"
	// FieldProjectId holds the string denoting the project_id field in the database.
	FieldProjectId = "project_id"
	// FieldAccountId holds the string denoting the account_id field in the database.
	FieldAccountId = "account_id"
	// EdgeProject holds the string denoting the project edge name in mutations.
	EdgeProject = "project"
	// EdgeAccount holds the string denoting the account edge name in mutations.
	EdgeAccount = "account"
	// Table holds the table name of the session in the database.
	Table = "session"
	// ProjectTable is the table that holds the project relation/edge.
	ProjectTable = "session"
	// ProjectInverseTable is the table name for the Project entity.
	// It exists in this package in order to avoid circular dependency with the "project" package.
	ProjectInverseTable = "project"
	// ProjectColumn is the table column denoting the project relation/edge.
	ProjectColumn = "project_id"
	// AccountTable is the table that holds the account relation/edge.
	AccountTable = "session"
	// AccountInverseTable is the table name for the Account entity.
	// It exists in this package in order to avoid circular dependency with the "account" package.
	AccountInverseTable = "account"
	// AccountColumn is the table column denoting the account relation/edge.
	AccountColumn = "account_id"
)

// Columns holds all SQL columns for session fields.
var Columns = []string{
	FieldId,
	FieldName,
	FieldDesc,
	FieldAgent,
	FieldModel,
	FieldRuntimeId,
	FieldClientId,
	FieldDateUpdated,
	FieldDateErased,
	FieldDateCreated,
	FieldStatus,
	FieldListed,
	FieldProjectId,
	FieldAccountId,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ValueScanner of all Session fields.
	ValueScanner struct {
		Status field.TypeValueScanner[*resource.SessionStatus]
	}
)

// OrderOption defines the ordering options for the Session queries.
type OrderOption func(*sql.Selector)

// ById orders the results by the id field.
func ById(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldId, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDesc orders the results by the desc field.
func ByDesc(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDesc, opts...).ToFunc()
}

// ByAgent orders the results by the agent field.
func ByAgent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAgent, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByRuntimeId orders the results by the runtime_id field.
func ByRuntimeId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRuntimeId, opts...).ToFunc()
}

// ByClientId orders the results by the client_id field.
func ByClientId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientId, opts...).ToFunc()
}

// ByDateUpdated orders the results by the date_updated field.
func ByDateUpdated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateUpdated, opts...).ToFunc()
}

// ByDateErased orders the results by the date_erased field.
func ByDateErased(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateErased, opts...).ToFunc()
}

// ByDateCreated orders the results by the date_created field.
func ByDateCreated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateCreated, opts...).ToFunc()
}

// ByListed orders the results by the listed field.
func ByListed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldListed, opts...).ToFunc()
}

// ByProjectId orders the results by the project_id field.
func ByProjectId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectId, opts...).ToFunc()
}

// ByAccountId orders the results by the account_id field.
func ByAccountId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountId, opts...).ToFunc()
}

// ByProjectField orders the results by project field.
func ByProjectField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProjectStep(), sql.OrderByField(field, opts...))
	}
}

// ByAccountField orders the results by account field.
func ByAccountField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccountStep(), sql.OrderByField(field, opts...))
	}
}
func newProjectStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldId),
		sqlgraph.To(ProjectInverseTable, FieldId),
		sqlgraph.Edge(sqlgraph.M2O, false, ProjectTable, ProjectColumn),
	)
}
func newAccountStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldId),
		sqlgraph.To(AccountInverseTable, FieldId),
		sqlgraph.Edge(sqlgraph.M2O, false, AccountTable, AccountColumn),
	)
}
