// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: cxz/account.proto

package schema

import (
	ent "github.com/protobuf-orm/ent"
	entsql "github.com/protobuf-orm/ent/dialect/entsql"
	schema "github.com/protobuf-orm/ent/schema"
	field "github.com/protobuf-orm/ent/schema/field"
	index "github.com/protobuf-orm/ent/schema/index"
)

type Account struct {
	ent.Schema
}

func (Account) Fields() []ent.Field {
	return []ent.Field{
		field.Uuid("id").
			Unique().
			Immutable(),
		field.String("alias"),
		field.String("name"),
		field.String("desc"),
		field.String("agent").
			Immutable(),
		field.Time("date_updated"),
		field.Time("date_erased").
			Nillable().
			Optional(),
		field.Time("date_created").
			Immutable().
			Optional(),
	}
}

func (Account) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("alias").
			Unique().
			Annotations(entsql.IndexWhere("date_erased IS NULL")),
	}
}

func (Account) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{Table: "account"},
	}
}
