// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: cxz/auth_binding.proto

package schema

import (
	ent "github.com/protobuf-orm/ent"
	entsql "github.com/protobuf-orm/ent/dialect/entsql"
	schema "github.com/protobuf-orm/ent/schema"
	edge "github.com/protobuf-orm/ent/schema/edge"
	field "github.com/protobuf-orm/ent/schema/field"
	index "github.com/protobuf-orm/ent/schema/index"
)

type AuthBinding struct {
	ent.Schema
}

func (AuthBinding) Fields() []ent.Field {
	return []ent.Field{
		field.Uuid("id").
			Unique().
			Immutable(),
		field.String("binding_id").
			Immutable(),
		field.String("auth_backend").
			Immutable(),
		field.String("scope").
			Immutable(),
		field.String("credential_ref").
			Immutable(),
		field.Time("date_updated"),
		field.Time("date_erased").
			Nillable().
			Optional(),
		field.Time("date_created").
			Immutable().
			Optional(),
		field.Uuid("account_id").
			Immutable(),
		field.Uuid("project_id").
			Optional().
			Immutable(),
	}
}

func (AuthBinding) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("account", Account.Type).
			Unique().
			Field("account_id").
			Required().
			Immutable(),
		edge.To("project", Project.Type).
			Unique().
			Field("project_id").
			Immutable(),
	}
}

func (AuthBinding) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("binding_id").
			Unique().
			Annotations(entsql.IndexWhere("date_erased IS NULL")),
	}
}

func (AuthBinding) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{Table: "authbinding"},
	}
}
