// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: cxz/project.proto

package schema

import (
	resource "github.com/lesomnus/cxz/resource"
	ent "github.com/protobuf-orm/ent"
	entsql "github.com/protobuf-orm/ent/dialect/entsql"
	schema "github.com/protobuf-orm/ent/schema"
	field "github.com/protobuf-orm/ent/schema/field"
	index "github.com/protobuf-orm/ent/schema/index"
	entpb "github.com/protobuf-orm/protoc-gen-orm-ent/runtime/entpb"
)

type Project struct {
	ent.Schema
}

func (Project) Fields() []ent.Field {
	return []ent.Field{
		field.Uuid("id").
			Unique().
			Immutable(),
		field.String("alias"),
		field.String("name"),
		field.String("desc"),
		field.String("workspace").
			Immutable(),
		field.String("config"),
		field.String("runtime_id").
			Immutable(),
		field.Time("date_updated"),
		field.Time("date_erased").
			Nillable().
			Optional(),
		field.Time("date_created").
			Immutable().
			Optional(),
		field.Json("status", &resource.ProjectStatus{}).ValueScanner(entpb.ValueScanner[*resource.ProjectStatus]{}).
			Optional(),
		field.Bool("listed").
			Optional(),
	}
}

func (Project) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("date_created", "id"),
		index.Fields("alias").
			Unique().
			Annotations(entsql.IndexWhere("date_erased IS NULL")),
		index.Fields("workspace").
			Unique().
			Annotations(entsql.IndexWhere("date_erased IS NULL")),
		index.Fields("runtime_id").
			Unique().
			Annotations(entsql.IndexWhere("date_erased IS NULL")),
	}
}

func (Project) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{Table: "project"},
	}
}
