// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"uuid"

	"github.com/lesomnus/cxz/internal/ent/account"
	"github.com/lesomnus/cxz/internal/ent/authbinding"
	"github.com/lesomnus/cxz/internal/ent/predicate"
	"github.com/lesomnus/cxz/internal/ent/project"
	"github.com/protobuf-orm/ent"
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	"github.com/protobuf-orm/ent/schema/field"
)

// AuthBindingQuery is the builder for querying AuthBinding entities.
type AuthBindingQuery struct {
	config
	ctx         *QueryContext
	order       []authbinding.OrderOption
	inters      []Interceptor
	predicates  []predicate.AuthBinding
	withAccount *AccountQuery
	withProject *ProjectQuery
	modifiers   []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AuthBindingQuery builder.
func (_q *AuthBindingQuery) Where(ps ...predicate.AuthBinding) *AuthBindingQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *AuthBindingQuery) Limit(limit int) *AuthBindingQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *AuthBindingQuery) Offset(offset int) *AuthBindingQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *AuthBindingQuery) Unique(unique bool) *AuthBindingQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *AuthBindingQuery) Order(o ...authbinding.OrderOption) *AuthBindingQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryAccount chains the current query on the "account" edge.
func (_q *AuthBindingQuery) QueryAccount() *AccountQuery {
	query := (&AccountClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(authbinding.Table, authbinding.FieldId, selector),
			sqlgraph.To(account.Table, account.FieldId),
			sqlgraph.Edge(sqlgraph.M2O, false, authbinding.AccountTable, authbinding.AccountColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryProject chains the current query on the "project" edge.
func (_q *AuthBindingQuery) QueryProject() *ProjectQuery {
	query := (&ProjectClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(authbinding.Table, authbinding.FieldId, selector),
			sqlgraph.To(project.Table, project.FieldId),
			sqlgraph.Edge(sqlgraph.M2O, false, authbinding.ProjectTable, authbinding.ProjectColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AuthBinding entity from the query.
// Returns a *NotFoundError when no AuthBinding was found.
func (_q *AuthBindingQuery) First(ctx context.Context) (*AuthBinding, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{authbinding.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *AuthBindingQuery) FirstX(ctx context.Context) *AuthBinding {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstId returns the first AuthBinding Id from the query.
// Returns a *NotFoundError when no AuthBinding Id was found.
func (_q *AuthBindingQuery) FirstId(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).Ids(setContextOp(ctx, _q.ctx, ent.OpQueryFirstId)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{authbinding.Label}
		return
	}
	return ids[0], nil
}

// FirstIdX is like FirstId, but panics if an error occurs.
func (_q *AuthBindingQuery) FirstIdX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstId(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AuthBinding entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AuthBinding entity is found.
// Returns a *NotFoundError when no AuthBinding entities are found.
func (_q *AuthBindingQuery) Only(ctx context.Context) (*AuthBinding, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{authbinding.Label}
	default:
		return nil, &NotSingularError{authbinding.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *AuthBindingQuery) OnlyX(ctx context.Context) *AuthBinding {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyId is like Only, but returns the only AuthBinding Id in the query.
// Returns a *NotSingularError when more than one AuthBinding Id is found.
// Returns a *NotFoundError when no entities are found.
func (_q *AuthBindingQuery) OnlyId(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).Ids(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyId)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{authbinding.Label}
	default:
		err = &NotSingularError{authbinding.Label}
	}
	return
}

// OnlyIdX is like OnlyId, but panics if an error occurs.
func (_q *AuthBindingQuery) OnlyIdX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyId(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AuthBinding entities.
func (_q *AuthBindingQuery) All(ctx context.Context) ([]*AuthBinding, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AuthBinding, *AuthBindingQuery]()
	return withInterceptors[[]*AuthBinding](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *AuthBindingQuery) AllX(ctx context.Context) []*AuthBinding {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// Ids executes the query and returns a list of AuthBinding Ids.
func (_q *AuthBindingQuery) Ids(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIds)
	if err = _q.Select(authbinding.FieldId).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IdsX is like Ids, but panics if an error occurs.
func (_q *AuthBindingQuery) IdsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.Ids(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *AuthBindingQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*AuthBindingQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *AuthBindingQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *AuthBindingQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstId(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *AuthBindingQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AuthBindingQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *AuthBindingQuery) Clone() *AuthBindingQuery {
	if _q == nil {
		return nil
	}
	return &AuthBindingQuery{
		config:      _q.config,
		ctx:         _q.ctx.Clone(),
		order:       append([]authbinding.OrderOption{}, _q.order...),
		inters:      append([]Interceptor{}, _q.inters...),
		predicates:  append([]predicate.AuthBinding{}, _q.predicates...),
		withAccount: _q.withAccount.Clone(),
		withProject: _q.withProject.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithAccount tells the query-builder to eager-load the nodes that are connected to
// the "account" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AuthBindingQuery) WithAccount(opts ...func(*AccountQuery)) *AuthBindingQuery {
	query := (&AccountClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAccount = query
	return _q
}

// WithProject tells the query-builder to eager-load the nodes that are connected to
// the "project" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AuthBindingQuery) WithProject(opts ...func(*ProjectQuery)) *AuthBindingQuery {
	query := (&ProjectClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProject = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		BindingId string `json:"binding_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AuthBinding.Query().
//		GroupBy(authbinding.FieldBindingId).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *AuthBindingQuery) GroupBy(field string, fields ...string) *AuthBindingGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AuthBindingGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = authbinding.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		BindingId string `json:"binding_id,omitempty"`
//	}
//
//	client.AuthBinding.Query().
//		Select(authbinding.FieldBindingId).
//		Scan(ctx, &v)
func (_q *AuthBindingQuery) Select(fields ...string) *AuthBindingSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &AuthBindingSelect{AuthBindingQuery: _q}
	sbuild.label = authbinding.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AuthBindingSelect configured with the given aggregations.
func (_q *AuthBindingQuery) Aggregate(fns ...AggregateFunc) *AuthBindingSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *AuthBindingQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !authbinding.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *AuthBindingQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AuthBinding, error) {
	var (
		nodes       = []*AuthBinding{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withAccount != nil,
			_q.withProject != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AuthBinding).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AuthBinding{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withAccount; query != nil {
		if err := _q.loadAccount(ctx, query, nodes, nil,
			func(n *AuthBinding, e *Account) { n.Edges.Account = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withProject; query != nil {
		if err := _q.loadProject(ctx, query, nodes, nil,
			func(n *AuthBinding, e *Project) { n.Edges.Project = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *AuthBindingQuery) loadAccount(ctx context.Context, query *AccountQuery, nodes []*AuthBinding, init func(*AuthBinding), assign func(*AuthBinding, *Account)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*AuthBinding)
	for i := range nodes {
		fk := nodes[i].AccountId
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(account.IdIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.Id]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "account_id" returned %v`, n.Id)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *AuthBindingQuery) loadProject(ctx context.Context, query *ProjectQuery, nodes []*AuthBinding, init func(*AuthBinding), assign func(*AuthBinding, *Project)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*AuthBinding)
	for i := range nodes {
		fk := nodes[i].ProjectId
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(project.IdIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.Id]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "project_id" returned %v`, n.Id)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *AuthBindingQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *AuthBindingQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(authbinding.Table, authbinding.Columns, sqlgraph.NewFieldSpec(authbinding.FieldId, field.TypeUuid))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, authbinding.FieldId)
		for i := range fields {
			if fields[i] != authbinding.FieldId {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withAccount != nil {
			_spec.Node.AddColumnOnce(authbinding.FieldAccountId)
		}
		if _q.withProject != nil {
			_spec.Node.AddColumnOnce(authbinding.FieldProjectId)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *AuthBindingQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(authbinding.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = authbinding.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *AuthBindingQuery) Modify(modifiers ...func(s *sql.Selector)) *AuthBindingSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// AuthBindingGroupBy is the group-by builder for AuthBinding entities.
type AuthBindingGroupBy struct {
	selector
	build *AuthBindingQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *AuthBindingGroupBy) Aggregate(fns ...AggregateFunc) *AuthBindingGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *AuthBindingGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AuthBindingQuery, *AuthBindingGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *AuthBindingGroupBy) sqlScan(ctx context.Context, root *AuthBindingQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AuthBindingSelect is the builder for selecting fields of AuthBinding entities.
type AuthBindingSelect struct {
	*AuthBindingQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *AuthBindingSelect) Aggregate(fns ...AggregateFunc) *AuthBindingSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *AuthBindingSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AuthBindingQuery, *AuthBindingSelect](ctx, _s.AuthBindingQuery, _s, _s.inters, v)
}

func (_s *AuthBindingSelect) sqlScan(ctx context.Context, root *AuthBindingQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *AuthBindingSelect) Modify(modifiers ...func(s *sql.Selector)) *AuthBindingSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
