// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"uuid"

	"github.com/lesomnus/cxz/internal/ent/account"
	"github.com/lesomnus/cxz/internal/ent/authbinding"
	"github.com/lesomnus/cxz/internal/ent/project"
	"github.com/protobuf-orm/ent"
	"github.com/protobuf-orm/ent/dialect/sql"
)

// AuthBinding is the model entity for the AuthBinding schema.
type AuthBinding struct {
	config `json:"-"`
	// Id of the ent.
	Id uuid.UUID `json:"id,omitempty"`
	// BindingId holds the value of the "binding_id" field.
	BindingId string `json:"binding_id,omitempty"`
	// AuthBackend holds the value of the "auth_backend" field.
	AuthBackend string `json:"auth_backend,omitempty"`
	// Scope holds the value of the "scope" field.
	Scope string `json:"scope,omitempty"`
	// CredentialRef holds the value of the "credential_ref" field.
	CredentialRef string `json:"credential_ref,omitempty"`
	// DateUpdated holds the value of the "date_updated" field.
	DateUpdated time.Time `json:"date_updated,omitempty"`
	// DateErased holds the value of the "date_erased" field.
	DateErased *time.Time `json:"date_erased,omitempty"`
	// DateCreated holds the value of the "date_created" field.
	DateCreated time.Time `json:"date_created,omitempty"`
	// AccountId holds the value of the "account_id" field.
	AccountId uuid.UUID `json:"account_id,omitempty"`
	// ProjectId holds the value of the "project_id" field.
	ProjectId uuid.UUID `json:"project_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AuthBindingQuery when eager-loading is set.
	Edges        AuthBindingEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AuthBindingEdges holds the relations/edges for other nodes in the graph.
type AuthBindingEdges struct {
	// Account holds the value of the account edge.
	Account *Account `json:"account,omitempty"`
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AuthBindingEdges) AccountOrErr() (*Account, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AuthBindingEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AuthBinding) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case authbinding.FieldBindingId, authbinding.FieldAuthBackend, authbinding.FieldScope, authbinding.FieldCredentialRef:
			values[i] = new(sql.NullString)
		case authbinding.FieldDateUpdated, authbinding.FieldDateErased, authbinding.FieldDateCreated:
			values[i] = new(sql.NullTime)
		case authbinding.FieldProjectId:
			values[i] = new(sql.Null[uuid.UUID])
		case authbinding.FieldId, authbinding.FieldAccountId:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AuthBinding fields.
func (_m *AuthBinding) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case authbinding.FieldId:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.Id = *value
			}
		case authbinding.FieldBindingId:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field binding_id", values[i])
			} else if value.Valid {
				_m.BindingId = value.String
			}
		case authbinding.FieldAuthBackend:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field auth_backend", values[i])
			} else if value.Valid {
				_m.AuthBackend = value.String
			}
		case authbinding.FieldScope:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scope", values[i])
			} else if value.Valid {
				_m.Scope = value.String
			}
		case authbinding.FieldCredentialRef:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field credential_ref", values[i])
			} else if value.Valid {
				_m.CredentialRef = value.String
			}
		case authbinding.FieldDateUpdated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_updated", values[i])
			} else if value.Valid {
				_m.DateUpdated = value.Time
			}
		case authbinding.FieldDateErased:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_erased", values[i])
			} else if value.Valid {
				_m.DateErased = new(time.Time)
				*_m.DateErased = value.Time
			}
		case authbinding.FieldDateCreated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_created", values[i])
			} else if value.Valid {
				_m.DateCreated = value.Time
			}
		case authbinding.FieldAccountId:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value != nil {
				_m.AccountId = *value
			}
		case authbinding.FieldProjectId:
			if value, ok := values[i].(*sql.Null[uuid.UUID]); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value.Valid {
				_m.ProjectId = value.V
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AuthBinding.
// This includes values selected through modifiers, order, etc.
func (_m *AuthBinding) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAccount queries the "account" edge of the AuthBinding entity.
func (_m *AuthBinding) QueryAccount() *AccountQuery {
	return NewAuthBindingClient(_m.config).QueryAccount(_m)
}

// QueryProject queries the "project" edge of the AuthBinding entity.
func (_m *AuthBinding) QueryProject() *ProjectQuery {
	return NewAuthBindingClient(_m.config).QueryProject(_m)
}

// Update returns a builder for updating this AuthBinding.
// Note that you need to call AuthBinding.Unwrap() before calling this method if this AuthBinding
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AuthBinding) Update() *AuthBindingUpdateOne {
	return NewAuthBindingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AuthBinding entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AuthBinding) Unwrap() *AuthBinding {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AuthBinding is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AuthBinding) String() string {
	var builder strings.Builder
	builder.WriteString("AuthBinding(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.Id))
	builder.WriteString("binding_id=")
	builder.WriteString(_m.BindingId)
	builder.WriteString(", ")
	builder.WriteString("auth_backend=")
	builder.WriteString(_m.AuthBackend)
	builder.WriteString(", ")
	builder.WriteString("scope=")
	builder.WriteString(_m.Scope)
	builder.WriteString(", ")
	builder.WriteString("credential_ref=")
	builder.WriteString(_m.CredentialRef)
	builder.WriteString(", ")
	builder.WriteString("date_updated=")
	builder.WriteString(_m.DateUpdated.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DateErased; v != nil {
		builder.WriteString("date_erased=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("date_created=")
	builder.WriteString(_m.DateCreated.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountId))
	builder.WriteString(", ")
	builder.WriteString("project_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProjectId))
	builder.WriteByte(')')
	return builder.String()
}

// AuthBindingList is a parsable slice of AuthBinding.
type AuthBindingList []*AuthBinding
