// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/lesomnus/cxz/internal/ent/authbinding"
	"github.com/lesomnus/cxz/internal/ent/predicate"
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	"github.com/protobuf-orm/ent/schema/field"
)

// AuthBindingDelete is the builder for deleting a AuthBinding entity.
type AuthBindingDelete struct {
	config
	hooks    []Hook
	mutation *AuthBindingMutation
}

// Where appends a list predicates to the AuthBindingDelete builder.
func (_d *AuthBindingDelete) Where(ps ...predicate.AuthBinding) *AuthBindingDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AuthBindingDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AuthBindingDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AuthBindingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(authbinding.Table, sqlgraph.NewFieldSpec(authbinding.FieldId, field.TypeUuid))
	if ps := _d.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AuthBindingDeleteOne is the builder for deleting a single AuthBinding entity.
type AuthBindingDeleteOne struct {
	_d *AuthBindingDelete
}

// Where appends a list predicates to the AuthBindingDelete builder.
func (_d *AuthBindingDeleteOne) Where(ps ...predicate.AuthBinding) *AuthBindingDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AuthBindingDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{authbinding.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AuthBindingDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
