// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: cxz/session.proto

package ent

import (
	resource "github.com/lesomnus/cxz/resource"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	uuid "uuid"
)

func (e *Session) Proto() *resource.Session {
	x := &resource.Session{}
	x.SetId(e.Id[:])
	x.SetName(e.Name)
	x.SetDesc(e.Desc)
	if v := e.Edges.Project; v != nil {
		x.SetProject(v.Proto())
	} else if v := e.ProjectId; v != *new(uuid.UUID) {
		r := &resource.Project{}
		r.SetId(v[:])
		x.SetProject(r)
	}
	x.SetAgent(e.Agent)
	x.SetModel(e.Model)
	x.SetRuntimeId(e.RuntimeId)
	x.SetClientId(e.ClientId)
	x.SetDateUpdated(timestamppb.New(e.DateUpdated))
	if e.DateErased != nil {
		x.SetDateErased(timestamppb.New(*e.DateErased))
	}
	x.SetDateCreated(timestamppb.New(e.DateCreated))
	if e.Status != nil {
		x.SetStatus(e.Status)
	}
	x.SetListed(e.Listed)
	return x
}
