// Code generated by ent, DO NOT EDIT.

package project

import (
	"context"
	"fmt"
	"time"

	"github.com/lesomnus/cxz/internal/ent/predicate"
	"github.com/lesomnus/cxz/resource"
	"github.com/protobuf-orm/ent"
	"github.com/protobuf-orm/ent/dialect/sql"
)

// Mutation represents an operation that mutates the Project nodes in the graph.
type Mutation struct {
	op            ent.Op
	typ           string
	alias         *string
	name          *string
	desc          *string
	workspace     *string
	_config       *string
	runtime_id    *string
	date_updated  *time.Time
	date_erased   *time.Time
	date_created  *time.Time
	status        **resource.ProjectStatus
	listed        *bool
	clearedFields map[string]struct{}
	predicates    []predicate.Project
}

// NewMutation creates a new Mutation for the Project entity.
func NewMutation(op ent.Op) *Mutation {
	return &Mutation{
		op:            op,
		typ:           "Project",
		clearedFields: make(map[string]struct{}),
	}
}

// Predicates returns the list of predicates set on the mutation.
func (m *Mutation) Predicates() []predicate.Project {
	return m.predicates
}

// SetAlias sets the "alias" field.
func (m *Mutation) SetAlias(s string) {
	m.alias = &s
}

// Alias returns the value of the "alias" field in the mutation.
func (m *Mutation) Alias() (r string, exists bool) {
	v := m.alias
	if v == nil {
		return
	}
	return *v, true
}

// ResetAlias resets all changes to the "alias" field.
func (m *Mutation) ResetAlias() {
	m.alias = nil
}

// SetName sets the "name" field.
func (m *Mutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *Mutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// ResetName resets all changes to the "name" field.
func (m *Mutation) ResetName() {
	m.name = nil
}

// SetDesc sets the "desc" field.
func (m *Mutation) SetDesc(s string) {
	m.desc = &s
}

// Desc returns the value of the "desc" field in the mutation.
func (m *Mutation) Desc() (r string, exists bool) {
	v := m.desc
	if v == nil {
		return
	}
	return *v, true
}

// ResetDesc resets all changes to the "desc" field.
func (m *Mutation) ResetDesc() {
	m.desc = nil
}

// SetWorkspace sets the "workspace" field.
func (m *Mutation) SetWorkspace(s string) {
	m.workspace = &s
}

// Workspace returns the value of the "workspace" field in the mutation.
func (m *Mutation) Workspace() (r string, exists bool) {
	v := m.workspace
	if v == nil {
		return
	}
	return *v, true
}

// ResetWorkspace resets all changes to the "workspace" field.
func (m *Mutation) ResetWorkspace() {
	m.workspace = nil
}

// SetConfig sets the "config" field.
func (m *Mutation) SetConfig(s string) {
	m._config = &s
}

// Config returns the value of the "config" field in the mutation.
func (m *Mutation) Config() (r string, exists bool) {
	v := m._config
	if v == nil {
		return
	}
	return *v, true
}

// ResetConfig resets all changes to the "config" field.
func (m *Mutation) ResetConfig() {
	m._config = nil
}

// SetRuntimeId sets the "runtime_id" field.
func (m *Mutation) SetRuntimeId(s string) {
	m.runtime_id = &s
}

// RuntimeId returns the value of the "runtime_id" field in the mutation.
func (m *Mutation) RuntimeId() (r string, exists bool) {
	v := m.runtime_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetRuntimeId resets all changes to the "runtime_id" field.
func (m *Mutation) ResetRuntimeId() {
	m.runtime_id = nil
}

// SetDateUpdated sets the "date_updated" field.
func (m *Mutation) SetDateUpdated(t time.Time) {
	m.date_updated = &t
}

// DateUpdated returns the value of the "date_updated" field in the mutation.
func (m *Mutation) DateUpdated() (r time.Time, exists bool) {
	v := m.date_updated
	if v == nil {
		return
	}
	return *v, true
}

// ResetDateUpdated resets all changes to the "date_updated" field.
func (m *Mutation) ResetDateUpdated() {
	m.date_updated = nil
}

// SetDateErased sets the "date_erased" field.
func (m *Mutation) SetDateErased(t time.Time) {
	m.date_erased = &t
}

// DateErased returns the value of the "date_erased" field in the mutation.
func (m *Mutation) DateErased() (r time.Time, exists bool) {
	v := m.date_erased
	if v == nil {
		return
	}
	return *v, true
}

// ClearDateErased clears the value of the "date_erased" field.
func (m *Mutation) ClearDateErased() {
	m.date_erased = nil
	m.clearedFields[FieldDateErased] = struct{}{}
}

// DateErasedCleared returns if the "date_erased" field was cleared in this mutation.
func (m *Mutation) DateErasedCleared() bool {
	_, ok := m.clearedFields[FieldDateErased]
	return ok
}

// ResetDateErased resets all changes to the "date_erased" field.
func (m *Mutation) ResetDateErased() {
	m.date_erased = nil
	delete(m.clearedFields, FieldDateErased)
}

// SetDateCreated sets the "date_created" field.
func (m *Mutation) SetDateCreated(t time.Time) {
	m.date_created = &t
}

// DateCreated returns the value of the "date_created" field in the mutation.
func (m *Mutation) DateCreated() (r time.Time, exists bool) {
	v := m.date_created
	if v == nil {
		return
	}
	return *v, true
}

// ClearDateCreated clears the value of the "date_created" field.
func (m *Mutation) ClearDateCreated() {
	m.date_created = nil
	m.clearedFields[FieldDateCreated] = struct{}{}
}

// DateCreatedCleared returns if the "date_created" field was cleared in this mutation.
func (m *Mutation) DateCreatedCleared() bool {
	_, ok := m.clearedFields[FieldDateCreated]
	return ok
}

// ResetDateCreated resets all changes to the "date_created" field.
func (m *Mutation) ResetDateCreated() {
	m.date_created = nil
	delete(m.clearedFields, FieldDateCreated)
}

// SetStatus sets the "status" field.
func (m *Mutation) SetStatus(rs *resource.ProjectStatus) {
	m.status = &rs
}

// Status returns the value of the "status" field in the mutation.
func (m *Mutation) Status() (r *resource.ProjectStatus, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// ClearStatus clears the value of the "status" field.
func (m *Mutation) ClearStatus() {
	m.status = nil
	m.clearedFields[FieldStatus] = struct{}{}
}

// StatusCleared returns if the "status" field was cleared in this mutation.
func (m *Mutation) StatusCleared() bool {
	_, ok := m.clearedFields[FieldStatus]
	return ok
}

// ResetStatus resets all changes to the "status" field.
func (m *Mutation) ResetStatus() {
	m.status = nil
	delete(m.clearedFields, FieldStatus)
}

// SetListed sets the "listed" field.
func (m *Mutation) SetListed(b bool) {
	m.listed = &b
}

// Listed returns the value of the "listed" field in the mutation.
func (m *Mutation) Listed() (r bool, exists bool) {
	v := m.listed
	if v == nil {
		return
	}
	return *v, true
}

// ClearListed clears the value of the "listed" field.
func (m *Mutation) ClearListed() {
	m.listed = nil
	m.clearedFields[FieldListed] = struct{}{}
}

// ListedCleared returns if the "listed" field was cleared in this mutation.
func (m *Mutation) ListedCleared() bool {
	_, ok := m.clearedFields[FieldListed]
	return ok
}

// ResetListed resets all changes to the "listed" field.
func (m *Mutation) ResetListed() {
	m.listed = nil
	delete(m.clearedFields, FieldListed)
}

// Where appends a list predicates to the Mutation builder.
func (m *Mutation) Where(ps ...predicate.Project) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the Mutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *Mutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Project, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *Mutation) Op() ent.Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *Mutation) SetOp(op ent.Op) {
	m.op = op
}

// Type returns the node type of this mutation (Project).
func (m *Mutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *Mutation) Fields() []string {
	fields := make([]string, 0, 11)
	if m.alias != nil {
		fields = append(fields, FieldAlias)
	}
	if m.name != nil {
		fields = append(fields, FieldName)
	}
	if m.desc != nil {
		fields = append(fields, FieldDesc)
	}
	if m.workspace != nil {
		fields = append(fields, FieldWorkspace)
	}
	if m._config != nil {
		fields = append(fields, FieldConfig)
	}
	if m.runtime_id != nil {
		fields = append(fields, FieldRuntimeId)
	}
	if m.date_updated != nil {
		fields = append(fields, FieldDateUpdated)
	}
	if m.date_erased != nil {
		fields = append(fields, FieldDateErased)
	}
	if m.date_created != nil {
		fields = append(fields, FieldDateCreated)
	}
	if m.status != nil {
		fields = append(fields, FieldStatus)
	}
	if m.listed != nil {
		fields = append(fields, FieldListed)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *Mutation) Field(name string) (ent.Value, bool) {
	switch name {
	case FieldAlias:
		return m.Alias()
	case FieldName:
		return m.Name()
	case FieldDesc:
		return m.Desc()
	case FieldWorkspace:
		return m.Workspace()
	case FieldConfig:
		return m.Config()
	case FieldRuntimeId:
		return m.RuntimeId()
	case FieldDateUpdated:
		return m.DateUpdated()
	case FieldDateErased:
		return m.DateErased()
	case FieldDateCreated:
		return m.DateCreated()
	case FieldStatus:
		return m.Status()
	case FieldListed:
		return m.Listed()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *Mutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	return nil, fmt.Errorf("unknown Project field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *Mutation) SetField(name string, value ent.Value) error {
	switch name {
	case FieldAlias:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAlias(v)
		return nil
	case FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case FieldDesc:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDesc(v)
		return nil
	case FieldWorkspace:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetWorkspace(v)
		return nil
	case FieldConfig:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetConfig(v)
		return nil
	case FieldRuntimeId:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRuntimeId(v)
		return nil
	case FieldDateUpdated:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDateUpdated(v)
		return nil
	case FieldDateErased:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDateErased(v)
		return nil
	case FieldDateCreated:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDateCreated(v)
		return nil
	case FieldStatus:
		v, ok := value.(*resource.ProjectStatus)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case FieldListed:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetListed(v)
		return nil
	}
	return fmt.Errorf("unknown Project field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *Mutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *Mutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *Mutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Project numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *Mutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(FieldDateErased) {
		fields = append(fields, FieldDateErased)
	}
	if m.FieldCleared(FieldDateCreated) {
		fields = append(fields, FieldDateCreated)
	}
	if m.FieldCleared(FieldStatus) {
		fields = append(fields, FieldStatus)
	}
	if m.FieldCleared(FieldListed) {
		fields = append(fields, FieldListed)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *Mutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *Mutation) ClearField(name string) error {
	switch name {
	case FieldDateErased:
		m.ClearDateErased()
		return nil
	case FieldDateCreated:
		m.ClearDateCreated()
		return nil
	case FieldStatus:
		m.ClearStatus()
		return nil
	case FieldListed:
		m.ClearListed()
		return nil
	}
	return fmt.Errorf("unknown Project nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *Mutation) ResetField(name string) error {
	switch name {
	case FieldAlias:
		m.ResetAlias()
		return nil
	case FieldName:
		m.ResetName()
		return nil
	case FieldDesc:
		m.ResetDesc()
		return nil
	case FieldWorkspace:
		m.ResetWorkspace()
		return nil
	case FieldConfig:
		m.ResetConfig()
		return nil
	case FieldRuntimeId:
		m.ResetRuntimeId()
		return nil
	case FieldDateUpdated:
		m.ResetDateUpdated()
		return nil
	case FieldDateErased:
		m.ResetDateErased()
		return nil
	case FieldDateCreated:
		m.ResetDateCreated()
		return nil
	case FieldStatus:
		m.ResetStatus()
		return nil
	case FieldListed:
		m.ResetListed()
		return nil
	}
	return fmt.Errorf("unknown Project field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *Mutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIds returns all Ids (to other nodes) that were added for the given edge
// name in this mutation.
func (m *Mutation) AddedIds(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *Mutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIds returns all Ids (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *Mutation) RemovedIds(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *Mutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *Mutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *Mutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Project unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *Mutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Project edge %s", name)
}
