// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cxz/auth_binding_svc.g.proto

package resource

import (
	patchpb "github.com/lesomnus/protobuf-patch/patchpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthBindingAddRequest struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id            []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_BindingId     string                 `protobuf:"bytes,4,opt,name=binding_id,json=bindingId"`
	xxx_hidden_Account       *AccountRef            `protobuf:"bytes,8,opt,name=account"`
	xxx_hidden_Project       *ProjectRef            `protobuf:"bytes,9,opt,name=project"`
	xxx_hidden_AuthBackend   string                 `protobuf:"bytes,10,opt,name=auth_backend,json=authBackend"`
	xxx_hidden_Scope         string                 `protobuf:"bytes,11,opt,name=scope"`
	xxx_hidden_CredentialRef string                 `protobuf:"bytes,12,opt,name=credential_ref,json=credentialRef"`
	xxx_hidden_DateCreated   *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=date_created,json=dateCreated"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *AuthBindingAddRequest) Reset() {
	*x = AuthBindingAddRequest{}
	mi := &file_cxz_auth_binding_svc_g_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthBindingAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthBindingAddRequest) ProtoMessage() {}

func (x *AuthBindingAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cxz_auth_binding_svc_g_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuthBindingAddRequest) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *AuthBindingAddRequest) GetBindingId() string {
	if x != nil {
		return x.xxx_hidden_BindingId
	}
	return ""
}

func (x *AuthBindingAddRequest) GetAccount() *AccountRef {
	if x != nil {
		return x.xxx_hidden_Account
	}
	return nil
}

func (x *AuthBindingAddRequest) GetProject() *ProjectRef {
	if x != nil {
		return x.xxx_hidden_Project
	}
	return nil
}

func (x *AuthBindingAddRequest) GetAuthBackend() string {
	if x != nil {
		return x.xxx_hidden_AuthBackend
	}
	return ""
}

func (x *AuthBindingAddRequest) GetScope() string {
	if x != nil {
		return x.xxx_hidden_Scope
	}
	return ""
}

func (x *AuthBindingAddRequest) GetCredentialRef() string {
	if x != nil {
		return x.xxx_hidden_CredentialRef
	}
	return ""
}

func (x *AuthBindingAddRequest) GetDateCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return nil
}

func (x *AuthBindingAddRequest) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 8)
}

func (x *AuthBindingAddRequest) SetBindingId(v string) {
	x.xxx_hidden_BindingId = v
}

func (x *AuthBindingAddRequest) SetAccount(v *AccountRef) {
	x.xxx_hidden_Account = v
}

func (x *AuthBindingAddRequest) SetProject(v *ProjectRef) {
	x.xxx_hidden_Project = v
}

func (x *AuthBindingAddRequest) SetAuthBackend(v string) {
	x.xxx_hidden_AuthBackend = v
}

func (x *AuthBindingAddRequest) SetScope(v string) {
	x.xxx_hidden_Scope = v
}

func (x *AuthBindingAddRequest) SetCredentialRef(v string) {
	x.xxx_hidden_CredentialRef = v
}

func (x *AuthBindingAddRequest) SetDateCreated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateCreated = v
}

func (x *AuthBindingAddRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AuthBindingAddRequest) HasAccount() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Account != nil
}

func (x *AuthBindingAddRequest) HasProject() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Project != nil
}

func (x *AuthBindingAddRequest) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateCreated != nil
}

func (x *AuthBindingAddRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *AuthBindingAddRequest) ClearAccount() {
	x.xxx_hidden_Account = nil
}

func (x *AuthBindingAddRequest) ClearProject() {
	x.xxx_hidden_Project = nil
}

func (x *AuthBindingAddRequest) ClearDateCreated() {
	x.xxx_hidden_DateCreated = nil
}

type AuthBindingAddRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id            []byte
	BindingId     string
	Account       *AccountRef
	Project       *ProjectRef
	AuthBackend   string
	Scope         string
	CredentialRef string
	DateCreated   *timestamppb.Timestamp
}

func (b0 AuthBindingAddRequest_builder) Build() *AuthBindingAddRequest {
	m0 := &AuthBindingAddRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 8)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_BindingId = b.BindingId
	x.xxx_hidden_Account = b.Account
	x.xxx_hidden_Project = b.Project
	x.xxx_hidden_AuthBackend = b.AuthBackend
	x.xxx_hidden_Scope = b.Scope
	x.xxx_hidden_CredentialRef = b.CredentialRef
	x.xxx_hidden_DateCreated = b.DateCreated
	return m0
}

type AuthBindingGetRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref    *AuthBindingRef        `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Select *AuthBindingSelect     `protobuf:"bytes,2,opt,name=select"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AuthBindingGetRequest) Reset() {
	*x = AuthBindingGetRequest{}
	mi := &file_cxz_auth_binding_svc_g_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthBindingGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthBindingGetRequest) ProtoMessage() {}

func (x *AuthBindingGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cxz_auth_binding_svc_g_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuthBindingGetRequest) GetRef() *AuthBindingRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *AuthBindingGetRequest) GetSelect() *AuthBindingSelect {
	if x != nil {
		return x.xxx_hidden_Select
	}
	return nil
}

func (x *AuthBindingGetRequest) SetRef(v *AuthBindingRef) {
	x.xxx_hidden_Ref = v
}

func (x *AuthBindingGetRequest) SetSelect(v *AuthBindingSelect) {
	x.xxx_hidden_Select = v
}

func (x *AuthBindingGetRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *AuthBindingGetRequest) HasSelect() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Select != nil
}

func (x *AuthBindingGetRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *AuthBindingGetRequest) ClearSelect() {
	x.xxx_hidden_Select = nil
}

type AuthBindingGetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref    *AuthBindingRef
	Select *AuthBindingSelect
}

func (b0 AuthBindingGetRequest_builder) Build() *AuthBindingGetRequest {
	m0 := &AuthBindingGetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Select = b.Select
	return m0
}

type AuthBindingRef struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key isAuthBindingRef_Key   `protobuf_oneof:"key"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuthBindingRef) Reset() {
	*x = AuthBindingRef{}
	mi := &file_cxz_auth_binding_svc_g_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthBindingRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthBindingRef) ProtoMessage() {}

func (x *AuthBindingRef) ProtoReflect() protoreflect.Message {
	mi := &file_cxz_auth_binding_svc_g_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuthBindingRef) GetId() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Key.(*authBindingRef_Id); ok {
			return x.Id
		}
	}
	return nil
}

func (x *AuthBindingRef) GetBindingId() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Key.(*authBindingRef_BindingId); ok {
			return x.BindingId
		}
	}
	return ""
}

func (x *AuthBindingRef) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Key = &authBindingRef_Id{v}
}

func (x *AuthBindingRef) SetBindingId(v string) {
	x.xxx_hidden_Key = &authBindingRef_BindingId{v}
}

func (x *AuthBindingRef) HasKey() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Key != nil
}

func (x *AuthBindingRef) HasId() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Key.(*authBindingRef_Id)
	return ok
}

func (x *AuthBindingRef) HasBindingId() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Key.(*authBindingRef_BindingId)
	return ok
}

func (x *AuthBindingRef) ClearKey() {
	x.xxx_hidden_Key = nil
}

func (x *AuthBindingRef) ClearId() {
	if _, ok := x.xxx_hidden_Key.(*authBindingRef_Id); ok {
		x.xxx_hidden_Key = nil
	}
}

func (x *AuthBindingRef) ClearBindingId() {
	if _, ok := x.xxx_hidden_Key.(*authBindingRef_BindingId); ok {
		x.xxx_hidden_Key = nil
	}
}

const AuthBindingRef_Key_not_set_case case_AuthBindingRef_Key = 0
const AuthBindingRef_Id_case case_AuthBindingRef_Key = 1
const AuthBindingRef_BindingId_case case_AuthBindingRef_Key = 4

func (x *AuthBindingRef) WhichKey() case_AuthBindingRef_Key {
	if x == nil {
		return AuthBindingRef_Key_not_set_case
	}
	switch x.xxx_hidden_Key.(type) {
	case *authBindingRef_Id:
		return AuthBindingRef_Id_case
	case *authBindingRef_BindingId:
		return AuthBindingRef_BindingId_case
	default:
		return AuthBindingRef_Key_not_set_case
	}
}

type AuthBindingRef_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Key:
	Id        []byte
	BindingId *string
	// -- end of xxx_hidden_Key
}

func (b0 AuthBindingRef_builder) Build() *AuthBindingRef {
	m0 := &AuthBindingRef{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		x.xxx_hidden_Key = &authBindingRef_Id{b.Id}
	}
	if b.BindingId != nil {
		x.xxx_hidden_Key = &authBindingRef_BindingId{*b.BindingId}
	}
	return m0
}

type case_AuthBindingRef_Key protoreflect.FieldNumber

func (x case_AuthBindingRef_Key) String() string {
	md := file_cxz_auth_binding_svc_g_proto_msgTypes[2].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isAuthBindingRef_Key interface {
	isAuthBindingRef_Key()
}

type authBindingRef_Id struct {
	Id []byte `protobuf:"bytes,1,opt,name=id,oneof"`
}

type authBindingRef_BindingId struct {
	BindingId string `protobuf:"bytes,4,opt,name=binding_id,json=bindingId,oneof"`
}

func (*authBindingRef_Id) isAuthBindingRef_Key() {}

func (*authBindingRef_BindingId) isAuthBindingRef_Key() {}

type AuthBindingSelect struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_All           bool                   `protobuf:"varint,1,opt,name=all"`
	xxx_hidden_BindingId     bool                   `protobuf:"varint,4,opt,name=binding_id,json=bindingId"`
	xxx_hidden_Account       *AccountSelect         `protobuf:"bytes,8,opt,name=account"`
	xxx_hidden_Project       *ProjectSelect         `protobuf:"bytes,9,opt,name=project"`
	xxx_hidden_AuthBackend   bool                   `protobuf:"varint,10,opt,name=auth_backend,json=authBackend"`
	xxx_hidden_Scope         bool                   `protobuf:"varint,11,opt,name=scope"`
	xxx_hidden_CredentialRef bool                   `protobuf:"varint,12,opt,name=credential_ref,json=credentialRef"`
	xxx_hidden_DateUpdated   bool                   `protobuf:"varint,13,opt,name=date_updated,json=dateUpdated"`
	xxx_hidden_DateErased    bool                   `protobuf:"varint,14,opt,name=date_erased,json=dateErased"`
	xxx_hidden_DateCreated   bool                   `protobuf:"varint,15,opt,name=date_created,json=dateCreated"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *AuthBindingSelect) Reset() {
	*x = AuthBindingSelect{}
	mi := &file_cxz_auth_binding_svc_g_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthBindingSelect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthBindingSelect) ProtoMessage() {}

func (x *AuthBindingSelect) ProtoReflect() protoreflect.Message {
	mi := &file_cxz_auth_binding_svc_g_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuthBindingSelect) GetAll() bool {
	if x != nil {
		return x.xxx_hidden_All
	}
	return false
}

func (x *AuthBindingSelect) GetBindingId() bool {
	if x != nil {
		return x.xxx_hidden_BindingId
	}
	return false
}

func (x *AuthBindingSelect) GetAccount() *AccountSelect {
	if x != nil {
		return x.xxx_hidden_Account
	}
	return nil
}

func (x *AuthBindingSelect) GetProject() *ProjectSelect {
	if x != nil {
		return x.xxx_hidden_Project
	}
	return nil
}

func (x *AuthBindingSelect) GetAuthBackend() bool {
	if x != nil {
		return x.xxx_hidden_AuthBackend
	}
	return false
}

func (x *AuthBindingSelect) GetScope() bool {
	if x != nil {
		return x.xxx_hidden_Scope
	}
	return false
}

func (x *AuthBindingSelect) GetCredentialRef() bool {
	if x != nil {
		return x.xxx_hidden_CredentialRef
	}
	return false
}

func (x *AuthBindingSelect) GetDateUpdated() bool {
	if x != nil {
		return x.xxx_hidden_DateUpdated
	}
	return false
}

func (x *AuthBindingSelect) GetDateErased() bool {
	if x != nil {
		return x.xxx_hidden_DateErased
	}
	return false
}

func (x *AuthBindingSelect) GetDateCreated() bool {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return false
}

func (x *AuthBindingSelect) SetAll(v bool) {
	x.xxx_hidden_All = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 10)
}

func (x *AuthBindingSelect) SetBindingId(v bool) {
	x.xxx_hidden_BindingId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 10)
}

func (x *AuthBindingSelect) SetAccount(v *AccountSelect) {
	x.xxx_hidden_Account = v
}

func (x *AuthBindingSelect) SetProject(v *ProjectSelect) {
	x.xxx_hidden_Project = v
}

func (x *AuthBindingSelect) SetAuthBackend(v bool) {
	x.xxx_hidden_AuthBackend = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 10)
}

func (x *AuthBindingSelect) SetScope(v bool) {
	x.xxx_hidden_Scope = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 10)
}

func (x *AuthBindingSelect) SetCredentialRef(v bool) {
	x.xxx_hidden_CredentialRef = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 10)
}

func (x *AuthBindingSelect) SetDateUpdated(v bool) {
	x.xxx_hidden_DateUpdated = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 10)
}

func (x *AuthBindingSelect) SetDateErased(v bool) {
	x.xxx_hidden_DateErased = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 10)
}

func (x *AuthBindingSelect) SetDateCreated(v bool) {
	x.xxx_hidden_DateCreated = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 10)
}

func (x *AuthBindingSelect) HasAll() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AuthBindingSelect) HasBindingId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AuthBindingSelect) HasAccount() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Account != nil
}

func (x *AuthBindingSelect) HasProject() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Project != nil
}

func (x *AuthBindingSelect) HasAuthBackend() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *AuthBindingSelect) HasScope() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *AuthBindingSelect) HasCredentialRef() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *AuthBindingSelect) HasDateUpdated() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *AuthBindingSelect) HasDateErased() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *AuthBindingSelect) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *AuthBindingSelect) ClearAll() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_All = false
}

func (x *AuthBindingSelect) ClearBindingId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_BindingId = false
}

func (x *AuthBindingSelect) ClearAccount() {
	x.xxx_hidden_Account = nil
}

func (x *AuthBindingSelect) ClearProject() {
	x.xxx_hidden_Project = nil
}

func (x *AuthBindingSelect) ClearAuthBackend() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_AuthBackend = false
}

func (x *AuthBindingSelect) ClearScope() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Scope = false
}

func (x *AuthBindingSelect) ClearCredentialRef() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_CredentialRef = false
}

func (x *AuthBindingSelect) ClearDateUpdated() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_DateUpdated = false
}

func (x *AuthBindingSelect) ClearDateErased() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_DateErased = false
}

func (x *AuthBindingSelect) ClearDateCreated() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_DateCreated = false
}

type AuthBindingSelect_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	All           *bool
	BindingId     *bool
	Account       *AccountSelect
	Project       *ProjectSelect
	AuthBackend   *bool
	Scope         *bool
	CredentialRef *bool
	DateUpdated   *bool
	DateErased    *bool
	DateCreated   *bool
}

func (b0 AuthBindingSelect_builder) Build() *AuthBindingSelect {
	m0 := &AuthBindingSelect{}
	b, x := &b0, m0
	_, _ = b, x
	if b.All != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 10)
		x.xxx_hidden_All = *b.All
	}
	if b.BindingId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 10)
		x.xxx_hidden_BindingId = *b.BindingId
	}
	x.xxx_hidden_Account = b.Account
	x.xxx_hidden_Project = b.Project
	if b.AuthBackend != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 10)
		x.xxx_hidden_AuthBackend = *b.AuthBackend
	}
	if b.Scope != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 10)
		x.xxx_hidden_Scope = *b.Scope
	}
	if b.CredentialRef != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 10)
		x.xxx_hidden_CredentialRef = *b.CredentialRef
	}
	if b.DateUpdated != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 10)
		x.xxx_hidden_DateUpdated = *b.DateUpdated
	}
	if b.DateErased != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 10)
		x.xxx_hidden_DateErased = *b.DateErased
	}
	if b.DateCreated != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 10)
		x.xxx_hidden_DateCreated = *b.DateCreated
	}
	return m0
}

type AuthBindingPatchRequest struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref              *AuthBindingRef        `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_DateUpdated      *timestamppb.Timestamp `protobuf:"bytes,26,opt,name=date_updated,json=dateUpdated"`
	xxx_hidden_DateUpdatedForce bool                   `protobuf:"varint,27,opt,name=date_updated_force,json=dateUpdatedForce"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *AuthBindingPatchRequest) Reset() {
	*x = AuthBindingPatchRequest{}
	mi := &file_cxz_auth_binding_svc_g_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthBindingPatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthBindingPatchRequest) ProtoMessage() {}

func (x *AuthBindingPatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cxz_auth_binding_svc_g_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuthBindingPatchRequest) GetRef() *AuthBindingRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *AuthBindingPatchRequest) GetDateUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateUpdated
	}
	return nil
}

func (x *AuthBindingPatchRequest) GetDateUpdatedForce() bool {
	if x != nil {
		return x.xxx_hidden_DateUpdatedForce
	}
	return false
}

func (x *AuthBindingPatchRequest) SetRef(v *AuthBindingRef) {
	x.xxx_hidden_Ref = v
}

func (x *AuthBindingPatchRequest) SetDateUpdated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateUpdated = v
}

func (x *AuthBindingPatchRequest) SetDateUpdatedForce(v bool) {
	x.xxx_hidden_DateUpdatedForce = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *AuthBindingPatchRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *AuthBindingPatchRequest) HasDateUpdated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateUpdated != nil
}

func (x *AuthBindingPatchRequest) HasDateUpdatedForce() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *AuthBindingPatchRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *AuthBindingPatchRequest) ClearDateUpdated() {
	x.xxx_hidden_DateUpdated = nil
}

func (x *AuthBindingPatchRequest) ClearDateUpdatedForce() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_DateUpdatedForce = false
}

type AuthBindingPatchRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref *AuthBindingRef
	// The version this update requires the stored date_updated to be.
	// It is a precondition, not a write: the update applies only if the row
	// still holds this value, and the server stamps the new version itself.
	// Setting it together with date_updated_force is an error --
	// the version is the token every client's compare-and-swap is measured
	// against, so it is not the caller's to choose.
	DateUpdated *timestamppb.Timestamp
	// Update whatever the stored date_updated is, with no precondition.
	// The server still stamps a new version, so other clients' tokens are
	// invalidated as usual; this declines the check for THIS update only.
	// One of date_updated or this must be set. An omitted version is
	// refused rather than assumed, because an unset field cannot be told
	// apart from a caller who never considered locking at all.
	DateUpdatedForce *bool
}

func (b0 AuthBindingPatchRequest_builder) Build() *AuthBindingPatchRequest {
	m0 := &AuthBindingPatchRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_DateUpdated = b.DateUpdated
	if b.DateUpdatedForce != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_DateUpdatedForce = *b.DateUpdatedForce
	}
	return m0
}

type AuthBindingApplyRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref   *AuthBindingRef        `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Patch *patchpb.Patch         `protobuf:"bytes,2,opt,name=patch"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AuthBindingApplyRequest) Reset() {
	*x = AuthBindingApplyRequest{}
	mi := &file_cxz_auth_binding_svc_g_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthBindingApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthBindingApplyRequest) ProtoMessage() {}

func (x *AuthBindingApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cxz_auth_binding_svc_g_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuthBindingApplyRequest) GetRef() *AuthBindingRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *AuthBindingApplyRequest) GetPatch() *patchpb.Patch {
	if x != nil {
		return x.xxx_hidden_Patch
	}
	return nil
}

func (x *AuthBindingApplyRequest) SetRef(v *AuthBindingRef) {
	x.xxx_hidden_Ref = v
}

func (x *AuthBindingApplyRequest) SetPatch(v *patchpb.Patch) {
	x.xxx_hidden_Patch = v
}

func (x *AuthBindingApplyRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *AuthBindingApplyRequest) HasPatch() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Patch != nil
}

func (x *AuthBindingApplyRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *AuthBindingApplyRequest) ClearPatch() {
	x.xxx_hidden_Patch = nil
}

type AuthBindingApplyRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref   *AuthBindingRef
	Patch *patchpb.Patch
}

func (b0 AuthBindingApplyRequest_builder) Build() *AuthBindingApplyRequest {
	m0 := &AuthBindingApplyRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Patch = b.Patch
	return m0
}

type AuthBindingEraseResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Erased      bool                   `protobuf:"varint,1,opt,name=erased"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AuthBindingEraseResponse) Reset() {
	*x = AuthBindingEraseResponse{}
	mi := &file_cxz_auth_binding_svc_g_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthBindingEraseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthBindingEraseResponse) ProtoMessage() {}

func (x *AuthBindingEraseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cxz_auth_binding_svc_g_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuthBindingEraseResponse) GetErased() bool {
	if x != nil {
		return x.xxx_hidden_Erased
	}
	return false
}

func (x *AuthBindingEraseResponse) SetErased(v bool) {
	x.xxx_hidden_Erased = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *AuthBindingEraseResponse) HasErased() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AuthBindingEraseResponse) ClearErased() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Erased = false
}

type AuthBindingEraseResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Erased is whether this call is the one that erased the row.
	//
	// False for a row that was already gone, was never there, or is out
	// of this caller's reach -- which are one answer on purpose, and the
	// reason the RPC does not fail instead.
	Erased *bool
}

func (b0 AuthBindingEraseResponse_builder) Build() *AuthBindingEraseResponse {
	m0 := &AuthBindingEraseResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Erased != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Erased = *b.Erased
	}
	return m0
}

type AuthBindingListRequest struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Filters *[]*AuthBindingFilter  `protobuf:"bytes,1,rep,name=filters"`
	xxx_hidden_Size    int32                  `protobuf:"varint,2,opt,name=size"`
	xxx_hidden_After   string                 `protobuf:"bytes,3,opt,name=after"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AuthBindingListRequest) Reset() {
	*x = AuthBindingListRequest{}
	mi := &file_cxz_auth_binding_svc_g_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthBindingListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthBindingListRequest) ProtoMessage() {}

func (x *AuthBindingListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cxz_auth_binding_svc_g_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuthBindingListRequest) GetFilters() []*AuthBindingFilter {
	if x != nil {
		if x.xxx_hidden_Filters != nil {
			return *x.xxx_hidden_Filters
		}
	}
	return nil
}

func (x *AuthBindingListRequest) GetSize() int32 {
	if x != nil {
		return x.xxx_hidden_Size
	}
	return 0
}

func (x *AuthBindingListRequest) GetAfter() string {
	if x != nil {
		return x.xxx_hidden_After
	}
	return ""
}

func (x *AuthBindingListRequest) SetFilters(v []*AuthBindingFilter) {
	x.xxx_hidden_Filters = &v
}

func (x *AuthBindingListRequest) SetSize(v int32) {
	x.xxx_hidden_Size = v
}

func (x *AuthBindingListRequest) SetAfter(v string) {
	x.xxx_hidden_After = v
}

type AuthBindingListRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Bounded because the work is: each filter is a predicate in the same query,
	// so this is what says how much of the database one request may read.
	Filters []*AuthBindingFilter
	// How many to answer with. Nothing said is what the schema declared, and more
	// than the cap is the cap -- a caller asking for more than there is meant no
	// harm, so it is not an error and it is not the whole table either.
	Size int32
	// Where to carry on from: the "next" of the answer before. It names the last
	// row of that page rather than counting rows from the start, so a row added
	// ahead of the page does not shift it and a caller reading through never sees
	// one twice or misses one.
	After string
}

func (b0 AuthBindingListRequest_builder) Build() *AuthBindingListRequest {
	m0 := &AuthBindingListRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Filters = &b.Filters
	x.xxx_hidden_Size = b.Size
	x.xxx_hidden_After = b.After
	return m0
}

type AuthBindingListResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Items *[]*AuthBinding        `protobuf:"bytes,1,rep,name=items"`
	xxx_hidden_Next  string                 `protobuf:"bytes,2,opt,name=next"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AuthBindingListResponse) Reset() {
	*x = AuthBindingListResponse{}
	mi := &file_cxz_auth_binding_svc_g_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthBindingListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthBindingListResponse) ProtoMessage() {}

func (x *AuthBindingListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cxz_auth_binding_svc_g_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuthBindingListResponse) GetItems() []*AuthBinding {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *AuthBindingListResponse) GetNext() string {
	if x != nil {
		return x.xxx_hidden_Next
	}
	return ""
}

func (x *AuthBindingListResponse) SetItems(v []*AuthBinding) {
	x.xxx_hidden_Items = &v
}

func (x *AuthBindingListResponse) SetNext(v string) {
	x.xxx_hidden_Next = v
}

type AuthBindingListResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Items []*AuthBinding
	// What to ask for next, and empty when this was the last of them.
	//
	// Empty means there is no more *for now*: a list is read as it is, and one
	// that has grown since answers a fresh call. It is not empty merely because
	// the page came back short -- a page is short when the last row of it was the
	// last row there was, which is a thing the server can only know by having
	// looked.
	Next string
}

func (b0 AuthBindingListResponse_builder) Build() *AuthBindingListResponse {
	m0 := &AuthBindingListResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = &b.Items
	x.xxx_hidden_Next = b.Next
	return m0
}

type AuthBindingFilter struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref     *AuthBindingRef        `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Account *AccountRef            `protobuf:"bytes,2,opt,name=account"`
	xxx_hidden_Project *ProjectRef            `protobuf:"bytes,3,opt,name=project"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AuthBindingFilter) Reset() {
	*x = AuthBindingFilter{}
	mi := &file_cxz_auth_binding_svc_g_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthBindingFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthBindingFilter) ProtoMessage() {}

func (x *AuthBindingFilter) ProtoReflect() protoreflect.Message {
	mi := &file_cxz_auth_binding_svc_g_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuthBindingFilter) GetRef() *AuthBindingRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *AuthBindingFilter) GetAccount() *AccountRef {
	if x != nil {
		return x.xxx_hidden_Account
	}
	return nil
}

func (x *AuthBindingFilter) GetProject() *ProjectRef {
	if x != nil {
		return x.xxx_hidden_Project
	}
	return nil
}

func (x *AuthBindingFilter) SetRef(v *AuthBindingRef) {
	x.xxx_hidden_Ref = v
}

func (x *AuthBindingFilter) SetAccount(v *AccountRef) {
	x.xxx_hidden_Account = v
}

func (x *AuthBindingFilter) SetProject(v *ProjectRef) {
	x.xxx_hidden_Project = v
}

func (x *AuthBindingFilter) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *AuthBindingFilter) HasAccount() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Account != nil
}

func (x *AuthBindingFilter) HasProject() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Project != nil
}

func (x *AuthBindingFilter) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *AuthBindingFilter) ClearAccount() {
	x.xxx_hidden_Account = nil
}

func (x *AuthBindingFilter) ClearProject() {
	x.xxx_hidden_Project = nil
}

type AuthBindingFilter_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref     *AuthBindingRef
	Account *AccountRef
	Project *ProjectRef
}

func (b0 AuthBindingFilter_builder) Build() *AuthBindingFilter {
	m0 := &AuthBindingFilter{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Account = b.Account
	x.xxx_hidden_Project = b.Project
	return m0
}

type AuthBindingWatchRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Filters      *[]*AuthBindingFilter  `protobuf:"bytes,1,rep,name=filters"`
	xxx_hidden_SkipSnapshot bool                   `protobuf:"varint,2,opt,name=skip_snapshot,json=skipSnapshot"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *AuthBindingWatchRequest) Reset() {
	*x = AuthBindingWatchRequest{}
	mi := &file_cxz_auth_binding_svc_g_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthBindingWatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthBindingWatchRequest) ProtoMessage() {}

func (x *AuthBindingWatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cxz_auth_binding_svc_g_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuthBindingWatchRequest) GetFilters() []*AuthBindingFilter {
	if x != nil {
		if x.xxx_hidden_Filters != nil {
			return *x.xxx_hidden_Filters
		}
	}
	return nil
}

func (x *AuthBindingWatchRequest) GetSkipSnapshot() bool {
	if x != nil {
		return x.xxx_hidden_SkipSnapshot
	}
	return false
}

func (x *AuthBindingWatchRequest) SetFilters(v []*AuthBindingFilter) {
	x.xxx_hidden_Filters = &v
}

func (x *AuthBindingWatchRequest) SetSkipSnapshot(v bool) {
	x.xxx_hidden_SkipSnapshot = v
}

type AuthBindingWatchRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Which rows to watch, in the same words List takes them: what is watched is
	// what that list would answer with, now and afterwards.
	//
	// Required, and bounded the way a List is -- for a heavier reason. A list
	// runs its filters once; a watch runs them again for every write that touches
	// the entity, for as long as the stream is open. A watch with no filters is
	// the whole table, forever, which is the one shape that has no cap at all.
	Filters []*AuthBindingFilter
	// Skip what is there now and send only what changes from here.
	//
	// Off by default, and the default is the safe one: a client that does not
	// know the current state and did not ask for it holds something wrong until
	// the next write happens to correct it.
	SkipSnapshot bool
}

func (b0 AuthBindingWatchRequest_builder) Build() *AuthBindingWatchRequest {
	m0 := &AuthBindingWatchRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Filters = &b.Filters
	x.xxx_hidden_SkipSnapshot = b.SkipSnapshot
	return m0
}

type AuthBindingWatchResponse struct {
	state            protoimpl.MessageState   `protogen:"opaque.v1"`
	xxx_hidden_Items *[]*AuthBindingWatchItem `protobuf:"bytes,1,rep,name=items"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AuthBindingWatchResponse) Reset() {
	*x = AuthBindingWatchResponse{}
	mi := &file_cxz_auth_binding_svc_g_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthBindingWatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthBindingWatchResponse) ProtoMessage() {}

func (x *AuthBindingWatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cxz_auth_binding_svc_g_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuthBindingWatchResponse) GetItems() []*AuthBindingWatchItem {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *AuthBindingWatchResponse) SetItems(v []*AuthBindingWatchItem) {
	x.xxx_hidden_Items = &v
}

type AuthBindingWatchResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// What changed, or -- in the first message -- everything that matches.
	Items []*AuthBindingWatchItem
}

func (b0 AuthBindingWatchResponse_builder) Build() *AuthBindingWatchResponse {
	m0 := &AuthBindingWatchResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = &b.Items
	return m0
}

type AuthBindingWatchItem struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Value       *AuthBinding           `protobuf:"bytes,2,opt,name=value"`
	xxx_hidden_Action      string                 `protobuf:"bytes,3,opt,name=action"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AuthBindingWatchItem) Reset() {
	*x = AuthBindingWatchItem{}
	mi := &file_cxz_auth_binding_svc_g_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthBindingWatchItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthBindingWatchItem) ProtoMessage() {}

func (x *AuthBindingWatchItem) ProtoReflect() protoreflect.Message {
	mi := &file_cxz_auth_binding_svc_g_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuthBindingWatchItem) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *AuthBindingWatchItem) GetValue() *AuthBinding {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return nil
}

func (x *AuthBindingWatchItem) GetAction() string {
	if x != nil {
		return x.xxx_hidden_Action
	}
	return ""
}

func (x *AuthBindingWatchItem) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *AuthBindingWatchItem) SetValue(v *AuthBinding) {
	x.xxx_hidden_Value = v
}

func (x *AuthBindingWatchItem) SetAction(v string) {
	x.xxx_hidden_Action = v
}

func (x *AuthBindingWatchItem) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AuthBindingWatchItem) HasValue() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Value != nil
}

func (x *AuthBindingWatchItem) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *AuthBindingWatchItem) ClearValue() {
	x.xxx_hidden_Value = nil
}

type AuthBindingWatchItem_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Which row. Always said, since one that is gone still has to be named.
	Id []byte
	// The row as it is now, and **absent when it is no longer one this caller may
	// see**: erased, or moved out of the filters this stream named.
	//
	// Absence is the whole of how a removal is said. There is no flag for it, and
	// there is deliberately no way to tell those two apart -- a stream that
	// distinguished "erased" from "no longer yours" would be telling a caller
	// about rows that stopped being theirs, which is the thing the wall is for.
	//
	// It is only ever said about a row this stream has already carried. One that
	// never matched is not news.
	Value *AuthBinding
	// The RPC that changed it, by the name gRPC knows it by. It is what the
	// caller of *that* RPC asked for and not the write it became, so an RPC
	// written by hand is here under its own name.
	//
	// Empty in the first message, which is not something anybody asked for -- it
	// is what is already there.
	Action string
}

func (b0 AuthBindingWatchItem_builder) Build() *AuthBindingWatchItem {
	m0 := &AuthBindingWatchItem{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_Value = b.Value
	x.xxx_hidden_Action = b.Action
	return m0
}

var File_cxz_auth_binding_svc_g_proto protoreflect.FileDescriptor

const file_cxz_auth_binding_svc_g_proto_rawDesc = "" +
	"\n" +
	"\x1ccxz/auth_binding_svc.g.proto\x12\x03cxz\x1a\x17cxz/account_svc.g.proto\x1a\x16cxz/auth_binding.proto\x1a\x17cxz/project_svc.g.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x11patch/patch.proto\"\xd7\x02\n" +
	"\x15AuthBindingAddRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12$\n" +
	"\n" +
	"binding_id\x18\x04 \x01(\tB\x05\xaa\x01\x02\b\x02R\tbindingId\x12)\n" +
	"\aaccount\x18\b \x01(\v2\x0f.cxz.AccountRefR\aaccount\x12)\n" +
	"\aproject\x18\t \x01(\v2\x0f.cxz.ProjectRefR\aproject\x12(\n" +
	"\fauth_backend\x18\n" +
	" \x01(\tB\x05\xaa\x01\x02\b\x02R\vauthBackend\x12\x1b\n" +
	"\x05scope\x18\v \x01(\tB\x05\xaa\x01\x02\b\x02R\x05scope\x12,\n" +
	"\x0ecredential_ref\x18\f \x01(\tB\x05\xaa\x01\x02\b\x02R\rcredentialRef\x12=\n" +
	"\fdate_created\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\vdateCreated\"n\n" +
	"\x15AuthBindingGetRequest\x12%\n" +
	"\x03ref\x18\x01 \x01(\v2\x13.cxz.AuthBindingRefR\x03ref\x12.\n" +
	"\x06select\x18\x02 \x01(\v2\x16.cxz.AuthBindingSelectR\x06select\"J\n" +
	"\x0eAuthBindingRef\x12\x10\n" +
	"\x02id\x18\x01 \x01(\fH\x00R\x02id\x12\x1f\n" +
	"\n" +
	"binding_id\x18\x04 \x01(\tH\x00R\tbindingIdB\x05\n" +
	"\x03key\"\xe7\x02\n" +
	"\x11AuthBindingSelect\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\x12\x1d\n" +
	"\n" +
	"binding_id\x18\x04 \x01(\bR\tbindingId\x12,\n" +
	"\aaccount\x18\b \x01(\v2\x12.cxz.AccountSelectR\aaccount\x12,\n" +
	"\aproject\x18\t \x01(\v2\x12.cxz.ProjectSelectR\aproject\x12!\n" +
	"\fauth_backend\x18\n" +
	" \x01(\bR\vauthBackend\x12\x14\n" +
	"\x05scope\x18\v \x01(\bR\x05scope\x12%\n" +
	"\x0ecredential_ref\x18\f \x01(\bR\rcredentialRef\x12!\n" +
	"\fdate_updated\x18\r \x01(\bR\vdateUpdated\x12\x1f\n" +
	"\vdate_erased\x18\x0e \x01(\bR\n" +
	"dateErased\x12!\n" +
	"\fdate_created\x18\x0f \x01(\bR\vdateCreated\"\xad\x01\n" +
	"\x17AuthBindingPatchRequest\x12%\n" +
	"\x03ref\x18\x01 \x01(\v2\x13.cxz.AuthBindingRefR\x03ref\x12=\n" +
	"\fdate_updated\x18\x1a \x01(\v2\x1a.google.protobuf.TimestampR\vdateUpdated\x12,\n" +
	"\x12date_updated_force\x18\x1b \x01(\bR\x10dateUpdatedForce\"d\n" +
	"\x17AuthBindingApplyRequest\x12%\n" +
	"\x03ref\x18\x01 \x01(\v2\x13.cxz.AuthBindingRefR\x03ref\x12\"\n" +
	"\x05patch\x18\x02 \x01(\v2\f.patch.PatchR\x05patch\"2\n" +
	"\x18AuthBindingEraseResponse\x12\x16\n" +
	"\x06erased\x18\x01 \x01(\bR\x06erased\"\x82\x01\n" +
	"\x16AuthBindingListRequest\x120\n" +
	"\afilters\x18\x01 \x03(\v2\x16.cxz.AuthBindingFilterR\afilters\x12\x19\n" +
	"\x04size\x18\x02 \x01(\x05B\x05\xaa\x01\x02\b\x02R\x04size\x12\x1b\n" +
	"\x05after\x18\x03 \x01(\tB\x05\xaa\x01\x02\b\x02R\x05after\"\\\n" +
	"\x17AuthBindingListResponse\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.cxz.AuthBindingR\x05items\x12\x19\n" +
	"\x04next\x18\x02 \x01(\tB\x05\xaa\x01\x02\b\x02R\x04next\"\x90\x01\n" +
	"\x11AuthBindingFilter\x12%\n" +
	"\x03ref\x18\x01 \x01(\v2\x13.cxz.AuthBindingRefR\x03ref\x12)\n" +
	"\aaccount\x18\x02 \x01(\v2\x0f.cxz.AccountRefR\aaccount\x12)\n" +
	"\aproject\x18\x03 \x01(\v2\x0f.cxz.ProjectRefR\aproject\"w\n" +
	"\x17AuthBindingWatchRequest\x120\n" +
	"\afilters\x18\x01 \x03(\v2\x16.cxz.AuthBindingFilterR\afilters\x12*\n" +
	"\rskip_snapshot\x18\x02 \x01(\bB\x05\xaa\x01\x02\b\x02R\fskipSnapshot\"K\n" +
	"\x18AuthBindingWatchResponse\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.cxz.AuthBindingWatchItemR\x05items\"m\n" +
	"\x14AuthBindingWatchItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.cxz.AuthBindingR\x05value\x12\x1d\n" +
	"\x06action\x18\x03 \x01(\tB\x05\xaa\x01\x02\b\x02R\x06action2\xb8\x03\n" +
	"\x12AuthBindingService\x123\n" +
	"\x03Add\x12\x1a.cxz.AuthBindingAddRequest\x1a\x10.cxz.AuthBinding\x123\n" +
	"\x03Get\x12\x1a.cxz.AuthBindingGetRequest\x1a\x10.cxz.AuthBinding\x127\n" +
	"\x05Patch\x12\x1c.cxz.AuthBindingPatchRequest\x1a\x10.cxz.AuthBinding\x127\n" +
	"\x05Apply\x12\x1c.cxz.AuthBindingApplyRequest\x1a\x10.cxz.AuthBinding\x12;\n" +
	"\x05Erase\x12\x13.cxz.AuthBindingRef\x1a\x1d.cxz.AuthBindingEraseResponse\x12A\n" +
	"\x04List\x12\x1b.cxz.AuthBindingListRequest\x1a\x1c.cxz.AuthBindingListResponse\x12F\n" +
	"\x05Watch\x12\x1c.cxz.AuthBindingWatchRequest\x1a\x1d.cxz.AuthBindingWatchResponse0\x01B\"Z github.com/lesomnus/cxz/resourceb\beditionsp\xe8\a"

var file_cxz_auth_binding_svc_g_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_cxz_auth_binding_svc_g_proto_goTypes = []any{
	(*AuthBindingAddRequest)(nil),    // 0: cxz.AuthBindingAddRequest
	(*AuthBindingGetRequest)(nil),    // 1: cxz.AuthBindingGetRequest
	(*AuthBindingRef)(nil),           // 2: cxz.AuthBindingRef
	(*AuthBindingSelect)(nil),        // 3: cxz.AuthBindingSelect
	(*AuthBindingPatchRequest)(nil),  // 4: cxz.AuthBindingPatchRequest
	(*AuthBindingApplyRequest)(nil),  // 5: cxz.AuthBindingApplyRequest
	(*AuthBindingEraseResponse)(nil), // 6: cxz.AuthBindingEraseResponse
	(*AuthBindingListRequest)(nil),   // 7: cxz.AuthBindingListRequest
	(*AuthBindingListResponse)(nil),  // 8: cxz.AuthBindingListResponse
	(*AuthBindingFilter)(nil),        // 9: cxz.AuthBindingFilter
	(*AuthBindingWatchRequest)(nil),  // 10: cxz.AuthBindingWatchRequest
	(*AuthBindingWatchResponse)(nil), // 11: cxz.AuthBindingWatchResponse
	(*AuthBindingWatchItem)(nil),     // 12: cxz.AuthBindingWatchItem
	(*AccountRef)(nil),               // 13: cxz.AccountRef
	(*ProjectRef)(nil),               // 14: cxz.ProjectRef
	(*timestamppb.Timestamp)(nil),    // 15: google.protobuf.Timestamp
	(*AccountSelect)(nil),            // 16: cxz.AccountSelect
	(*ProjectSelect)(nil),            // 17: cxz.ProjectSelect
	(*patchpb.Patch)(nil),            // 18: patch.Patch
	(*AuthBinding)(nil),              // 19: cxz.AuthBinding
}
var file_cxz_auth_binding_svc_g_proto_depIdxs = []int32{
	13, // 0: cxz.AuthBindingAddRequest.account:type_name -> cxz.AccountRef
	14, // 1: cxz.AuthBindingAddRequest.project:type_name -> cxz.ProjectRef
	15, // 2: cxz.AuthBindingAddRequest.date_created:type_name -> google.protobuf.Timestamp
	2,  // 3: cxz.AuthBindingGetRequest.ref:type_name -> cxz.AuthBindingRef
	3,  // 4: cxz.AuthBindingGetRequest.select:type_name -> cxz.AuthBindingSelect
	16, // 5: cxz.AuthBindingSelect.account:type_name -> cxz.AccountSelect
	17, // 6: cxz.AuthBindingSelect.project:type_name -> cxz.ProjectSelect
	2,  // 7: cxz.AuthBindingPatchRequest.ref:type_name -> cxz.AuthBindingRef
	15, // 8: cxz.AuthBindingPatchRequest.date_updated:type_name -> google.protobuf.Timestamp
	2,  // 9: cxz.AuthBindingApplyRequest.ref:type_name -> cxz.AuthBindingRef
	18, // 10: cxz.AuthBindingApplyRequest.patch:type_name -> patch.Patch
	9,  // 11: cxz.AuthBindingListRequest.filters:type_name -> cxz.AuthBindingFilter
	19, // 12: cxz.AuthBindingListResponse.items:type_name -> cxz.AuthBinding
	2,  // 13: cxz.AuthBindingFilter.ref:type_name -> cxz.AuthBindingRef
	13, // 14: cxz.AuthBindingFilter.account:type_name -> cxz.AccountRef
	14, // 15: cxz.AuthBindingFilter.project:type_name -> cxz.ProjectRef
	9,  // 16: cxz.AuthBindingWatchRequest.filters:type_name -> cxz.AuthBindingFilter
	12, // 17: cxz.AuthBindingWatchResponse.items:type_name -> cxz.AuthBindingWatchItem
	19, // 18: cxz.AuthBindingWatchItem.value:type_name -> cxz.AuthBinding
	0,  // 19: cxz.AuthBindingService.Add:input_type -> cxz.AuthBindingAddRequest
	1,  // 20: cxz.AuthBindingService.Get:input_type -> cxz.AuthBindingGetRequest
	4,  // 21: cxz.AuthBindingService.Patch:input_type -> cxz.AuthBindingPatchRequest
	5,  // 22: cxz.AuthBindingService.Apply:input_type -> cxz.AuthBindingApplyRequest
	2,  // 23: cxz.AuthBindingService.Erase:input_type -> cxz.AuthBindingRef
	7,  // 24: cxz.AuthBindingService.List:input_type -> cxz.AuthBindingListRequest
	10, // 25: cxz.AuthBindingService.Watch:input_type -> cxz.AuthBindingWatchRequest
	19, // 26: cxz.AuthBindingService.Add:output_type -> cxz.AuthBinding
	19, // 27: cxz.AuthBindingService.Get:output_type -> cxz.AuthBinding
	19, // 28: cxz.AuthBindingService.Patch:output_type -> cxz.AuthBinding
	19, // 29: cxz.AuthBindingService.Apply:output_type -> cxz.AuthBinding
	6,  // 30: cxz.AuthBindingService.Erase:output_type -> cxz.AuthBindingEraseResponse
	8,  // 31: cxz.AuthBindingService.List:output_type -> cxz.AuthBindingListResponse
	11, // 32: cxz.AuthBindingService.Watch:output_type -> cxz.AuthBindingWatchResponse
	26, // [26:33] is the sub-list for method output_type
	19, // [19:26] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_cxz_auth_binding_svc_g_proto_init() }
func file_cxz_auth_binding_svc_g_proto_init() {
	if File_cxz_auth_binding_svc_g_proto != nil {
		return
	}
	file_cxz_account_svc_g_proto_init()
	file_cxz_auth_binding_proto_init()
	file_cxz_project_svc_g_proto_init()
	file_cxz_auth_binding_svc_g_proto_msgTypes[2].OneofWrappers = []any{
		(*authBindingRef_Id)(nil),
		(*authBindingRef_BindingId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cxz_auth_binding_svc_g_proto_rawDesc), len(file_cxz_auth_binding_svc_g_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cxz_auth_binding_svc_g_proto_goTypes,
		DependencyIndexes: file_cxz_auth_binding_svc_g_proto_depIdxs,
		MessageInfos:      file_cxz_auth_binding_svc_g_proto_msgTypes,
	}.Build()
	File_cxz_auth_binding_svc_g_proto = out.File
	file_cxz_auth_binding_svc_g_proto_goTypes = nil
	file_cxz_auth_binding_svc_g_proto_depIdxs = nil
}
