// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: cxz/project_svc.g.proto

package resource

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProjectService_Add_FullMethodName            = "/cxz.ProjectService/Add"
	ProjectService_Get_FullMethodName            = "/cxz.ProjectService/Get"
	ProjectService_Patch_FullMethodName          = "/cxz.ProjectService/Patch"
	ProjectService_Apply_FullMethodName          = "/cxz.ProjectService/Apply"
	ProjectService_Erase_FullMethodName          = "/cxz.ProjectService/Erase"
	ProjectService_List_FullMethodName           = "/cxz.ProjectService/List"
	ProjectService_Watch_FullMethodName          = "/cxz.ProjectService/Watch"
	ProjectService_Terminal_FullMethodName       = "/cxz.ProjectService/Terminal"
	ProjectService_SessionLogin_FullMethodName   = "/cxz.ProjectService/SessionLogin"
	ProjectService_Paths_FullMethodName          = "/cxz.ProjectService/Paths"
	ProjectService_Devcontainer_FullMethodName   = "/cxz.ProjectService/Devcontainer"
	ProjectService_Docker_FullMethodName         = "/cxz.ProjectService/Docker"
	ProjectService_FileMappings_FullMethodName   = "/cxz.ProjectService/FileMappings"
	ProjectService_Up_FullMethodName             = "/cxz.ProjectService/Up"
	ProjectService_Down_FullMethodName           = "/cxz.ProjectService/Down"
	ProjectService_Recreate_FullMethodName       = "/cxz.ProjectService/Recreate"
	ProjectService_InspectForeign_FullMethodName = "/cxz.ProjectService/InspectForeign"
)

// ProjectServiceClient is the client API for ProjectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProjectServiceClient interface {
	// Add creates a new Project
	Add(ctx context.Context, in *ProjectAddRequest, opts ...grpc.CallOption) (*Project, error)
	// Get retrieves a Project
	Get(ctx context.Context, in *ProjectGetRequest, opts ...grpc.CallOption) (*Project, error)
	// Patch updates an existing Project
	Patch(ctx context.Context, in *ProjectPatchRequest, opts ...grpc.CallOption) (*Project, error)
	// Apply applies a patch document to an existing Project
	Apply(ctx context.Context, in *ProjectApplyRequest, opts ...grpc.CallOption) (*Project, error)
	// Erase deletes a Project
	Erase(ctx context.Context, in *ProjectRef, opts ...grpc.CallOption) (*ProjectEraseResponse, error)
	// List reads Projects a page at a time.
	List(ctx context.Context, in *ProjectListRequest, opts ...grpc.CallOption) (*ProjectListResponse, error)
	// Watch the Projects this caller may see, as they are now and as they change.
	//
	// What arrives is **state and never a delta**, so a client converges rather
	// than replays: it keeps what it was last told about a row and replaces it.
	// An event it did not receive is one it does not need, since the next one
	// about that row carries the whole of it.
	//
	// The first message is everything that matches right now, so a client does
	// not have to List first and race the subscription. A row may arrive twice --
	// once in that first message and once as a change that happened while it was
	// being read -- and that is harmless for the same reason.
	Watch(ctx context.Context, in *ProjectWatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProjectWatchResponse], error)
	// Ephemeral PTY on the manager host. First frame identifies a project and size;
	// later frames carry input or a resize. Terminal bytes are never journaled.
	Terminal(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProjectTerminalRequest, ProjectTerminalReply], error)
	// Ephemeral login transport. First frame identifies the session profile;
	// subsequent frames carry stdin only. These frames are never journaled.
	SessionLogin(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProjectLoginRequest, ProjectLoginOutput], error)
	// Read immediate directory entries inside the project's container as its remote user.
	Paths(ctx context.Context, in *ProjectPathsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProjectPathsReply], error)
	Devcontainer(ctx context.Context, in *DevcontainerRequest, opts ...grpc.CallOption) (*DevcontainerReply, error)
	Docker(ctx context.Context, in *DockerRequest, opts ...grpc.CallOption) (*DockerReply, error)
	FileMappings(ctx context.Context, in *FileMappingsRequest, opts ...grpc.CallOption) (*FileMappingsReply, error)
	// Provision/start a registered workspace. This never creates a conversation.
	Up(ctx context.Context, in *ProjectUpRequest, opts ...grpc.CallOption) (*Project, error)
	// Remove owned containers, retaining the resource, workspace and volumes.
	Down(ctx context.Context, in *ProjectControl, opts ...grpc.CallOption) (*Project, error)
	// Replace only explicitly confirmed targets. Foreign containers are not adopted.
	Recreate(ctx context.Context, in *ProjectRecreateRequest, opts ...grpc.CallOption) (*Project, error)
	// Foreign inventory is not part of the registered Project resource list.
	InspectForeign(ctx context.Context, in *InspectForeignRequest, opts ...grpc.CallOption) (*InspectForeignResponse, error)
}

type projectServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProjectServiceClient(cc grpc.ClientConnInterface) ProjectServiceClient {
	return &projectServiceClient{cc}
}

func (c *projectServiceClient) Add(ctx context.Context, in *ProjectAddRequest, opts ...grpc.CallOption) (*Project, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Project)
	err := c.cc.Invoke(ctx, ProjectService_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) Get(ctx context.Context, in *ProjectGetRequest, opts ...grpc.CallOption) (*Project, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Project)
	err := c.cc.Invoke(ctx, ProjectService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) Patch(ctx context.Context, in *ProjectPatchRequest, opts ...grpc.CallOption) (*Project, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Project)
	err := c.cc.Invoke(ctx, ProjectService_Patch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) Apply(ctx context.Context, in *ProjectApplyRequest, opts ...grpc.CallOption) (*Project, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Project)
	err := c.cc.Invoke(ctx, ProjectService_Apply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) Erase(ctx context.Context, in *ProjectRef, opts ...grpc.CallOption) (*ProjectEraseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectEraseResponse)
	err := c.cc.Invoke(ctx, ProjectService_Erase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) List(ctx context.Context, in *ProjectListRequest, opts ...grpc.CallOption) (*ProjectListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectListResponse)
	err := c.cc.Invoke(ctx, ProjectService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) Watch(ctx context.Context, in *ProjectWatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProjectWatchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProjectService_ServiceDesc.Streams[0], ProjectService_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProjectWatchRequest, ProjectWatchResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProjectService_WatchClient = grpc.ServerStreamingClient[ProjectWatchResponse]

func (c *projectServiceClient) Terminal(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProjectTerminalRequest, ProjectTerminalReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProjectService_ServiceDesc.Streams[1], ProjectService_Terminal_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProjectTerminalRequest, ProjectTerminalReply]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProjectService_TerminalClient = grpc.BidiStreamingClient[ProjectTerminalRequest, ProjectTerminalReply]

func (c *projectServiceClient) SessionLogin(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProjectLoginRequest, ProjectLoginOutput], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProjectService_ServiceDesc.Streams[2], ProjectService_SessionLogin_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProjectLoginRequest, ProjectLoginOutput]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProjectService_SessionLoginClient = grpc.BidiStreamingClient[ProjectLoginRequest, ProjectLoginOutput]

func (c *projectServiceClient) Paths(ctx context.Context, in *ProjectPathsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProjectPathsReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProjectService_ServiceDesc.Streams[3], ProjectService_Paths_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProjectPathsRequest, ProjectPathsReply]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProjectService_PathsClient = grpc.ServerStreamingClient[ProjectPathsReply]

func (c *projectServiceClient) Devcontainer(ctx context.Context, in *DevcontainerRequest, opts ...grpc.CallOption) (*DevcontainerReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DevcontainerReply)
	err := c.cc.Invoke(ctx, ProjectService_Devcontainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) Docker(ctx context.Context, in *DockerRequest, opts ...grpc.CallOption) (*DockerReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DockerReply)
	err := c.cc.Invoke(ctx, ProjectService_Docker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) FileMappings(ctx context.Context, in *FileMappingsRequest, opts ...grpc.CallOption) (*FileMappingsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileMappingsReply)
	err := c.cc.Invoke(ctx, ProjectService_FileMappings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) Up(ctx context.Context, in *ProjectUpRequest, opts ...grpc.CallOption) (*Project, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Project)
	err := c.cc.Invoke(ctx, ProjectService_Up_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) Down(ctx context.Context, in *ProjectControl, opts ...grpc.CallOption) (*Project, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Project)
	err := c.cc.Invoke(ctx, ProjectService_Down_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) Recreate(ctx context.Context, in *ProjectRecreateRequest, opts ...grpc.CallOption) (*Project, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Project)
	err := c.cc.Invoke(ctx, ProjectService_Recreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) InspectForeign(ctx context.Context, in *InspectForeignRequest, opts ...grpc.CallOption) (*InspectForeignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InspectForeignResponse)
	err := c.cc.Invoke(ctx, ProjectService_InspectForeign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProjectServiceServer is the server API for ProjectService service.
// All implementations must embed UnimplementedProjectServiceServer
// for forward compatibility.
type ProjectServiceServer interface {
	// Add creates a new Project
	Add(context.Context, *ProjectAddRequest) (*Project, error)
	// Get retrieves a Project
	Get(context.Context, *ProjectGetRequest) (*Project, error)
	// Patch updates an existing Project
	Patch(context.Context, *ProjectPatchRequest) (*Project, error)
	// Apply applies a patch document to an existing Project
	Apply(context.Context, *ProjectApplyRequest) (*Project, error)
	// Erase deletes a Project
	Erase(context.Context, *ProjectRef) (*ProjectEraseResponse, error)
	// List reads Projects a page at a time.
	List(context.Context, *ProjectListRequest) (*ProjectListResponse, error)
	// Watch the Projects this caller may see, as they are now and as they change.
	//
	// What arrives is **state and never a delta**, so a client converges rather
	// than replays: it keeps what it was last told about a row and replaces it.
	// An event it did not receive is one it does not need, since the next one
	// about that row carries the whole of it.
	//
	// The first message is everything that matches right now, so a client does
	// not have to List first and race the subscription. A row may arrive twice --
	// once in that first message and once as a change that happened while it was
	// being read -- and that is harmless for the same reason.
	Watch(*ProjectWatchRequest, grpc.ServerStreamingServer[ProjectWatchResponse]) error
	// Ephemeral PTY on the manager host. First frame identifies a project and size;
	// later frames carry input or a resize. Terminal bytes are never journaled.
	Terminal(grpc.BidiStreamingServer[ProjectTerminalRequest, ProjectTerminalReply]) error
	// Ephemeral login transport. First frame identifies the session profile;
	// subsequent frames carry stdin only. These frames are never journaled.
	SessionLogin(grpc.BidiStreamingServer[ProjectLoginRequest, ProjectLoginOutput]) error
	// Read immediate directory entries inside the project's container as its remote user.
	Paths(*ProjectPathsRequest, grpc.ServerStreamingServer[ProjectPathsReply]) error
	Devcontainer(context.Context, *DevcontainerRequest) (*DevcontainerReply, error)
	Docker(context.Context, *DockerRequest) (*DockerReply, error)
	FileMappings(context.Context, *FileMappingsRequest) (*FileMappingsReply, error)
	// Provision/start a registered workspace. This never creates a conversation.
	Up(context.Context, *ProjectUpRequest) (*Project, error)
	// Remove owned containers, retaining the resource, workspace and volumes.
	Down(context.Context, *ProjectControl) (*Project, error)
	// Replace only explicitly confirmed targets. Foreign containers are not adopted.
	Recreate(context.Context, *ProjectRecreateRequest) (*Project, error)
	// Foreign inventory is not part of the registered Project resource list.
	InspectForeign(context.Context, *InspectForeignRequest) (*InspectForeignResponse, error)
	mustEmbedUnimplementedProjectServiceServer()
}

// UnimplementedProjectServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProjectServiceServer struct{}

func (UnimplementedProjectServiceServer) Add(context.Context, *ProjectAddRequest) (*Project, error) {
	return nil, status.Error(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedProjectServiceServer) Get(context.Context, *ProjectGetRequest) (*Project, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedProjectServiceServer) Patch(context.Context, *ProjectPatchRequest) (*Project, error) {
	return nil, status.Error(codes.Unimplemented, "method Patch not implemented")
}
func (UnimplementedProjectServiceServer) Apply(context.Context, *ProjectApplyRequest) (*Project, error) {
	return nil, status.Error(codes.Unimplemented, "method Apply not implemented")
}
func (UnimplementedProjectServiceServer) Erase(context.Context, *ProjectRef) (*ProjectEraseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Erase not implemented")
}
func (UnimplementedProjectServiceServer) List(context.Context, *ProjectListRequest) (*ProjectListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedProjectServiceServer) Watch(*ProjectWatchRequest, grpc.ServerStreamingServer[ProjectWatchResponse]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedProjectServiceServer) Terminal(grpc.BidiStreamingServer[ProjectTerminalRequest, ProjectTerminalReply]) error {
	return status.Error(codes.Unimplemented, "method Terminal not implemented")
}
func (UnimplementedProjectServiceServer) SessionLogin(grpc.BidiStreamingServer[ProjectLoginRequest, ProjectLoginOutput]) error {
	return status.Error(codes.Unimplemented, "method SessionLogin not implemented")
}
func (UnimplementedProjectServiceServer) Paths(*ProjectPathsRequest, grpc.ServerStreamingServer[ProjectPathsReply]) error {
	return status.Error(codes.Unimplemented, "method Paths not implemented")
}
func (UnimplementedProjectServiceServer) Devcontainer(context.Context, *DevcontainerRequest) (*DevcontainerReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Devcontainer not implemented")
}
func (UnimplementedProjectServiceServer) Docker(context.Context, *DockerRequest) (*DockerReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Docker not implemented")
}
func (UnimplementedProjectServiceServer) FileMappings(context.Context, *FileMappingsRequest) (*FileMappingsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method FileMappings not implemented")
}
func (UnimplementedProjectServiceServer) Up(context.Context, *ProjectUpRequest) (*Project, error) {
	return nil, status.Error(codes.Unimplemented, "method Up not implemented")
}
func (UnimplementedProjectServiceServer) Down(context.Context, *ProjectControl) (*Project, error) {
	return nil, status.Error(codes.Unimplemented, "method Down not implemented")
}
func (UnimplementedProjectServiceServer) Recreate(context.Context, *ProjectRecreateRequest) (*Project, error) {
	return nil, status.Error(codes.Unimplemented, "method Recreate not implemented")
}
func (UnimplementedProjectServiceServer) InspectForeign(context.Context, *InspectForeignRequest) (*InspectForeignResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InspectForeign not implemented")
}
func (UnimplementedProjectServiceServer) mustEmbedUnimplementedProjectServiceServer() {}
func (UnimplementedProjectServiceServer) testEmbeddedByValue()                        {}

// UnsafeProjectServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProjectServiceServer will
// result in compilation errors.
type UnsafeProjectServiceServer interface {
	mustEmbedUnimplementedProjectServiceServer()
}

func RegisterProjectServiceServer(s grpc.ServiceRegistrar, srv ProjectServiceServer) {
	// If the following call panics, it indicates UnimplementedProjectServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProjectService_ServiceDesc, srv)
}

func _ProjectService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).Add(ctx, req.(*ProjectAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).Get(ctx, req.(*ProjectGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_Patch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectPatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).Patch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_Patch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).Patch(ctx, req.(*ProjectPatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_Apply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).Apply(ctx, req.(*ProjectApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_Erase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).Erase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_Erase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).Erase(ctx, req.(*ProjectRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).List(ctx, req.(*ProjectListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProjectWatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProjectServiceServer).Watch(m, &grpc.GenericServerStream[ProjectWatchRequest, ProjectWatchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProjectService_WatchServer = grpc.ServerStreamingServer[ProjectWatchResponse]

func _ProjectService_Terminal_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProjectServiceServer).Terminal(&grpc.GenericServerStream[ProjectTerminalRequest, ProjectTerminalReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProjectService_TerminalServer = grpc.BidiStreamingServer[ProjectTerminalRequest, ProjectTerminalReply]

func _ProjectService_SessionLogin_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProjectServiceServer).SessionLogin(&grpc.GenericServerStream[ProjectLoginRequest, ProjectLoginOutput]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProjectService_SessionLoginServer = grpc.BidiStreamingServer[ProjectLoginRequest, ProjectLoginOutput]

func _ProjectService_Paths_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProjectPathsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProjectServiceServer).Paths(m, &grpc.GenericServerStream[ProjectPathsRequest, ProjectPathsReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProjectService_PathsServer = grpc.ServerStreamingServer[ProjectPathsReply]

func _ProjectService_Devcontainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DevcontainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).Devcontainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_Devcontainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).Devcontainer(ctx, req.(*DevcontainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_Docker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DockerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).Docker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_Docker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).Docker(ctx, req.(*DockerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_FileMappings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileMappingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).FileMappings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_FileMappings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).FileMappings(ctx, req.(*FileMappingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_Up_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).Up(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_Up_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).Up(ctx, req.(*ProjectUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_Down_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectControl)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).Down(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_Down_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).Down(ctx, req.(*ProjectControl))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_Recreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRecreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).Recreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_Recreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).Recreate(ctx, req.(*ProjectRecreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_InspectForeign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InspectForeignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).InspectForeign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_InspectForeign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).InspectForeign(ctx, req.(*InspectForeignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProjectService_ServiceDesc is the grpc.ServiceDesc for ProjectService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProjectService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cxz.ProjectService",
	HandlerType: (*ProjectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _ProjectService_Add_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ProjectService_Get_Handler,
		},
		{
			MethodName: "Patch",
			Handler:    _ProjectService_Patch_Handler,
		},
		{
			MethodName: "Apply",
			Handler:    _ProjectService_Apply_Handler,
		},
		{
			MethodName: "Erase",
			Handler:    _ProjectService_Erase_Handler,
		},
		{
			MethodName: "List",
			Handler:    _ProjectService_List_Handler,
		},
		{
			MethodName: "Devcontainer",
			Handler:    _ProjectService_Devcontainer_Handler,
		},
		{
			MethodName: "Docker",
			Handler:    _ProjectService_Docker_Handler,
		},
		{
			MethodName: "FileMappings",
			Handler:    _ProjectService_FileMappings_Handler,
		},
		{
			MethodName: "Up",
			Handler:    _ProjectService_Up_Handler,
		},
		{
			MethodName: "Down",
			Handler:    _ProjectService_Down_Handler,
		},
		{
			MethodName: "Recreate",
			Handler:    _ProjectService_Recreate_Handler,
		},
		{
			MethodName: "InspectForeign",
			Handler:    _ProjectService_InspectForeign_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _ProjectService_Watch_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Terminal",
			Handler:       _ProjectService_Terminal_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SessionLogin",
			Handler:       _ProjectService_SessionLogin_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Paths",
			Handler:       _ProjectService_Paths_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cxz/project_svc.g.proto",
}
