// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cxz/session.proto

package resource

import (
	_ "github.com/lesomnus/payday/pdpb"
	_ "github.com/protobuf-orm/protobuf-orm/ormpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The durable conversation identity. Runtime/run IDs and journal cursors are
// operational state, not caller-patchable columns.
type Session struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Alias       string                 `protobuf:"bytes,4,opt,name=alias"`
	xxx_hidden_Name        string                 `protobuf:"bytes,5,opt,name=name"`
	xxx_hidden_Desc        string                 `protobuf:"bytes,6,opt,name=desc"`
	xxx_hidden_Project     *Project               `protobuf:"bytes,8,opt,name=project"`
	xxx_hidden_Agent       string                 `protobuf:"bytes,9,opt,name=agent"`
	xxx_hidden_Model       string                 `protobuf:"bytes,10,opt,name=model"`
	xxx_hidden_RuntimeId   string                 `protobuf:"bytes,11,opt,name=runtime_id,json=runtimeId"`
	xxx_hidden_ClientId    string                 `protobuf:"bytes,12,opt,name=client_id,json=clientId"`
	xxx_hidden_DateUpdated *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=date_updated,json=dateUpdated"`
	xxx_hidden_DateErased  *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=date_erased,json=dateErased"`
	xxx_hidden_DateCreated *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=date_created,json=dateCreated"`
	xxx_hidden_Status      *SessionStatus         `protobuf:"bytes,16,opt,name=status"`
	xxx_hidden_Listed      bool                   `protobuf:"varint,17,opt,name=listed"`
	xxx_hidden_Account     *Account               `protobuf:"bytes,18,opt,name=account"`
	xxx_hidden_AuthBinding *AuthBinding           `protobuf:"bytes,19,opt,name=auth_binding,json=authBinding"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_cxz_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_cxz_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Session) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *Session) GetAlias() string {
	if x != nil {
		return x.xxx_hidden_Alias
	}
	return ""
}

func (x *Session) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *Session) GetDesc() string {
	if x != nil {
		return x.xxx_hidden_Desc
	}
	return ""
}

func (x *Session) GetProject() *Project {
	if x != nil {
		return x.xxx_hidden_Project
	}
	return nil
}

func (x *Session) GetAgent() string {
	if x != nil {
		return x.xxx_hidden_Agent
	}
	return ""
}

func (x *Session) GetModel() string {
	if x != nil {
		return x.xxx_hidden_Model
	}
	return ""
}

func (x *Session) GetRuntimeId() string {
	if x != nil {
		return x.xxx_hidden_RuntimeId
	}
	return ""
}

func (x *Session) GetClientId() string {
	if x != nil {
		return x.xxx_hidden_ClientId
	}
	return ""
}

func (x *Session) GetDateUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateUpdated
	}
	return nil
}

func (x *Session) GetDateErased() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateErased
	}
	return nil
}

func (x *Session) GetDateCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return nil
}

func (x *Session) GetStatus() *SessionStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *Session) GetListed() bool {
	if x != nil {
		return x.xxx_hidden_Listed
	}
	return false
}

func (x *Session) GetAccount() *Account {
	if x != nil {
		return x.xxx_hidden_Account
	}
	return nil
}

func (x *Session) GetAuthBinding() *AuthBinding {
	if x != nil {
		return x.xxx_hidden_AuthBinding
	}
	return nil
}

func (x *Session) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
}

func (x *Session) SetAlias(v string) {
	x.xxx_hidden_Alias = v
}

func (x *Session) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *Session) SetDesc(v string) {
	x.xxx_hidden_Desc = v
}

func (x *Session) SetProject(v *Project) {
	x.xxx_hidden_Project = v
}

func (x *Session) SetAgent(v string) {
	x.xxx_hidden_Agent = v
}

func (x *Session) SetModel(v string) {
	x.xxx_hidden_Model = v
}

func (x *Session) SetRuntimeId(v string) {
	x.xxx_hidden_RuntimeId = v
}

func (x *Session) SetClientId(v string) {
	x.xxx_hidden_ClientId = v
}

func (x *Session) SetDateUpdated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateUpdated = v
}

func (x *Session) SetDateErased(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateErased = v
}

func (x *Session) SetDateCreated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateCreated = v
}

func (x *Session) SetStatus(v *SessionStatus) {
	x.xxx_hidden_Status = v
}

func (x *Session) SetListed(v bool) {
	x.xxx_hidden_Listed = v
}

func (x *Session) SetAccount(v *Account) {
	x.xxx_hidden_Account = v
}

func (x *Session) SetAuthBinding(v *AuthBinding) {
	x.xxx_hidden_AuthBinding = v
}

func (x *Session) HasProject() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Project != nil
}

func (x *Session) HasDateUpdated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateUpdated != nil
}

func (x *Session) HasDateErased() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateErased != nil
}

func (x *Session) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateCreated != nil
}

func (x *Session) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *Session) HasAccount() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Account != nil
}

func (x *Session) HasAuthBinding() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_AuthBinding != nil
}

func (x *Session) ClearProject() {
	x.xxx_hidden_Project = nil
}

func (x *Session) ClearDateUpdated() {
	x.xxx_hidden_DateUpdated = nil
}

func (x *Session) ClearDateErased() {
	x.xxx_hidden_DateErased = nil
}

func (x *Session) ClearDateCreated() {
	x.xxx_hidden_DateCreated = nil
}

func (x *Session) ClearStatus() {
	x.xxx_hidden_Status = nil
}

func (x *Session) ClearAccount() {
	x.xxx_hidden_Account = nil
}

func (x *Session) ClearAuthBinding() {
	x.xxx_hidden_AuthBinding = nil
}

type Session_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id []byte
	// Nullable only for upgrading older databases; lifecycle assigns every session.
	Alias       string
	Name        string
	Desc        string
	Project     *Project
	Agent       string
	Model       string
	RuntimeId   string
	ClientId    string
	DateUpdated *timestamppb.Timestamp
	DateErased  *timestamppb.Timestamp
	DateCreated *timestamppb.Timestamp
	Status      *SessionStatus
	Listed      bool
	Account     *Account
	AuthBinding *AuthBinding
}

func (b0 Session_builder) Build() *Session {
	m0 := &Session{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Alias = b.Alias
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Desc = b.Desc
	x.xxx_hidden_Project = b.Project
	x.xxx_hidden_Agent = b.Agent
	x.xxx_hidden_Model = b.Model
	x.xxx_hidden_RuntimeId = b.RuntimeId
	x.xxx_hidden_ClientId = b.ClientId
	x.xxx_hidden_DateUpdated = b.DateUpdated
	x.xxx_hidden_DateErased = b.DateErased
	x.xxx_hidden_DateCreated = b.DateCreated
	x.xxx_hidden_Status = b.Status
	x.xxx_hidden_Listed = b.Listed
	x.xxx_hidden_Account = b.Account
	x.xxx_hidden_AuthBinding = b.AuthBinding
	return m0
}

type SessionStatus struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_State          string                 `protobuf:"bytes,1,opt,name=state"`
	xxx_hidden_RunId          string                 `protobuf:"bytes,2,opt,name=run_id,json=runId"`
	xxx_hidden_VendorId       string                 `protobuf:"bytes,3,opt,name=vendor_id,json=vendorId"`
	xxx_hidden_LastSeq        uint64                 `protobuf:"varint,4,opt,name=last_seq,json=lastSeq"`
	xxx_hidden_Pending        *[]*SessionEvent       `protobuf:"bytes,5,rep,name=pending"`
	xxx_hidden_PermissionMode string                 `protobuf:"bytes,6,opt,name=permission_mode,json=permissionMode"`
	xxx_hidden_Queued         string                 `protobuf:"bytes,7,opt,name=queued"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *SessionStatus) Reset() {
	*x = SessionStatus{}
	mi := &file_cxz_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStatus) ProtoMessage() {}

func (x *SessionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_cxz_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SessionStatus) GetState() string {
	if x != nil {
		return x.xxx_hidden_State
	}
	return ""
}

func (x *SessionStatus) GetRunId() string {
	if x != nil {
		return x.xxx_hidden_RunId
	}
	return ""
}

func (x *SessionStatus) GetVendorId() string {
	if x != nil {
		return x.xxx_hidden_VendorId
	}
	return ""
}

func (x *SessionStatus) GetLastSeq() uint64 {
	if x != nil {
		return x.xxx_hidden_LastSeq
	}
	return 0
}

func (x *SessionStatus) GetPending() []*SessionEvent {
	if x != nil {
		if x.xxx_hidden_Pending != nil {
			return *x.xxx_hidden_Pending
		}
	}
	return nil
}

func (x *SessionStatus) GetPermissionMode() string {
	if x != nil {
		return x.xxx_hidden_PermissionMode
	}
	return ""
}

func (x *SessionStatus) GetQueued() string {
	if x != nil {
		return x.xxx_hidden_Queued
	}
	return ""
}

func (x *SessionStatus) SetState(v string) {
	x.xxx_hidden_State = v
}

func (x *SessionStatus) SetRunId(v string) {
	x.xxx_hidden_RunId = v
}

func (x *SessionStatus) SetVendorId(v string) {
	x.xxx_hidden_VendorId = v
}

func (x *SessionStatus) SetLastSeq(v uint64) {
	x.xxx_hidden_LastSeq = v
}

func (x *SessionStatus) SetPending(v []*SessionEvent) {
	x.xxx_hidden_Pending = &v
}

func (x *SessionStatus) SetPermissionMode(v string) {
	x.xxx_hidden_PermissionMode = v
}

func (x *SessionStatus) SetQueued(v string) {
	x.xxx_hidden_Queued = v
}

type SessionStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	State          string
	RunId          string
	VendorId       string
	LastSeq        uint64
	Pending        []*SessionEvent
	PermissionMode string
	Queued         string
}

func (b0 SessionStatus_builder) Build() *SessionStatus {
	m0 := &SessionStatus{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_State = b.State
	x.xxx_hidden_RunId = b.RunId
	x.xxx_hidden_VendorId = b.VendorId
	x.xxx_hidden_LastSeq = b.LastSeq
	x.xxx_hidden_Pending = &b.Pending
	x.xxx_hidden_PermissionMode = b.PermissionMode
	x.xxx_hidden_Queued = b.Queued
	return m0
}

type SessionEvent struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RunId       string                 `protobuf:"bytes,1,opt,name=run_id,json=runId"`
	xxx_hidden_Seq         uint64                 `protobuf:"varint,2,opt,name=seq"`
	xxx_hidden_TimeMs      int64                  `protobuf:"varint,3,opt,name=time_ms,json=timeMs"`
	xxx_hidden_Kind        string                 `protobuf:"bytes,4,opt,name=kind"`
	xxx_hidden_Text        string                 `protobuf:"bytes,5,opt,name=text"`
	xxx_hidden_RequestId   string                 `protobuf:"bytes,6,opt,name=request_id,json=requestId"`
	xxx_hidden_Payload     []byte                 `protobuf:"bytes,7,opt,name=payload"`
	xxx_hidden_Response    *ResponseMetadata      `protobuf:"bytes,8,opt,name=response"`
	xxx_hidden_ToolSummary *ToolSummary           `protobuf:"bytes,9,opt,name=tool_summary,json=toolSummary"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SessionEvent) Reset() {
	*x = SessionEvent{}
	mi := &file_cxz_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionEvent) ProtoMessage() {}

func (x *SessionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_cxz_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SessionEvent) GetRunId() string {
	if x != nil {
		return x.xxx_hidden_RunId
	}
	return ""
}

func (x *SessionEvent) GetSeq() uint64 {
	if x != nil {
		return x.xxx_hidden_Seq
	}
	return 0
}

func (x *SessionEvent) GetTimeMs() int64 {
	if x != nil {
		return x.xxx_hidden_TimeMs
	}
	return 0
}

func (x *SessionEvent) GetKind() string {
	if x != nil {
		return x.xxx_hidden_Kind
	}
	return ""
}

func (x *SessionEvent) GetText() string {
	if x != nil {
		return x.xxx_hidden_Text
	}
	return ""
}

func (x *SessionEvent) GetRequestId() string {
	if x != nil {
		return x.xxx_hidden_RequestId
	}
	return ""
}

func (x *SessionEvent) GetPayload() []byte {
	if x != nil {
		return x.xxx_hidden_Payload
	}
	return nil
}

func (x *SessionEvent) GetResponse() *ResponseMetadata {
	if x != nil {
		return x.xxx_hidden_Response
	}
	return nil
}

func (x *SessionEvent) GetToolSummary() *ToolSummary {
	if x != nil {
		return x.xxx_hidden_ToolSummary
	}
	return nil
}

func (x *SessionEvent) SetRunId(v string) {
	x.xxx_hidden_RunId = v
}

func (x *SessionEvent) SetSeq(v uint64) {
	x.xxx_hidden_Seq = v
}

func (x *SessionEvent) SetTimeMs(v int64) {
	x.xxx_hidden_TimeMs = v
}

func (x *SessionEvent) SetKind(v string) {
	x.xxx_hidden_Kind = v
}

func (x *SessionEvent) SetText(v string) {
	x.xxx_hidden_Text = v
}

func (x *SessionEvent) SetRequestId(v string) {
	x.xxx_hidden_RequestId = v
}

func (x *SessionEvent) SetPayload(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Payload = v
}

func (x *SessionEvent) SetResponse(v *ResponseMetadata) {
	x.xxx_hidden_Response = v
}

func (x *SessionEvent) SetToolSummary(v *ToolSummary) {
	x.xxx_hidden_ToolSummary = v
}

func (x *SessionEvent) HasResponse() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Response != nil
}

func (x *SessionEvent) HasToolSummary() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ToolSummary != nil
}

func (x *SessionEvent) ClearResponse() {
	x.xxx_hidden_Response = nil
}

func (x *SessionEvent) ClearToolSummary() {
	x.xxx_hidden_ToolSummary = nil
}

type SessionEvent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RunId     string
	Seq       uint64
	TimeMs    int64
	Kind      string
	Text      string
	RequestId string
	Payload   []byte
	Response  *ResponseMetadata
	// Present only on a derived transcript row, never in the native live journal.
	ToolSummary *ToolSummary
}

func (b0 SessionEvent_builder) Build() *SessionEvent {
	m0 := &SessionEvent{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_RunId = b.RunId
	x.xxx_hidden_Seq = b.Seq
	x.xxx_hidden_TimeMs = b.TimeMs
	x.xxx_hidden_Kind = b.Kind
	x.xxx_hidden_Text = b.Text
	x.xxx_hidden_RequestId = b.RequestId
	x.xxx_hidden_Payload = b.Payload
	x.xxx_hidden_Response = b.Response
	x.xxx_hidden_ToolSummary = b.ToolSummary
	return m0
}

type ToolSummary struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name         string                 `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Shell        string                 `protobuf:"bytes,2,opt,name=shell"`
	xxx_hidden_Command      string                 `protobuf:"bytes,3,opt,name=command"`
	xxx_hidden_State        string                 `protobuf:"bytes,4,opt,name=state"`
	xxx_hidden_Files        *[]*ToolFileSummary    `protobuf:"bytes,5,rep,name=files"`
	xxx_hidden_OmittedFiles uint32                 `protobuf:"varint,6,opt,name=omitted_files,json=omittedFiles"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ToolSummary) Reset() {
	*x = ToolSummary{}
	mi := &file_cxz_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolSummary) ProtoMessage() {}

func (x *ToolSummary) ProtoReflect() protoreflect.Message {
	mi := &file_cxz_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ToolSummary) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *ToolSummary) GetShell() string {
	if x != nil {
		return x.xxx_hidden_Shell
	}
	return ""
}

func (x *ToolSummary) GetCommand() string {
	if x != nil {
		return x.xxx_hidden_Command
	}
	return ""
}

func (x *ToolSummary) GetState() string {
	if x != nil {
		return x.xxx_hidden_State
	}
	return ""
}

func (x *ToolSummary) GetFiles() []*ToolFileSummary {
	if x != nil {
		if x.xxx_hidden_Files != nil {
			return *x.xxx_hidden_Files
		}
	}
	return nil
}

func (x *ToolSummary) GetOmittedFiles() uint32 {
	if x != nil {
		return x.xxx_hidden_OmittedFiles
	}
	return 0
}

func (x *ToolSummary) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *ToolSummary) SetShell(v string) {
	x.xxx_hidden_Shell = v
}

func (x *ToolSummary) SetCommand(v string) {
	x.xxx_hidden_Command = v
}

func (x *ToolSummary) SetState(v string) {
	x.xxx_hidden_State = v
}

func (x *ToolSummary) SetFiles(v []*ToolFileSummary) {
	x.xxx_hidden_Files = &v
}

func (x *ToolSummary) SetOmittedFiles(v uint32) {
	x.xxx_hidden_OmittedFiles = v
}

type ToolSummary_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name         string
	Shell        string
	Command      string
	State        string
	Files        []*ToolFileSummary
	OmittedFiles uint32
}

func (b0 ToolSummary_builder) Build() *ToolSummary {
	m0 := &ToolSummary{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Shell = b.Shell
	x.xxx_hidden_Command = b.Command
	x.xxx_hidden_State = b.State
	x.xxx_hidden_Files = &b.Files
	x.xxx_hidden_OmittedFiles = b.OmittedFiles
	return m0
}

// Counts describe recorded diff hunks or submitted content/replacement spans.
// An unknown measure never implies zero changes.
type ToolFileSummary struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Path     string                 `protobuf:"bytes,1,opt,name=path"`
	xxx_hidden_MovePath string                 `protobuf:"bytes,2,opt,name=move_path,json=movePath"`
	xxx_hidden_Action   string                 `protobuf:"bytes,3,opt,name=action"`
	xxx_hidden_Added    uint32                 `protobuf:"varint,4,opt,name=added"`
	xxx_hidden_Removed  uint32                 `protobuf:"varint,5,opt,name=removed"`
	xxx_hidden_Lines    uint32                 `protobuf:"varint,6,opt,name=lines"`
	xxx_hidden_Measure  string                 `protobuf:"bytes,7,opt,name=measure"`
	xxx_hidden_PerMatch bool                   `protobuf:"varint,8,opt,name=per_match,json=perMatch"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ToolFileSummary) Reset() {
	*x = ToolFileSummary{}
	mi := &file_cxz_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolFileSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolFileSummary) ProtoMessage() {}

func (x *ToolFileSummary) ProtoReflect() protoreflect.Message {
	mi := &file_cxz_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ToolFileSummary) GetPath() string {
	if x != nil {
		return x.xxx_hidden_Path
	}
	return ""
}

func (x *ToolFileSummary) GetMovePath() string {
	if x != nil {
		return x.xxx_hidden_MovePath
	}
	return ""
}

func (x *ToolFileSummary) GetAction() string {
	if x != nil {
		return x.xxx_hidden_Action
	}
	return ""
}

func (x *ToolFileSummary) GetAdded() uint32 {
	if x != nil {
		return x.xxx_hidden_Added
	}
	return 0
}

func (x *ToolFileSummary) GetRemoved() uint32 {
	if x != nil {
		return x.xxx_hidden_Removed
	}
	return 0
}

func (x *ToolFileSummary) GetLines() uint32 {
	if x != nil {
		return x.xxx_hidden_Lines
	}
	return 0
}

func (x *ToolFileSummary) GetMeasure() string {
	if x != nil {
		return x.xxx_hidden_Measure
	}
	return ""
}

func (x *ToolFileSummary) GetPerMatch() bool {
	if x != nil {
		return x.xxx_hidden_PerMatch
	}
	return false
}

func (x *ToolFileSummary) SetPath(v string) {
	x.xxx_hidden_Path = v
}

func (x *ToolFileSummary) SetMovePath(v string) {
	x.xxx_hidden_MovePath = v
}

func (x *ToolFileSummary) SetAction(v string) {
	x.xxx_hidden_Action = v
}

func (x *ToolFileSummary) SetAdded(v uint32) {
	x.xxx_hidden_Added = v
}

func (x *ToolFileSummary) SetRemoved(v uint32) {
	x.xxx_hidden_Removed = v
}

func (x *ToolFileSummary) SetLines(v uint32) {
	x.xxx_hidden_Lines = v
}

func (x *ToolFileSummary) SetMeasure(v string) {
	x.xxx_hidden_Measure = v
}

func (x *ToolFileSummary) SetPerMatch(v bool) {
	x.xxx_hidden_PerMatch = v
}

type ToolFileSummary_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Path     string
	MovePath string
	Action   string
	Added    uint32
	Removed  uint32
	Lines    uint32
	Measure  string
	PerMatch bool
}

func (b0 ToolFileSummary_builder) Build() *ToolFileSummary {
	m0 := &ToolFileSummary{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Path = b.Path
	x.xxx_hidden_MovePath = b.MovePath
	x.xxx_hidden_Action = b.Action
	x.xxx_hidden_Added = b.Added
	x.xxx_hidden_Removed = b.Removed
	x.xxx_hidden_Lines = b.Lines
	x.xxx_hidden_Measure = b.Measure
	x.xxx_hidden_PerMatch = b.PerMatch
	return m0
}

// Frozen response context; sources are response, settings or requested.
// Empty values mean the provider/configuration did not supply a known value.
type ResponseMetadata struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Model          string                 `protobuf:"bytes,1,opt,name=model"`
	xxx_hidden_Effort         string                 `protobuf:"bytes,2,opt,name=effort"`
	xxx_hidden_ModelSource    string                 `protobuf:"bytes,3,opt,name=model_source,json=modelSource"`
	xxx_hidden_EffortSource   string                 `protobuf:"bytes,4,opt,name=effort_source,json=effortSource"`
	xxx_hidden_TurnId         string                 `protobuf:"bytes,5,opt,name=turn_id,json=turnId"`
	xxx_hidden_Phase          string                 `protobuf:"bytes,6,opt,name=phase"`
	xxx_hidden_CompletionJson []byte                 `protobuf:"bytes,7,opt,name=completion_json,json=completionJson"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ResponseMetadata) Reset() {
	*x = ResponseMetadata{}
	mi := &file_cxz_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseMetadata) ProtoMessage() {}

func (x *ResponseMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_cxz_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ResponseMetadata) GetModel() string {
	if x != nil {
		return x.xxx_hidden_Model
	}
	return ""
}

func (x *ResponseMetadata) GetEffort() string {
	if x != nil {
		return x.xxx_hidden_Effort
	}
	return ""
}

func (x *ResponseMetadata) GetModelSource() string {
	if x != nil {
		return x.xxx_hidden_ModelSource
	}
	return ""
}

func (x *ResponseMetadata) GetEffortSource() string {
	if x != nil {
		return x.xxx_hidden_EffortSource
	}
	return ""
}

func (x *ResponseMetadata) GetTurnId() string {
	if x != nil {
		return x.xxx_hidden_TurnId
	}
	return ""
}

func (x *ResponseMetadata) GetPhase() string {
	if x != nil {
		return x.xxx_hidden_Phase
	}
	return ""
}

func (x *ResponseMetadata) GetCompletionJson() []byte {
	if x != nil {
		return x.xxx_hidden_CompletionJson
	}
	return nil
}

func (x *ResponseMetadata) SetModel(v string) {
	x.xxx_hidden_Model = v
}

func (x *ResponseMetadata) SetEffort(v string) {
	x.xxx_hidden_Effort = v
}

func (x *ResponseMetadata) SetModelSource(v string) {
	x.xxx_hidden_ModelSource = v
}

func (x *ResponseMetadata) SetEffortSource(v string) {
	x.xxx_hidden_EffortSource = v
}

func (x *ResponseMetadata) SetTurnId(v string) {
	x.xxx_hidden_TurnId = v
}

func (x *ResponseMetadata) SetPhase(v string) {
	x.xxx_hidden_Phase = v
}

func (x *ResponseMetadata) SetCompletionJson(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_CompletionJson = v
}

type ResponseMetadata_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Model        string
	Effort       string
	ModelSource  string
	EffortSource string
	TurnId       string
	Phase        string
	// Immutable successful-turn summary referencing the final assistant seq.
	CompletionJson []byte
}

func (b0 ResponseMetadata_builder) Build() *ResponseMetadata {
	m0 := &ResponseMetadata{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Model = b.Model
	x.xxx_hidden_Effort = b.Effort
	x.xxx_hidden_ModelSource = b.ModelSource
	x.xxx_hidden_EffortSource = b.EffortSource
	x.xxx_hidden_TurnId = b.TurnId
	x.xxx_hidden_Phase = b.Phase
	x.xxx_hidden_CompletionJson = b.CompletionJson
	return m0
}

var File_cxz_session_proto protoreflect.FileDescriptor

const file_cxz_session_proto_rawDesc = "" +
	"\n" +
	"\x11cxz/session.proto\x12\x03cxz\x1a\x11cxz/project.proto\x1a\x11cxz/account.proto\x1a\x16cxz/auth_binding.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\torm.proto\x1a\fpayday.proto\"\xb3\x06\n" +
	"\aSession\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\fB\v\xea\x82\x16\a\x10@(\x01\x82\x01\x00R\x02id\x12\x1e\n" +
	"\x05alias\x18\x04 \x01(\tB\b\xea\x82\x16\x040\x018\x01R\x05alias\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\x06 \x01(\tR\x04desc\x12.\n" +
	"\aproject\x18\b \x01(\v2\f.cxz.ProjectB\x06\xf2\x82\x16\x02@\x01R\aproject\x12\x1c\n" +
	"\x05agent\x18\t \x01(\tB\x06\xea\x82\x16\x02@\x01R\x05agent\x12\x1c\n" +
	"\x05model\x18\n" +
	" \x01(\tB\x06\xea\x82\x16\x02@\x01R\x05model\x12'\n" +
	"\n" +
	"runtime_id\x18\v \x01(\tB\b\xea\x82\x16\x040\x01@\x01R\truntimeId\x12%\n" +
	"\tclient_id\x18\f \x01(\tB\b\xea\x82\x16\x040\x01@\x01R\bclientId\x12F\n" +
	"\fdate_updated\x18\r \x01(\v2\x1a.google.protobuf.TimestampB\a\xea\x82\x16\x03\x8a\x01\x00R\vdateUpdated\x12D\n" +
	"\vdate_erased\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampB\a\xea\x82\x16\x03\x92\x01\x00R\n" +
	"dateErased\x12H\n" +
	"\fdate_created\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampB\t\xea\x82\x16\x05@\x01\x82\x01\x00R\vdateCreated\x12*\n" +
	"\x06status\x18\x10 \x01(\v2\x12.cxz.SessionStatusR\x06status\x12#\n" +
	"\x06listed\x18\x11 \x01(\bB\v\xea\x82\x16\a\x82\x01\x04trueR\x06listed\x12.\n" +
	"\aaccount\x18\x12 \x01(\v2\f.cxz.AccountB\x06\xf2\x82\x16\x02@\x01R\aaccount\x12;\n" +
	"\fauth_binding\x18\x13 \x01(\v2\x10.cxz.AuthBindingB\x06\xf2\x82\x16\x02@\x01R\vauthBinding:q\xca\xfc\x15&\x12\x02\x10\x01\x1a \x12\x04page\x1a\x10\n" +
	"\fdate_created\x10\x0f\x1a\x06\n" +
	"\x02id\x10\x01\x8a\xbb\x16C\b\b2;\n" +
	"\x10\n" +
	"\x0e\n" +
	"\fdate_created\n" +
	"\x06\n" +
	"\x04\n" +
	"\x02id\x1a\x05\n" +
	"\x03ref\x1a\t\n" +
	"\aproject\x1a\b\n" +
	"\x06listed 2(\xc8\x01:\x00*\x00\"\xe2\x01\n" +
	"\rSessionStatus\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x1b\n" +
	"\tvendor_id\x18\x03 \x01(\tR\bvendorId\x12\x19\n" +
	"\blast_seq\x18\x04 \x01(\x04R\alastSeq\x12+\n" +
	"\apending\x18\x05 \x03(\v2\x11.cxz.SessionEventR\apending\x12'\n" +
	"\x0fpermission_mode\x18\x06 \x01(\tR\x0epermissionMode\x12\x16\n" +
	"\x06queued\x18\a \x01(\tR\x06queued\"\x99\x02\n" +
	"\fSessionEvent\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x17\n" +
	"\atime_ms\x18\x03 \x01(\x03R\x06timeMs\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"request_id\x18\x06 \x01(\tR\trequestId\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\x121\n" +
	"\bresponse\x18\b \x01(\v2\x15.cxz.ResponseMetadataR\bresponse\x123\n" +
	"\ftool_summary\x18\t \x01(\v2\x10.cxz.ToolSummaryR\vtoolSummary\"\xb8\x01\n" +
	"\vToolSummary\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05shell\x18\x02 \x01(\tR\x05shell\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12*\n" +
	"\x05files\x18\x05 \x03(\v2\x14.cxz.ToolFileSummaryR\x05files\x12#\n" +
	"\romitted_files\x18\x06 \x01(\rR\fomittedFiles\"\xd7\x01\n" +
	"\x0fToolFileSummary\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1b\n" +
	"\tmove_path\x18\x02 \x01(\tR\bmovePath\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x14\n" +
	"\x05added\x18\x04 \x01(\rR\x05added\x12\x18\n" +
	"\aremoved\x18\x05 \x01(\rR\aremoved\x12\x14\n" +
	"\x05lines\x18\x06 \x01(\rR\x05lines\x12\x18\n" +
	"\ameasure\x18\a \x01(\tR\ameasure\x12\x1b\n" +
	"\tper_match\x18\b \x01(\bR\bperMatch\"\xe0\x01\n" +
	"\x10ResponseMetadata\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x16\n" +
	"\x06effort\x18\x02 \x01(\tR\x06effort\x12!\n" +
	"\fmodel_source\x18\x03 \x01(\tR\vmodelSource\x12#\n" +
	"\reffort_source\x18\x04 \x01(\tR\feffortSource\x12\x17\n" +
	"\aturn_id\x18\x05 \x01(\tR\x06turnId\x12\x14\n" +
	"\x05phase\x18\x06 \x01(\tR\x05phase\x12'\n" +
	"\x0fcompletion_json\x18\a \x01(\fR\x0ecompletionJsonB'Z github.com/lesomnus/cxz/resource\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var file_cxz_session_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_cxz_session_proto_goTypes = []any{
	(*Session)(nil),               // 0: cxz.Session
	(*SessionStatus)(nil),         // 1: cxz.SessionStatus
	(*SessionEvent)(nil),          // 2: cxz.SessionEvent
	(*ToolSummary)(nil),           // 3: cxz.ToolSummary
	(*ToolFileSummary)(nil),       // 4: cxz.ToolFileSummary
	(*ResponseMetadata)(nil),      // 5: cxz.ResponseMetadata
	(*Project)(nil),               // 6: cxz.Project
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*Account)(nil),               // 8: cxz.Account
	(*AuthBinding)(nil),           // 9: cxz.AuthBinding
}
var file_cxz_session_proto_depIdxs = []int32{
	6,  // 0: cxz.Session.project:type_name -> cxz.Project
	7,  // 1: cxz.Session.date_updated:type_name -> google.protobuf.Timestamp
	7,  // 2: cxz.Session.date_erased:type_name -> google.protobuf.Timestamp
	7,  // 3: cxz.Session.date_created:type_name -> google.protobuf.Timestamp
	1,  // 4: cxz.Session.status:type_name -> cxz.SessionStatus
	8,  // 5: cxz.Session.account:type_name -> cxz.Account
	9,  // 6: cxz.Session.auth_binding:type_name -> cxz.AuthBinding
	2,  // 7: cxz.SessionStatus.pending:type_name -> cxz.SessionEvent
	5,  // 8: cxz.SessionEvent.response:type_name -> cxz.ResponseMetadata
	3,  // 9: cxz.SessionEvent.tool_summary:type_name -> cxz.ToolSummary
	4,  // 10: cxz.ToolSummary.files:type_name -> cxz.ToolFileSummary
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_cxz_session_proto_init() }
func file_cxz_session_proto_init() {
	if File_cxz_session_proto != nil {
		return
	}
	file_cxz_project_proto_init()
	file_cxz_account_proto_init()
	file_cxz_auth_binding_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cxz_session_proto_rawDesc), len(file_cxz_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cxz_session_proto_goTypes,
		DependencyIndexes: file_cxz_session_proto_depIdxs,
		MessageInfos:      file_cxz_session_proto_msgTypes,
	}.Build()
	File_cxz_session_proto = out.File
	file_cxz_session_proto_goTypes = nil
	file_cxz_session_proto_depIdxs = nil
}
