// Code generated by protoc-gen-orm-go. DO NOT EDIT.

package resource

import (
	bytes "bytes"
)

func (x *SessionRef) Pick() *SessionGetRequest {
	return SessionGetRequest_builder{Ref: x}.Build()
}

func (x *Session) Ref() *SessionRef {
	if v := x.GetId(); len(v) > 0 {
		return SessionById(v)
	}
	if v := x.GetRuntimeId(); len(v) > 0 {
		return SessionByRuntimeId(v)
	}
	if v := x.GetClientId(); len(v) > 0 {
		return SessionByClientId(v)
	}

	return nil
}

func (x *Session) Pick() *SessionGetRequest {
	return x.Ref().Pick()
}

func (x *SessionRef) Picks(v *Session) bool {
	switch x.WhichKey() {
	case SessionRef_Id_case:
		return bytes.Equal(x.GetId(), v.GetId())
	case SessionRef_RuntimeId_case:
		return x.GetRuntimeId() == v.GetRuntimeId()
	case SessionRef_ClientId_case:
		return x.GetClientId() == v.GetClientId()
	default:
		return false
	}
}

func (x *SessionGetRequest) WithSelect(f func(s *SessionSelect)) *SessionGetRequest {
	if !x.HasSelect() {
		x.SetSelect(&SessionSelect{})
	}
	f(x.GetSelect())
	return x
}

func SessionById(v []byte) *SessionRef {
	x := &SessionRef{}
	x.SetId(v)
	return x
}

func SessionByRuntimeId(v string) *SessionRef {
	x := &SessionRef{}
	x.SetRuntimeId(v)
	return x
}

func SessionByClientId(v string) *SessionRef {
	x := &SessionRef{}
	x.SetClientId(v)
	return x
}

func SessionGetById(v []byte) *SessionGetRequest {
	return SessionGetRequest_builder{Ref: SessionById(v)}.Build()
}

func SessionGetByRuntimeId(v string) *SessionGetRequest {
	return SessionGetRequest_builder{Ref: SessionByRuntimeId(v)}.Build()
}

func SessionGetByClientId(v string) *SessionGetRequest {
	return SessionGetRequest_builder{Ref: SessionByClientId(v)}.Build()
}
