// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cxz.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_cxz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_cxz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_cxz_proto_rawDescGZIP(), []int{0}
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     string                 `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ClientId      string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_cxz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cxz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_cxz_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *CreateRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type SessionRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionRef) Reset() {
	*x = SessionRef{}
	mi := &file_cxz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRef) ProtoMessage() {}

func (x *SessionRef) ProtoReflect() protoreflect.Message {
	mi := &file_cxz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRef.ProtoReflect.Descriptor instead.
func (*SessionRef) Descriptor() ([]byte, []int) {
	return file_cxz_proto_rawDescGZIP(), []int{2}
}

func (x *SessionRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Workspace     string                 `protobuf:"bytes,2,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	RunId         string                 `protobuf:"bytes,5,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	VendorId      string                 `protobuf:"bytes,6,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastSeq       uint64                 `protobuf:"varint,8,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"`
	Pending       []*Event               `protobuf:"bytes,9,rep,name=pending,proto3" json:"pending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_cxz_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_cxz_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_cxz_proto_rawDescGZIP(), []int{3}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *Session) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Session) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Session) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Session) GetVendorId() string {
	if x != nil {
		return x.VendorId
	}
	return ""
}

func (x *Session) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Session) GetLastSeq() uint64 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

func (x *Session) GetPending() []*Event {
	if x != nil {
		return x.Pending
	}
	return nil
}

type SessionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionList) Reset() {
	*x = SessionList{}
	mi := &file_cxz_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionList) ProtoMessage() {}

func (x *SessionList) ProtoReflect() protoreflect.Message {
	mi := &file_cxz_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionList.ProtoReflect.Descriptor instead.
func (*SessionList) Descriptor() ([]byte, []int) {
	return file_cxz_proto_rawDescGZIP(), []int{4}
}

func (x *SessionList) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type Input struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Input) Reset() {
	*x = Input{}
	mi := &file_cxz_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Input) ProtoMessage() {}

func (x *Input) ProtoReflect() protoreflect.Message {
	mi := &file_cxz_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Input.ProtoReflect.Descriptor instead.
func (*Input) Descriptor() ([]byte, []int) {
	return file_cxz_proto_rawDescGZIP(), []int{5}
}

func (x *Input) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Input) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Input) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Input) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Answer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Allow         bool                   `protobuf:"varint,5,opt,name=allow,proto3" json:"allow,omitempty"`
	AnswersJson   string                 `protobuf:"bytes,6,opt,name=answers_json,json=answersJson,proto3" json:"answers_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer) Reset() {
	*x = Answer{}
	mi := &file_cxz_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer) ProtoMessage() {}

func (x *Answer) ProtoReflect() protoreflect.Message {
	mi := &file_cxz_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer.ProtoReflect.Descriptor instead.
func (*Answer) Descriptor() ([]byte, []int) {
	return file_cxz_proto_rawDescGZIP(), []int{6}
}

func (x *Answer) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Answer) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Answer) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Answer) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Answer) GetAllow() bool {
	if x != nil {
		return x.Allow
	}
	return false
}

func (x *Answer) GetAnswersJson() string {
	if x != nil {
		return x.AnswersJson
	}
	return ""
}

type Control struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Control) Reset() {
	*x = Control{}
	mi := &file_cxz_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Control) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Control) ProtoMessage() {}

func (x *Control) ProtoReflect() protoreflect.Message {
	mi := &file_cxz_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Control.ProtoReflect.Descriptor instead.
func (*Control) Descriptor() ([]byte, []int) {
	return file_cxz_proto_rawDescGZIP(), []int{7}
}

func (x *Control) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Control) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Control) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type Receipt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Receipt) Reset() {
	*x = Receipt{}
	mi := &file_cxz_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipt) ProtoMessage() {}

func (x *Receipt) ProtoReflect() protoreflect.Message {
	mi := &file_cxz_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipt.ProtoReflect.Descriptor instead.
func (*Receipt) Descriptor() ([]byte, []int) {
	return file_cxz_proto_rawDescGZIP(), []int{8}
}

func (x *Receipt) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Receipt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AfterSeq      uint64                 `protobuf:"varint,2,opt,name=after_seq,json=afterSeq,proto3" json:"after_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_cxz_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cxz_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_cxz_proto_rawDescGZIP(), []int{9}
}

func (x *WatchRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WatchRequest) GetAfterSeq() uint64 {
	if x != nil {
		return x.AfterSeq
	}
	return 0
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Seq           uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	TimeMs        int64                  `protobuf:"varint,4,opt,name=time_ms,json=timeMs,proto3" json:"time_ms,omitempty"`
	Kind          string                 `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`
	Text          string                 `protobuf:"bytes,6,opt,name=text,proto3" json:"text,omitempty"`
	RequestId     string                 `protobuf:"bytes,7,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,8,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_cxz_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_cxz_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_cxz_proto_rawDescGZIP(), []int{10}
}

func (x *Event) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Event) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Event) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Event) GetTimeMs() int64 {
	if x != nil {
		return x.TimeMs
	}
	return 0
}

func (x *Event) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Event) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Event) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Event) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_cxz_proto protoreflect.FileDescriptor

const file_cxz_proto_rawDesc = "" +
	"\n" +
	"\tcxz.proto\x12\x06cxz.v1\"\a\n" +
	"\x05Empty\"`\n" +
	"\rCreateRequest\x12\x1c\n" +
	"\tworkspace\x18\x01 \x01(\tR\tworkspace\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\"\x1c\n" +
	"\n" +
	"SessionRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xfa\x01\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tworkspace\x18\x02 \x01(\tR\tworkspace\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x15\n" +
	"\x06run_id\x18\x05 \x01(\tR\x05runId\x12\x1b\n" +
	"\tvendor_id\x18\x06 \x01(\tR\bvendorId\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x19\n" +
	"\blast_seq\x18\b \x01(\x04R\alastSeq\x12'\n" +
	"\apending\x18\t \x03(\v2\r.cxz.v1.EventR\apending\":\n" +
	"\vSessionList\x12+\n" +
	"\bsessions\x18\x01 \x03(\v2\x0f.cxz.v1.SessionR\bsessions\"n\n" +
	"\x05Input\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\"\xb3\x01\n" +
	"\x06Answer\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\x12\x14\n" +
	"\x05allow\x18\x05 \x01(\bR\x05allow\x12!\n" +
	"\fanswers_json\x18\x06 \x01(\tR\vanswersJson\"\\\n" +
	"\aControl\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\">\n" +
	"\aReceipt\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"J\n" +
	"\fWatchRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tafter_seq\x18\x02 \x01(\x04R\bafterSeq\"\xc9\x01\n" +
	"\x05Event\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\x12\x17\n" +
	"\atime_ms\x18\x04 \x01(\x03R\x06timeMs\x12\x12\n" +
	"\x04kind\x18\x05 \x01(\tR\x04kind\x12\x12\n" +
	"\x04text\x18\x06 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"request_id\x18\a \x01(\tR\trequestId\x12\x18\n" +
	"\apayload\x18\b \x01(\fR\apayload2\x9b\x03\n" +
	"\bSessions\x120\n" +
	"\x06Create\x12\x15.cxz.v1.CreateRequest\x1a\x0f.cxz.v1.Session\x12*\n" +
	"\x04List\x12\r.cxz.v1.Empty\x1a\x13.cxz.v1.SessionList\x12*\n" +
	"\x03Get\x12\x12.cxz.v1.SessionRef\x1a\x0f.cxz.v1.Session\x12&\n" +
	"\x04Send\x12\r.cxz.v1.Input\x1a\x0f.cxz.v1.Receipt\x12(\n" +
	"\x05Reply\x12\x0e.cxz.v1.Answer\x1a\x0f.cxz.v1.Receipt\x12-\n" +
	"\tInterrupt\x12\x0f.cxz.v1.Control\x1a\x0f.cxz.v1.Receipt\x12*\n" +
	"\x06Resume\x12\x0f.cxz.v1.Control\x1a\x0f.cxz.v1.Session\x12(\n" +
	"\x04Stop\x12\x0f.cxz.v1.Control\x1a\x0f.cxz.v1.Receipt\x12.\n" +
	"\x05Watch\x12\x14.cxz.v1.WatchRequest\x1a\r.cxz.v1.Event0\x01B!Z\x1fgithub.com/lesomnus/cxz/api;apib\x06proto3"

var (
	file_cxz_proto_rawDescOnce sync.Once
	file_cxz_proto_rawDescData []byte
)

func file_cxz_proto_rawDescGZIP() []byte {
	file_cxz_proto_rawDescOnce.Do(func() {
		file_cxz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cxz_proto_rawDesc), len(file_cxz_proto_rawDesc)))
	})
	return file_cxz_proto_rawDescData
}

var file_cxz_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_cxz_proto_goTypes = []any{
	(*Empty)(nil),         // 0: cxz.v1.Empty
	(*CreateRequest)(nil), // 1: cxz.v1.CreateRequest
	(*SessionRef)(nil),    // 2: cxz.v1.SessionRef
	(*Session)(nil),       // 3: cxz.v1.Session
	(*SessionList)(nil),   // 4: cxz.v1.SessionList
	(*Input)(nil),         // 5: cxz.v1.Input
	(*Answer)(nil),        // 6: cxz.v1.Answer
	(*Control)(nil),       // 7: cxz.v1.Control
	(*Receipt)(nil),       // 8: cxz.v1.Receipt
	(*WatchRequest)(nil),  // 9: cxz.v1.WatchRequest
	(*Event)(nil),         // 10: cxz.v1.Event
}
var file_cxz_proto_depIdxs = []int32{
	10, // 0: cxz.v1.Session.pending:type_name -> cxz.v1.Event
	3,  // 1: cxz.v1.SessionList.sessions:type_name -> cxz.v1.Session
	1,  // 2: cxz.v1.Sessions.Create:input_type -> cxz.v1.CreateRequest
	0,  // 3: cxz.v1.Sessions.List:input_type -> cxz.v1.Empty
	2,  // 4: cxz.v1.Sessions.Get:input_type -> cxz.v1.SessionRef
	5,  // 5: cxz.v1.Sessions.Send:input_type -> cxz.v1.Input
	6,  // 6: cxz.v1.Sessions.Reply:input_type -> cxz.v1.Answer
	7,  // 7: cxz.v1.Sessions.Interrupt:input_type -> cxz.v1.Control
	7,  // 8: cxz.v1.Sessions.Resume:input_type -> cxz.v1.Control
	7,  // 9: cxz.v1.Sessions.Stop:input_type -> cxz.v1.Control
	9,  // 10: cxz.v1.Sessions.Watch:input_type -> cxz.v1.WatchRequest
	3,  // 11: cxz.v1.Sessions.Create:output_type -> cxz.v1.Session
	4,  // 12: cxz.v1.Sessions.List:output_type -> cxz.v1.SessionList
	3,  // 13: cxz.v1.Sessions.Get:output_type -> cxz.v1.Session
	8,  // 14: cxz.v1.Sessions.Send:output_type -> cxz.v1.Receipt
	8,  // 15: cxz.v1.Sessions.Reply:output_type -> cxz.v1.Receipt
	8,  // 16: cxz.v1.Sessions.Interrupt:output_type -> cxz.v1.Receipt
	3,  // 17: cxz.v1.Sessions.Resume:output_type -> cxz.v1.Session
	8,  // 18: cxz.v1.Sessions.Stop:output_type -> cxz.v1.Receipt
	10, // 19: cxz.v1.Sessions.Watch:output_type -> cxz.v1.Event
	11, // [11:20] is the sub-list for method output_type
	2,  // [2:11] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_cxz_proto_init() }
func file_cxz_proto_init() {
	if File_cxz_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cxz_proto_rawDesc), len(file_cxz_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cxz_proto_goTypes,
		DependencyIndexes: file_cxz_proto_depIdxs,
		MessageInfos:      file_cxz_proto_msgTypes,
	}.Build()
	File_cxz_proto = out.File
	file_cxz_proto_goTypes = nil
	file_cxz_proto_depIdxs = nil
}
