// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: cxz.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Sessions_Devcontainer_FullMethodName          = "/cxz.runtime.Sessions/Devcontainer"
	Sessions_Docker_FullMethodName                = "/cxz.runtime.Sessions/Docker"
	Sessions_FileMappings_FullMethodName          = "/cxz.runtime.Sessions/FileMappings"
	Sessions_Create_FullMethodName                = "/cxz.runtime.Sessions/Create"
	Sessions_List_FullMethodName                  = "/cxz.runtime.Sessions/List"
	Sessions_Get_FullMethodName                   = "/cxz.runtime.Sessions/Get"
	Sessions_CopyMemory_FullMethodName            = "/cxz.runtime.Sessions/CopyMemory"
	Sessions_Memory_FullMethodName                = "/cxz.runtime.Sessions/Memory"
	Sessions_Logs_FullMethodName                  = "/cxz.runtime.Sessions/Logs"
	Sessions_Permission_FullMethodName            = "/cxz.runtime.Sessions/Permission"
	Sessions_Send_FullMethodName                  = "/cxz.runtime.Sessions/Send"
	Sessions_Attach_FullMethodName                = "/cxz.runtime.Sessions/Attach"
	Sessions_Activity_FullMethodName              = "/cxz.runtime.Sessions/Activity"
	Sessions_UpdateAgent_FullMethodName           = "/cxz.runtime.Sessions/UpdateAgent"
	Sessions_Reply_FullMethodName                 = "/cxz.runtime.Sessions/Reply"
	Sessions_Interrupt_FullMethodName             = "/cxz.runtime.Sessions/Interrupt"
	Sessions_Resume_FullMethodName                = "/cxz.runtime.Sessions/Resume"
	Sessions_Stop_FullMethodName                  = "/cxz.runtime.Sessions/Stop"
	Sessions_Watch_FullMethodName                 = "/cxz.runtime.Sessions/Watch"
	Sessions_History_FullMethodName               = "/cxz.runtime.Sessions/History"
	Sessions_Transcript_FullMethodName            = "/cxz.runtime.Sessions/Transcript"
	Sessions_EventDetails_FullMethodName          = "/cxz.runtime.Sessions/EventDetails"
	Sessions_Background_FullMethodName            = "/cxz.runtime.Sessions/Background"
	Sessions_Models_FullMethodName                = "/cxz.runtime.Sessions/Models"
	Sessions_Search_FullMethodName                = "/cxz.runtime.Sessions/Search"
	Sessions_Open_FullMethodName                  = "/cxz.runtime.Sessions/Open"
	Sessions_Projects_FullMethodName              = "/cxz.runtime.Sessions/Projects"
	Sessions_Down_FullMethodName                  = "/cxz.runtime.Sessions/Down"
	Sessions_AuxRun_FullMethodName                = "/cxz.runtime.Sessions/AuxRun"
	Sessions_AuxCancel_FullMethodName             = "/cxz.runtime.Sessions/AuxCancel"
	Sessions_AuxStatus_FullMethodName             = "/cxz.runtime.Sessions/AuxStatus"
	Sessions_AuxEvents_FullMethodName             = "/cxz.runtime.Sessions/AuxEvents"
	Sessions_AuxPrefer_FullMethodName             = "/cxz.runtime.Sessions/AuxPrefer"
	Sessions_AuxForget_FullMethodName             = "/cxz.runtime.Sessions/AuxForget"
	Sessions_AuxConfig_FullMethodName             = "/cxz.runtime.Sessions/AuxConfig"
	Sessions_AuxSetConfig_FullMethodName          = "/cxz.runtime.Sessions/AuxSetConfig"
	Sessions_AuxModels_FullMethodName             = "/cxz.runtime.Sessions/AuxModels"
	Sessions_AuxLoginInfo_FullMethodName          = "/cxz.runtime.Sessions/AuxLoginInfo"
	Sessions_PurgeSession_FullMethodName          = "/cxz.runtime.Sessions/PurgeSession"
	Sessions_GetHistoryPolicy_FullMethodName      = "/cxz.runtime.Sessions/GetHistoryPolicy"
	Sessions_SetHistoryPolicy_FullMethodName      = "/cxz.runtime.Sessions/SetHistoryPolicy"
	Sessions_GetHistoryFloor_FullMethodName       = "/cxz.runtime.Sessions/GetHistoryFloor"
	Sessions_MarkHistoryTrimmable_FullMethodName  = "/cxz.runtime.Sessions/MarkHistoryTrimmable"
	Sessions_PutSecretFile_FullMethodName         = "/cxz.runtime.Sessions/PutSecretFile"
	Sessions_DeleteSecretFile_FullMethodName      = "/cxz.runtime.Sessions/DeleteSecretFile"
	Sessions_GetSkills_FullMethodName             = "/cxz.runtime.Sessions/GetSkills"
	Sessions_AddSkill_FullMethodName              = "/cxz.runtime.Sessions/AddSkill"
	Sessions_RemoveSkill_FullMethodName           = "/cxz.runtime.Sessions/RemoveSkill"
	Sessions_SetSkillDefault_FullMethodName       = "/cxz.runtime.Sessions/SetSkillDefault"
	Sessions_SetProjectSkill_FullMethodName       = "/cxz.runtime.Sessions/SetProjectSkill"
	Sessions_ClearProjectSkill_FullMethodName     = "/cxz.runtime.Sessions/ClearProjectSkill"
	Sessions_SyncSkills_FullMethodName            = "/cxz.runtime.Sessions/SyncSkills"
	Sessions_RenderDevcontainer_FullMethodName    = "/cxz.runtime.Sessions/RenderDevcontainer"
	Sessions_GetMcpServers_FullMethodName         = "/cxz.runtime.Sessions/GetMcpServers"
	Sessions_PutMcpServer_FullMethodName          = "/cxz.runtime.Sessions/PutMcpServer"
	Sessions_RemoveMcpServer_FullMethodName       = "/cxz.runtime.Sessions/RemoveMcpServer"
	Sessions_SetMcpServerDefault_FullMethodName   = "/cxz.runtime.Sessions/SetMcpServerDefault"
	Sessions_SetProjectMcpServer_FullMethodName   = "/cxz.runtime.Sessions/SetProjectMcpServer"
	Sessions_ClearProjectMcpServer_FullMethodName = "/cxz.runtime.Sessions/ClearProjectMcpServer"
	Sessions_McpSessions_FullMethodName           = "/cxz.runtime.Sessions/McpSessions"
	Sessions_SyncMcpServers_FullMethodName        = "/cxz.runtime.Sessions/SyncMcpServers"
	Sessions_McpLogs_FullMethodName               = "/cxz.runtime.Sessions/McpLogs"
	Sessions_RestartMcp_FullMethodName            = "/cxz.runtime.Sessions/RestartMcp"
)

// SessionsClient is the client API for Sessions service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SessionsClient interface {
	Devcontainer(ctx context.Context, in *DevcontainerInput, opts ...grpc.CallOption) (*Receipt, error)
	Docker(ctx context.Context, in *DockerInput, opts ...grpc.CallOption) (*Receipt, error)
	FileMappings(ctx context.Context, in *FileMappingsInput, opts ...grpc.CallOption) (*Receipt, error)
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*Session, error)
	List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SessionList, error)
	Get(ctx context.Context, in *SessionRef, opts ...grpc.CallOption) (*Session, error)
	CopyMemory(ctx context.Context, in *CopyMemoryRequest, opts ...grpc.CallOption) (*Receipt, error)
	Memory(ctx context.Context, in *MemoryRequest, opts ...grpc.CallOption) (*MemoryReply, error)
	Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (*LogsReply, error)
	Permission(ctx context.Context, in *PermissionInput, opts ...grpc.CallOption) (*Receipt, error)
	Send(ctx context.Context, in *Input, opts ...grpc.CallOption) (*Receipt, error)
	Attach(ctx context.Context, in *AttachmentInput, opts ...grpc.CallOption) (*Attachment, error)
	Activity(ctx context.Context, in *ActivityInput, opts ...grpc.CallOption) (*Receipt, error)
	UpdateAgent(ctx context.Context, in *AgentUpdateInput, opts ...grpc.CallOption) (*AgentUpdateStatus, error)
	Reply(ctx context.Context, in *Answer, opts ...grpc.CallOption) (*Receipt, error)
	Interrupt(ctx context.Context, in *Control, opts ...grpc.CallOption) (*Receipt, error)
	Resume(ctx context.Context, in *Control, opts ...grpc.CallOption) (*Session, error)
	Stop(ctx context.Context, in *Control, opts ...grpc.CallOption) (*Receipt, error)
	Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	History(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (*EventBatch, error)
	Transcript(ctx context.Context, in *TranscriptRequest, opts ...grpc.CallOption) (*TranscriptReply, error)
	EventDetails(ctx context.Context, in *EventDetailsRequest, opts ...grpc.CallOption) (*EventBatch, error)
	Background(ctx context.Context, in *SessionRef, opts ...grpc.CallOption) (*BackgroundReply, error)
	Models(ctx context.Context, in *ModelsRequest, opts ...grpc.CallOption) (*ModelsReply, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SearchReply], error)
	Open(ctx context.Context, in *ProjectRequest, opts ...grpc.CallOption) (*Session, error)
	Projects(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProjectList, error)
	Down(ctx context.Context, in *ProjectRequest, opts ...grpc.CallOption) (*Receipt, error)
	AuxRun(ctx context.Context, in *AuxRunInput, opts ...grpc.CallOption) (*AuxState, error)
	AuxCancel(ctx context.Context, in *AuxCancelInput, opts ...grpc.CallOption) (*AuxState, error)
	AuxStatus(ctx context.Context, in *AuxStatusInput, opts ...grpc.CallOption) (*AuxState, error)
	AuxEvents(ctx context.Context, in *AuxStatusInput, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AuxState], error)
	AuxPrefer(ctx context.Context, in *AuxPreferInput, opts ...grpc.CallOption) (*AuxState, error)
	AuxForget(ctx context.Context, in *AuxForgetInput, opts ...grpc.CallOption) (*Receipt, error)
	AuxConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AuxConfigReply, error)
	AuxSetConfig(ctx context.Context, in *AuxSetConfigInput, opts ...grpc.CallOption) (*AuxConfigReply, error)
	AuxModels(ctx context.Context, in *AuxModelsInput, opts ...grpc.CallOption) (*AuxModelsReply, error)
	AuxLoginInfo(ctx context.Context, in *AuxLoginInfoInput, opts ...grpc.CallOption) (*AuxLoginInfoReply, error)
	PurgeSession(ctx context.Context, in *SessionPurgeInput, opts ...grpc.CallOption) (*SessionPurgeReply, error)
	GetHistoryPolicy(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HistoryPolicy, error)
	SetHistoryPolicy(ctx context.Context, in *HistoryPolicy, opts ...grpc.CallOption) (*HistoryPolicy, error)
	GetHistoryFloor(ctx context.Context, in *SessionRef, opts ...grpc.CallOption) (*HistoryFloorReply, error)
	MarkHistoryTrimmable(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	PutSecretFile(ctx context.Context, in *PutSecretFileInput, opts ...grpc.CallOption) (*SecretFileReply, error)
	DeleteSecretFile(ctx context.Context, in *DeleteSecretFileInput, opts ...grpc.CallOption) (*SecretFileReply, error)
	GetSkills(ctx context.Context, in *SkillsInput, opts ...grpc.CallOption) (*SkillsReply, error)
	AddSkill(ctx context.Context, in *SkillInput, opts ...grpc.CallOption) (*SkillsReply, error)
	RemoveSkill(ctx context.Context, in *SkillInput, opts ...grpc.CallOption) (*SkillsReply, error)
	SetSkillDefault(ctx context.Context, in *SkillDefaultInput, opts ...grpc.CallOption) (*SkillsReply, error)
	SetProjectSkill(ctx context.Context, in *ProjectSkillInput, opts ...grpc.CallOption) (*SkillsReply, error)
	ClearProjectSkill(ctx context.Context, in *ClearProjectSkillInput, opts ...grpc.CallOption) (*SkillsReply, error)
	SyncSkills(ctx context.Context, in *SyncSkillsInput, opts ...grpc.CallOption) (*Receipt, error)
	RenderDevcontainer(ctx context.Context, in *RenderDevcontainerInput, opts ...grpc.CallOption) (*RenderDevcontainerReply, error)
	GetMcpServers(ctx context.Context, in *McpServersInput, opts ...grpc.CallOption) (*McpServersReply, error)
	PutMcpServer(ctx context.Context, in *PutMcpServerInput, opts ...grpc.CallOption) (*McpServersReply, error)
	RemoveMcpServer(ctx context.Context, in *McpServerInput, opts ...grpc.CallOption) (*McpServersReply, error)
	SetMcpServerDefault(ctx context.Context, in *McpServerDefaultInput, opts ...grpc.CallOption) (*McpServersReply, error)
	SetProjectMcpServer(ctx context.Context, in *ProjectMcpServerInput, opts ...grpc.CallOption) (*McpServersReply, error)
	ClearProjectMcpServer(ctx context.Context, in *ClearProjectMcpServerInput, opts ...grpc.CallOption) (*McpServersReply, error)
	McpSessions(ctx context.Context, in *McpSessionsInput, opts ...grpc.CallOption) (*McpSessionsReply, error)
	SyncMcpServers(ctx context.Context, in *SyncMcpServersInput, opts ...grpc.CallOption) (*Receipt, error)
	McpLogs(ctx context.Context, in *McpLogsInput, opts ...grpc.CallOption) (*McpLogsReply, error)
	RestartMcp(ctx context.Context, in *RestartMcpInput, opts ...grpc.CallOption) (*Receipt, error)
}

type sessionsClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionsClient(cc grpc.ClientConnInterface) SessionsClient {
	return &sessionsClient{cc}
}

func (c *sessionsClient) Devcontainer(ctx context.Context, in *DevcontainerInput, opts ...grpc.CallOption) (*Receipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Receipt)
	err := c.cc.Invoke(ctx, Sessions_Devcontainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) Docker(ctx context.Context, in *DockerInput, opts ...grpc.CallOption) (*Receipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Receipt)
	err := c.cc.Invoke(ctx, Sessions_Docker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) FileMappings(ctx context.Context, in *FileMappingsInput, opts ...grpc.CallOption) (*Receipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Receipt)
	err := c.cc.Invoke(ctx, Sessions_FileMappings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, Sessions_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SessionList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionList)
	err := c.cc.Invoke(ctx, Sessions_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) Get(ctx context.Context, in *SessionRef, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, Sessions_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) CopyMemory(ctx context.Context, in *CopyMemoryRequest, opts ...grpc.CallOption) (*Receipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Receipt)
	err := c.cc.Invoke(ctx, Sessions_CopyMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) Memory(ctx context.Context, in *MemoryRequest, opts ...grpc.CallOption) (*MemoryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemoryReply)
	err := c.cc.Invoke(ctx, Sessions_Memory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (*LogsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogsReply)
	err := c.cc.Invoke(ctx, Sessions_Logs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) Permission(ctx context.Context, in *PermissionInput, opts ...grpc.CallOption) (*Receipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Receipt)
	err := c.cc.Invoke(ctx, Sessions_Permission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) Send(ctx context.Context, in *Input, opts ...grpc.CallOption) (*Receipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Receipt)
	err := c.cc.Invoke(ctx, Sessions_Send_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) Attach(ctx context.Context, in *AttachmentInput, opts ...grpc.CallOption) (*Attachment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Attachment)
	err := c.cc.Invoke(ctx, Sessions_Attach_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) Activity(ctx context.Context, in *ActivityInput, opts ...grpc.CallOption) (*Receipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Receipt)
	err := c.cc.Invoke(ctx, Sessions_Activity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) UpdateAgent(ctx context.Context, in *AgentUpdateInput, opts ...grpc.CallOption) (*AgentUpdateStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentUpdateStatus)
	err := c.cc.Invoke(ctx, Sessions_UpdateAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) Reply(ctx context.Context, in *Answer, opts ...grpc.CallOption) (*Receipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Receipt)
	err := c.cc.Invoke(ctx, Sessions_Reply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) Interrupt(ctx context.Context, in *Control, opts ...grpc.CallOption) (*Receipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Receipt)
	err := c.cc.Invoke(ctx, Sessions_Interrupt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) Resume(ctx context.Context, in *Control, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, Sessions_Resume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) Stop(ctx context.Context, in *Control, opts ...grpc.CallOption) (*Receipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Receipt)
	err := c.cc.Invoke(ctx, Sessions_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Sessions_ServiceDesc.Streams[0], Sessions_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sessions_WatchClient = grpc.ServerStreamingClient[Event]

func (c *sessionsClient) History(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (*EventBatch, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventBatch)
	err := c.cc.Invoke(ctx, Sessions_History_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) Transcript(ctx context.Context, in *TranscriptRequest, opts ...grpc.CallOption) (*TranscriptReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TranscriptReply)
	err := c.cc.Invoke(ctx, Sessions_Transcript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) EventDetails(ctx context.Context, in *EventDetailsRequest, opts ...grpc.CallOption) (*EventBatch, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventBatch)
	err := c.cc.Invoke(ctx, Sessions_EventDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) Background(ctx context.Context, in *SessionRef, opts ...grpc.CallOption) (*BackgroundReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BackgroundReply)
	err := c.cc.Invoke(ctx, Sessions_Background_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) Models(ctx context.Context, in *ModelsRequest, opts ...grpc.CallOption) (*ModelsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelsReply)
	err := c.cc.Invoke(ctx, Sessions_Models_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SearchReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Sessions_ServiceDesc.Streams[1], Sessions_Search_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SearchRequest, SearchReply]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sessions_SearchClient = grpc.ServerStreamingClient[SearchReply]

func (c *sessionsClient) Open(ctx context.Context, in *ProjectRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, Sessions_Open_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) Projects(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProjectList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectList)
	err := c.cc.Invoke(ctx, Sessions_Projects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) Down(ctx context.Context, in *ProjectRequest, opts ...grpc.CallOption) (*Receipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Receipt)
	err := c.cc.Invoke(ctx, Sessions_Down_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) AuxRun(ctx context.Context, in *AuxRunInput, opts ...grpc.CallOption) (*AuxState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuxState)
	err := c.cc.Invoke(ctx, Sessions_AuxRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) AuxCancel(ctx context.Context, in *AuxCancelInput, opts ...grpc.CallOption) (*AuxState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuxState)
	err := c.cc.Invoke(ctx, Sessions_AuxCancel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) AuxStatus(ctx context.Context, in *AuxStatusInput, opts ...grpc.CallOption) (*AuxState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuxState)
	err := c.cc.Invoke(ctx, Sessions_AuxStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) AuxEvents(ctx context.Context, in *AuxStatusInput, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AuxState], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Sessions_ServiceDesc.Streams[2], Sessions_AuxEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AuxStatusInput, AuxState]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sessions_AuxEventsClient = grpc.ServerStreamingClient[AuxState]

func (c *sessionsClient) AuxPrefer(ctx context.Context, in *AuxPreferInput, opts ...grpc.CallOption) (*AuxState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuxState)
	err := c.cc.Invoke(ctx, Sessions_AuxPrefer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) AuxForget(ctx context.Context, in *AuxForgetInput, opts ...grpc.CallOption) (*Receipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Receipt)
	err := c.cc.Invoke(ctx, Sessions_AuxForget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) AuxConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AuxConfigReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuxConfigReply)
	err := c.cc.Invoke(ctx, Sessions_AuxConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) AuxSetConfig(ctx context.Context, in *AuxSetConfigInput, opts ...grpc.CallOption) (*AuxConfigReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuxConfigReply)
	err := c.cc.Invoke(ctx, Sessions_AuxSetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) AuxModels(ctx context.Context, in *AuxModelsInput, opts ...grpc.CallOption) (*AuxModelsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuxModelsReply)
	err := c.cc.Invoke(ctx, Sessions_AuxModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) AuxLoginInfo(ctx context.Context, in *AuxLoginInfoInput, opts ...grpc.CallOption) (*AuxLoginInfoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuxLoginInfoReply)
	err := c.cc.Invoke(ctx, Sessions_AuxLoginInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) PurgeSession(ctx context.Context, in *SessionPurgeInput, opts ...grpc.CallOption) (*SessionPurgeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionPurgeReply)
	err := c.cc.Invoke(ctx, Sessions_PurgeSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) GetHistoryPolicy(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HistoryPolicy, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoryPolicy)
	err := c.cc.Invoke(ctx, Sessions_GetHistoryPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) SetHistoryPolicy(ctx context.Context, in *HistoryPolicy, opts ...grpc.CallOption) (*HistoryPolicy, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoryPolicy)
	err := c.cc.Invoke(ctx, Sessions_SetHistoryPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) GetHistoryFloor(ctx context.Context, in *SessionRef, opts ...grpc.CallOption) (*HistoryFloorReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoryFloorReply)
	err := c.cc.Invoke(ctx, Sessions_GetHistoryFloor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) MarkHistoryTrimmable(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Sessions_MarkHistoryTrimmable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) PutSecretFile(ctx context.Context, in *PutSecretFileInput, opts ...grpc.CallOption) (*SecretFileReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecretFileReply)
	err := c.cc.Invoke(ctx, Sessions_PutSecretFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) DeleteSecretFile(ctx context.Context, in *DeleteSecretFileInput, opts ...grpc.CallOption) (*SecretFileReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecretFileReply)
	err := c.cc.Invoke(ctx, Sessions_DeleteSecretFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) GetSkills(ctx context.Context, in *SkillsInput, opts ...grpc.CallOption) (*SkillsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkillsReply)
	err := c.cc.Invoke(ctx, Sessions_GetSkills_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) AddSkill(ctx context.Context, in *SkillInput, opts ...grpc.CallOption) (*SkillsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkillsReply)
	err := c.cc.Invoke(ctx, Sessions_AddSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) RemoveSkill(ctx context.Context, in *SkillInput, opts ...grpc.CallOption) (*SkillsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkillsReply)
	err := c.cc.Invoke(ctx, Sessions_RemoveSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) SetSkillDefault(ctx context.Context, in *SkillDefaultInput, opts ...grpc.CallOption) (*SkillsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkillsReply)
	err := c.cc.Invoke(ctx, Sessions_SetSkillDefault_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) SetProjectSkill(ctx context.Context, in *ProjectSkillInput, opts ...grpc.CallOption) (*SkillsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkillsReply)
	err := c.cc.Invoke(ctx, Sessions_SetProjectSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) ClearProjectSkill(ctx context.Context, in *ClearProjectSkillInput, opts ...grpc.CallOption) (*SkillsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkillsReply)
	err := c.cc.Invoke(ctx, Sessions_ClearProjectSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) SyncSkills(ctx context.Context, in *SyncSkillsInput, opts ...grpc.CallOption) (*Receipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Receipt)
	err := c.cc.Invoke(ctx, Sessions_SyncSkills_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) RenderDevcontainer(ctx context.Context, in *RenderDevcontainerInput, opts ...grpc.CallOption) (*RenderDevcontainerReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenderDevcontainerReply)
	err := c.cc.Invoke(ctx, Sessions_RenderDevcontainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) GetMcpServers(ctx context.Context, in *McpServersInput, opts ...grpc.CallOption) (*McpServersReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(McpServersReply)
	err := c.cc.Invoke(ctx, Sessions_GetMcpServers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) PutMcpServer(ctx context.Context, in *PutMcpServerInput, opts ...grpc.CallOption) (*McpServersReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(McpServersReply)
	err := c.cc.Invoke(ctx, Sessions_PutMcpServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) RemoveMcpServer(ctx context.Context, in *McpServerInput, opts ...grpc.CallOption) (*McpServersReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(McpServersReply)
	err := c.cc.Invoke(ctx, Sessions_RemoveMcpServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) SetMcpServerDefault(ctx context.Context, in *McpServerDefaultInput, opts ...grpc.CallOption) (*McpServersReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(McpServersReply)
	err := c.cc.Invoke(ctx, Sessions_SetMcpServerDefault_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) SetProjectMcpServer(ctx context.Context, in *ProjectMcpServerInput, opts ...grpc.CallOption) (*McpServersReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(McpServersReply)
	err := c.cc.Invoke(ctx, Sessions_SetProjectMcpServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) ClearProjectMcpServer(ctx context.Context, in *ClearProjectMcpServerInput, opts ...grpc.CallOption) (*McpServersReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(McpServersReply)
	err := c.cc.Invoke(ctx, Sessions_ClearProjectMcpServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) McpSessions(ctx context.Context, in *McpSessionsInput, opts ...grpc.CallOption) (*McpSessionsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(McpSessionsReply)
	err := c.cc.Invoke(ctx, Sessions_McpSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) SyncMcpServers(ctx context.Context, in *SyncMcpServersInput, opts ...grpc.CallOption) (*Receipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Receipt)
	err := c.cc.Invoke(ctx, Sessions_SyncMcpServers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) McpLogs(ctx context.Context, in *McpLogsInput, opts ...grpc.CallOption) (*McpLogsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(McpLogsReply)
	err := c.cc.Invoke(ctx, Sessions_McpLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) RestartMcp(ctx context.Context, in *RestartMcpInput, opts ...grpc.CallOption) (*Receipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Receipt)
	err := c.cc.Invoke(ctx, Sessions_RestartMcp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionsServer is the server API for Sessions service.
// All implementations must embed UnimplementedSessionsServer
// for forward compatibility.
type SessionsServer interface {
	Devcontainer(context.Context, *DevcontainerInput) (*Receipt, error)
	Docker(context.Context, *DockerInput) (*Receipt, error)
	FileMappings(context.Context, *FileMappingsInput) (*Receipt, error)
	Create(context.Context, *CreateRequest) (*Session, error)
	List(context.Context, *Empty) (*SessionList, error)
	Get(context.Context, *SessionRef) (*Session, error)
	CopyMemory(context.Context, *CopyMemoryRequest) (*Receipt, error)
	Memory(context.Context, *MemoryRequest) (*MemoryReply, error)
	Logs(context.Context, *LogsRequest) (*LogsReply, error)
	Permission(context.Context, *PermissionInput) (*Receipt, error)
	Send(context.Context, *Input) (*Receipt, error)
	Attach(context.Context, *AttachmentInput) (*Attachment, error)
	Activity(context.Context, *ActivityInput) (*Receipt, error)
	UpdateAgent(context.Context, *AgentUpdateInput) (*AgentUpdateStatus, error)
	Reply(context.Context, *Answer) (*Receipt, error)
	Interrupt(context.Context, *Control) (*Receipt, error)
	Resume(context.Context, *Control) (*Session, error)
	Stop(context.Context, *Control) (*Receipt, error)
	Watch(*WatchRequest, grpc.ServerStreamingServer[Event]) error
	History(context.Context, *WatchRequest) (*EventBatch, error)
	Transcript(context.Context, *TranscriptRequest) (*TranscriptReply, error)
	EventDetails(context.Context, *EventDetailsRequest) (*EventBatch, error)
	Background(context.Context, *SessionRef) (*BackgroundReply, error)
	Models(context.Context, *ModelsRequest) (*ModelsReply, error)
	Search(*SearchRequest, grpc.ServerStreamingServer[SearchReply]) error
	Open(context.Context, *ProjectRequest) (*Session, error)
	Projects(context.Context, *Empty) (*ProjectList, error)
	Down(context.Context, *ProjectRequest) (*Receipt, error)
	AuxRun(context.Context, *AuxRunInput) (*AuxState, error)
	AuxCancel(context.Context, *AuxCancelInput) (*AuxState, error)
	AuxStatus(context.Context, *AuxStatusInput) (*AuxState, error)
	AuxEvents(*AuxStatusInput, grpc.ServerStreamingServer[AuxState]) error
	AuxPrefer(context.Context, *AuxPreferInput) (*AuxState, error)
	AuxForget(context.Context, *AuxForgetInput) (*Receipt, error)
	AuxConfig(context.Context, *Empty) (*AuxConfigReply, error)
	AuxSetConfig(context.Context, *AuxSetConfigInput) (*AuxConfigReply, error)
	AuxModels(context.Context, *AuxModelsInput) (*AuxModelsReply, error)
	AuxLoginInfo(context.Context, *AuxLoginInfoInput) (*AuxLoginInfoReply, error)
	PurgeSession(context.Context, *SessionPurgeInput) (*SessionPurgeReply, error)
	GetHistoryPolicy(context.Context, *Empty) (*HistoryPolicy, error)
	SetHistoryPolicy(context.Context, *HistoryPolicy) (*HistoryPolicy, error)
	GetHistoryFloor(context.Context, *SessionRef) (*HistoryFloorReply, error)
	MarkHistoryTrimmable(context.Context, *Empty) (*Empty, error)
	PutSecretFile(context.Context, *PutSecretFileInput) (*SecretFileReply, error)
	DeleteSecretFile(context.Context, *DeleteSecretFileInput) (*SecretFileReply, error)
	GetSkills(context.Context, *SkillsInput) (*SkillsReply, error)
	AddSkill(context.Context, *SkillInput) (*SkillsReply, error)
	RemoveSkill(context.Context, *SkillInput) (*SkillsReply, error)
	SetSkillDefault(context.Context, *SkillDefaultInput) (*SkillsReply, error)
	SetProjectSkill(context.Context, *ProjectSkillInput) (*SkillsReply, error)
	ClearProjectSkill(context.Context, *ClearProjectSkillInput) (*SkillsReply, error)
	SyncSkills(context.Context, *SyncSkillsInput) (*Receipt, error)
	RenderDevcontainer(context.Context, *RenderDevcontainerInput) (*RenderDevcontainerReply, error)
	GetMcpServers(context.Context, *McpServersInput) (*McpServersReply, error)
	PutMcpServer(context.Context, *PutMcpServerInput) (*McpServersReply, error)
	RemoveMcpServer(context.Context, *McpServerInput) (*McpServersReply, error)
	SetMcpServerDefault(context.Context, *McpServerDefaultInput) (*McpServersReply, error)
	SetProjectMcpServer(context.Context, *ProjectMcpServerInput) (*McpServersReply, error)
	ClearProjectMcpServer(context.Context, *ClearProjectMcpServerInput) (*McpServersReply, error)
	McpSessions(context.Context, *McpSessionsInput) (*McpSessionsReply, error)
	SyncMcpServers(context.Context, *SyncMcpServersInput) (*Receipt, error)
	McpLogs(context.Context, *McpLogsInput) (*McpLogsReply, error)
	RestartMcp(context.Context, *RestartMcpInput) (*Receipt, error)
	mustEmbedUnimplementedSessionsServer()
}

// UnimplementedSessionsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSessionsServer struct{}

func (UnimplementedSessionsServer) Devcontainer(context.Context, *DevcontainerInput) (*Receipt, error) {
	return nil, status.Error(codes.Unimplemented, "method Devcontainer not implemented")
}
func (UnimplementedSessionsServer) Docker(context.Context, *DockerInput) (*Receipt, error) {
	return nil, status.Error(codes.Unimplemented, "method Docker not implemented")
}
func (UnimplementedSessionsServer) FileMappings(context.Context, *FileMappingsInput) (*Receipt, error) {
	return nil, status.Error(codes.Unimplemented, "method FileMappings not implemented")
}
func (UnimplementedSessionsServer) Create(context.Context, *CreateRequest) (*Session, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedSessionsServer) List(context.Context, *Empty) (*SessionList, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedSessionsServer) Get(context.Context, *SessionRef) (*Session, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedSessionsServer) CopyMemory(context.Context, *CopyMemoryRequest) (*Receipt, error) {
	return nil, status.Error(codes.Unimplemented, "method CopyMemory not implemented")
}
func (UnimplementedSessionsServer) Memory(context.Context, *MemoryRequest) (*MemoryReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Memory not implemented")
}
func (UnimplementedSessionsServer) Logs(context.Context, *LogsRequest) (*LogsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Logs not implemented")
}
func (UnimplementedSessionsServer) Permission(context.Context, *PermissionInput) (*Receipt, error) {
	return nil, status.Error(codes.Unimplemented, "method Permission not implemented")
}
func (UnimplementedSessionsServer) Send(context.Context, *Input) (*Receipt, error) {
	return nil, status.Error(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedSessionsServer) Attach(context.Context, *AttachmentInput) (*Attachment, error) {
	return nil, status.Error(codes.Unimplemented, "method Attach not implemented")
}
func (UnimplementedSessionsServer) Activity(context.Context, *ActivityInput) (*Receipt, error) {
	return nil, status.Error(codes.Unimplemented, "method Activity not implemented")
}
func (UnimplementedSessionsServer) UpdateAgent(context.Context, *AgentUpdateInput) (*AgentUpdateStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAgent not implemented")
}
func (UnimplementedSessionsServer) Reply(context.Context, *Answer) (*Receipt, error) {
	return nil, status.Error(codes.Unimplemented, "method Reply not implemented")
}
func (UnimplementedSessionsServer) Interrupt(context.Context, *Control) (*Receipt, error) {
	return nil, status.Error(codes.Unimplemented, "method Interrupt not implemented")
}
func (UnimplementedSessionsServer) Resume(context.Context, *Control) (*Session, error) {
	return nil, status.Error(codes.Unimplemented, "method Resume not implemented")
}
func (UnimplementedSessionsServer) Stop(context.Context, *Control) (*Receipt, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedSessionsServer) Watch(*WatchRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedSessionsServer) History(context.Context, *WatchRequest) (*EventBatch, error) {
	return nil, status.Error(codes.Unimplemented, "method History not implemented")
}
func (UnimplementedSessionsServer) Transcript(context.Context, *TranscriptRequest) (*TranscriptReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Transcript not implemented")
}
func (UnimplementedSessionsServer) EventDetails(context.Context, *EventDetailsRequest) (*EventBatch, error) {
	return nil, status.Error(codes.Unimplemented, "method EventDetails not implemented")
}
func (UnimplementedSessionsServer) Background(context.Context, *SessionRef) (*BackgroundReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Background not implemented")
}
func (UnimplementedSessionsServer) Models(context.Context, *ModelsRequest) (*ModelsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Models not implemented")
}
func (UnimplementedSessionsServer) Search(*SearchRequest, grpc.ServerStreamingServer[SearchReply]) error {
	return status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedSessionsServer) Open(context.Context, *ProjectRequest) (*Session, error) {
	return nil, status.Error(codes.Unimplemented, "method Open not implemented")
}
func (UnimplementedSessionsServer) Projects(context.Context, *Empty) (*ProjectList, error) {
	return nil, status.Error(codes.Unimplemented, "method Projects not implemented")
}
func (UnimplementedSessionsServer) Down(context.Context, *ProjectRequest) (*Receipt, error) {
	return nil, status.Error(codes.Unimplemented, "method Down not implemented")
}
func (UnimplementedSessionsServer) AuxRun(context.Context, *AuxRunInput) (*AuxState, error) {
	return nil, status.Error(codes.Unimplemented, "method AuxRun not implemented")
}
func (UnimplementedSessionsServer) AuxCancel(context.Context, *AuxCancelInput) (*AuxState, error) {
	return nil, status.Error(codes.Unimplemented, "method AuxCancel not implemented")
}
func (UnimplementedSessionsServer) AuxStatus(context.Context, *AuxStatusInput) (*AuxState, error) {
	return nil, status.Error(codes.Unimplemented, "method AuxStatus not implemented")
}
func (UnimplementedSessionsServer) AuxEvents(*AuxStatusInput, grpc.ServerStreamingServer[AuxState]) error {
	return status.Error(codes.Unimplemented, "method AuxEvents not implemented")
}
func (UnimplementedSessionsServer) AuxPrefer(context.Context, *AuxPreferInput) (*AuxState, error) {
	return nil, status.Error(codes.Unimplemented, "method AuxPrefer not implemented")
}
func (UnimplementedSessionsServer) AuxForget(context.Context, *AuxForgetInput) (*Receipt, error) {
	return nil, status.Error(codes.Unimplemented, "method AuxForget not implemented")
}
func (UnimplementedSessionsServer) AuxConfig(context.Context, *Empty) (*AuxConfigReply, error) {
	return nil, status.Error(codes.Unimplemented, "method AuxConfig not implemented")
}
func (UnimplementedSessionsServer) AuxSetConfig(context.Context, *AuxSetConfigInput) (*AuxConfigReply, error) {
	return nil, status.Error(codes.Unimplemented, "method AuxSetConfig not implemented")
}
func (UnimplementedSessionsServer) AuxModels(context.Context, *AuxModelsInput) (*AuxModelsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method AuxModels not implemented")
}
func (UnimplementedSessionsServer) AuxLoginInfo(context.Context, *AuxLoginInfoInput) (*AuxLoginInfoReply, error) {
	return nil, status.Error(codes.Unimplemented, "method AuxLoginInfo not implemented")
}
func (UnimplementedSessionsServer) PurgeSession(context.Context, *SessionPurgeInput) (*SessionPurgeReply, error) {
	return nil, status.Error(codes.Unimplemented, "method PurgeSession not implemented")
}
func (UnimplementedSessionsServer) GetHistoryPolicy(context.Context, *Empty) (*HistoryPolicy, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHistoryPolicy not implemented")
}
func (UnimplementedSessionsServer) SetHistoryPolicy(context.Context, *HistoryPolicy) (*HistoryPolicy, error) {
	return nil, status.Error(codes.Unimplemented, "method SetHistoryPolicy not implemented")
}
func (UnimplementedSessionsServer) GetHistoryFloor(context.Context, *SessionRef) (*HistoryFloorReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHistoryFloor not implemented")
}
func (UnimplementedSessionsServer) MarkHistoryTrimmable(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkHistoryTrimmable not implemented")
}
func (UnimplementedSessionsServer) PutSecretFile(context.Context, *PutSecretFileInput) (*SecretFileReply, error) {
	return nil, status.Error(codes.Unimplemented, "method PutSecretFile not implemented")
}
func (UnimplementedSessionsServer) DeleteSecretFile(context.Context, *DeleteSecretFileInput) (*SecretFileReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSecretFile not implemented")
}
func (UnimplementedSessionsServer) GetSkills(context.Context, *SkillsInput) (*SkillsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSkills not implemented")
}
func (UnimplementedSessionsServer) AddSkill(context.Context, *SkillInput) (*SkillsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method AddSkill not implemented")
}
func (UnimplementedSessionsServer) RemoveSkill(context.Context, *SkillInput) (*SkillsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveSkill not implemented")
}
func (UnimplementedSessionsServer) SetSkillDefault(context.Context, *SkillDefaultInput) (*SkillsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SetSkillDefault not implemented")
}
func (UnimplementedSessionsServer) SetProjectSkill(context.Context, *ProjectSkillInput) (*SkillsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SetProjectSkill not implemented")
}
func (UnimplementedSessionsServer) ClearProjectSkill(context.Context, *ClearProjectSkillInput) (*SkillsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearProjectSkill not implemented")
}
func (UnimplementedSessionsServer) SyncSkills(context.Context, *SyncSkillsInput) (*Receipt, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncSkills not implemented")
}
func (UnimplementedSessionsServer) RenderDevcontainer(context.Context, *RenderDevcontainerInput) (*RenderDevcontainerReply, error) {
	return nil, status.Error(codes.Unimplemented, "method RenderDevcontainer not implemented")
}
func (UnimplementedSessionsServer) GetMcpServers(context.Context, *McpServersInput) (*McpServersReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMcpServers not implemented")
}
func (UnimplementedSessionsServer) PutMcpServer(context.Context, *PutMcpServerInput) (*McpServersReply, error) {
	return nil, status.Error(codes.Unimplemented, "method PutMcpServer not implemented")
}
func (UnimplementedSessionsServer) RemoveMcpServer(context.Context, *McpServerInput) (*McpServersReply, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveMcpServer not implemented")
}
func (UnimplementedSessionsServer) SetMcpServerDefault(context.Context, *McpServerDefaultInput) (*McpServersReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SetMcpServerDefault not implemented")
}
func (UnimplementedSessionsServer) SetProjectMcpServer(context.Context, *ProjectMcpServerInput) (*McpServersReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SetProjectMcpServer not implemented")
}
func (UnimplementedSessionsServer) ClearProjectMcpServer(context.Context, *ClearProjectMcpServerInput) (*McpServersReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearProjectMcpServer not implemented")
}
func (UnimplementedSessionsServer) McpSessions(context.Context, *McpSessionsInput) (*McpSessionsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method McpSessions not implemented")
}
func (UnimplementedSessionsServer) SyncMcpServers(context.Context, *SyncMcpServersInput) (*Receipt, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncMcpServers not implemented")
}
func (UnimplementedSessionsServer) McpLogs(context.Context, *McpLogsInput) (*McpLogsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method McpLogs not implemented")
}
func (UnimplementedSessionsServer) RestartMcp(context.Context, *RestartMcpInput) (*Receipt, error) {
	return nil, status.Error(codes.Unimplemented, "method RestartMcp not implemented")
}
func (UnimplementedSessionsServer) mustEmbedUnimplementedSessionsServer() {}
func (UnimplementedSessionsServer) testEmbeddedByValue()                  {}

// UnsafeSessionsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionsServer will
// result in compilation errors.
type UnsafeSessionsServer interface {
	mustEmbedUnimplementedSessionsServer()
}

func RegisterSessionsServer(s grpc.ServiceRegistrar, srv SessionsServer) {
	// If the following call panics, it indicates UnimplementedSessionsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Sessions_ServiceDesc, srv)
}

func _Sessions_Devcontainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DevcontainerInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).Devcontainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_Devcontainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).Devcontainer(ctx, req.(*DevcontainerInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_Docker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DockerInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).Docker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_Docker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).Docker(ctx, req.(*DockerInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_FileMappings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileMappingsInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).FileMappings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_FileMappings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).FileMappings(ctx, req.(*FileMappingsInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).List(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).Get(ctx, req.(*SessionRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_CopyMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).CopyMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_CopyMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).CopyMemory(ctx, req.(*CopyMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_Memory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).Memory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_Memory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).Memory(ctx, req.(*MemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_Logs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).Logs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_Logs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).Logs(ctx, req.(*LogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_Permission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PermissionInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).Permission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_Permission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).Permission(ctx, req.(*PermissionInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Input)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_Send_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).Send(ctx, req.(*Input))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_Attach_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachmentInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).Attach(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_Attach_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).Attach(ctx, req.(*AttachmentInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_Activity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivityInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).Activity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_Activity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).Activity(ctx, req.(*ActivityInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_UpdateAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentUpdateInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).UpdateAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_UpdateAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).UpdateAgent(ctx, req.(*AgentUpdateInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_Reply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Answer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).Reply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_Reply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).Reply(ctx, req.(*Answer))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_Interrupt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Control)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).Interrupt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_Interrupt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).Interrupt(ctx, req.(*Control))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_Resume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Control)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).Resume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_Resume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).Resume(ctx, req.(*Control))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Control)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).Stop(ctx, req.(*Control))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SessionsServer).Watch(m, &grpc.GenericServerStream[WatchRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sessions_WatchServer = grpc.ServerStreamingServer[Event]

func _Sessions_History_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).History(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_History_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).History(ctx, req.(*WatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_Transcript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TranscriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).Transcript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_Transcript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).Transcript(ctx, req.(*TranscriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_EventDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).EventDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_EventDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).EventDetails(ctx, req.(*EventDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_Background_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).Background(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_Background_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).Background(ctx, req.(*SessionRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_Models_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).Models(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_Models_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).Models(ctx, req.(*ModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_Search_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SessionsServer).Search(m, &grpc.GenericServerStream[SearchRequest, SearchReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sessions_SearchServer = grpc.ServerStreamingServer[SearchReply]

func _Sessions_Open_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).Open(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_Open_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).Open(ctx, req.(*ProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_Projects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).Projects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_Projects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).Projects(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_Down_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).Down(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_Down_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).Down(ctx, req.(*ProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_AuxRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuxRunInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).AuxRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_AuxRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).AuxRun(ctx, req.(*AuxRunInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_AuxCancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuxCancelInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).AuxCancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_AuxCancel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).AuxCancel(ctx, req.(*AuxCancelInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_AuxStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuxStatusInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).AuxStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_AuxStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).AuxStatus(ctx, req.(*AuxStatusInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_AuxEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AuxStatusInput)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SessionsServer).AuxEvents(m, &grpc.GenericServerStream[AuxStatusInput, AuxState]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sessions_AuxEventsServer = grpc.ServerStreamingServer[AuxState]

func _Sessions_AuxPrefer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuxPreferInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).AuxPrefer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_AuxPrefer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).AuxPrefer(ctx, req.(*AuxPreferInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_AuxForget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuxForgetInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).AuxForget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_AuxForget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).AuxForget(ctx, req.(*AuxForgetInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_AuxConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).AuxConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_AuxConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).AuxConfig(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_AuxSetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuxSetConfigInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).AuxSetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_AuxSetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).AuxSetConfig(ctx, req.(*AuxSetConfigInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_AuxModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuxModelsInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).AuxModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_AuxModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).AuxModels(ctx, req.(*AuxModelsInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_AuxLoginInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuxLoginInfoInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).AuxLoginInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_AuxLoginInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).AuxLoginInfo(ctx, req.(*AuxLoginInfoInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_PurgeSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionPurgeInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).PurgeSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_PurgeSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).PurgeSession(ctx, req.(*SessionPurgeInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_GetHistoryPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).GetHistoryPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_GetHistoryPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).GetHistoryPolicy(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_SetHistoryPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoryPolicy)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).SetHistoryPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_SetHistoryPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).SetHistoryPolicy(ctx, req.(*HistoryPolicy))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_GetHistoryFloor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).GetHistoryFloor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_GetHistoryFloor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).GetHistoryFloor(ctx, req.(*SessionRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_MarkHistoryTrimmable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).MarkHistoryTrimmable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_MarkHistoryTrimmable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).MarkHistoryTrimmable(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_PutSecretFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutSecretFileInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).PutSecretFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_PutSecretFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).PutSecretFile(ctx, req.(*PutSecretFileInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_DeleteSecretFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSecretFileInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).DeleteSecretFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_DeleteSecretFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).DeleteSecretFile(ctx, req.(*DeleteSecretFileInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_GetSkills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkillsInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).GetSkills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_GetSkills_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).GetSkills(ctx, req.(*SkillsInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_AddSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkillInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).AddSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_AddSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).AddSkill(ctx, req.(*SkillInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_RemoveSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkillInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).RemoveSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_RemoveSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).RemoveSkill(ctx, req.(*SkillInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_SetSkillDefault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkillDefaultInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).SetSkillDefault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_SetSkillDefault_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).SetSkillDefault(ctx, req.(*SkillDefaultInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_SetProjectSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectSkillInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).SetProjectSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_SetProjectSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).SetProjectSkill(ctx, req.(*ProjectSkillInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_ClearProjectSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearProjectSkillInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).ClearProjectSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_ClearProjectSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).ClearProjectSkill(ctx, req.(*ClearProjectSkillInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_SyncSkills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncSkillsInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).SyncSkills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_SyncSkills_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).SyncSkills(ctx, req.(*SyncSkillsInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_RenderDevcontainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderDevcontainerInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).RenderDevcontainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_RenderDevcontainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).RenderDevcontainer(ctx, req.(*RenderDevcontainerInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_GetMcpServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(McpServersInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).GetMcpServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_GetMcpServers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).GetMcpServers(ctx, req.(*McpServersInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_PutMcpServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutMcpServerInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).PutMcpServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_PutMcpServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).PutMcpServer(ctx, req.(*PutMcpServerInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_RemoveMcpServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(McpServerInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).RemoveMcpServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_RemoveMcpServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).RemoveMcpServer(ctx, req.(*McpServerInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_SetMcpServerDefault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(McpServerDefaultInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).SetMcpServerDefault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_SetMcpServerDefault_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).SetMcpServerDefault(ctx, req.(*McpServerDefaultInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_SetProjectMcpServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectMcpServerInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).SetProjectMcpServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_SetProjectMcpServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).SetProjectMcpServer(ctx, req.(*ProjectMcpServerInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_ClearProjectMcpServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearProjectMcpServerInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).ClearProjectMcpServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_ClearProjectMcpServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).ClearProjectMcpServer(ctx, req.(*ClearProjectMcpServerInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_McpSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(McpSessionsInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).McpSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_McpSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).McpSessions(ctx, req.(*McpSessionsInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_SyncMcpServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncMcpServersInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).SyncMcpServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_SyncMcpServers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).SyncMcpServers(ctx, req.(*SyncMcpServersInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_McpLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(McpLogsInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).McpLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_McpLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).McpLogs(ctx, req.(*McpLogsInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_RestartMcp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartMcpInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).RestartMcp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_RestartMcp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).RestartMcp(ctx, req.(*RestartMcpInput))
	}
	return interceptor(ctx, in, info, handler)
}

// Sessions_ServiceDesc is the grpc.ServiceDesc for Sessions service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sessions_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cxz.runtime.Sessions",
	HandlerType: (*SessionsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Devcontainer",
			Handler:    _Sessions_Devcontainer_Handler,
		},
		{
			MethodName: "Docker",
			Handler:    _Sessions_Docker_Handler,
		},
		{
			MethodName: "FileMappings",
			Handler:    _Sessions_FileMappings_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Sessions_Create_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Sessions_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Sessions_Get_Handler,
		},
		{
			MethodName: "CopyMemory",
			Handler:    _Sessions_CopyMemory_Handler,
		},
		{
			MethodName: "Memory",
			Handler:    _Sessions_Memory_Handler,
		},
		{
			MethodName: "Logs",
			Handler:    _Sessions_Logs_Handler,
		},
		{
			MethodName: "Permission",
			Handler:    _Sessions_Permission_Handler,
		},
		{
			MethodName: "Send",
			Handler:    _Sessions_Send_Handler,
		},
		{
			MethodName: "Attach",
			Handler:    _Sessions_Attach_Handler,
		},
		{
			MethodName: "Activity",
			Handler:    _Sessions_Activity_Handler,
		},
		{
			MethodName: "UpdateAgent",
			Handler:    _Sessions_UpdateAgent_Handler,
		},
		{
			MethodName: "Reply",
			Handler:    _Sessions_Reply_Handler,
		},
		{
			MethodName: "Interrupt",
			Handler:    _Sessions_Interrupt_Handler,
		},
		{
			MethodName: "Resume",
			Handler:    _Sessions_Resume_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Sessions_Stop_Handler,
		},
		{
			MethodName: "History",
			Handler:    _Sessions_History_Handler,
		},
		{
			MethodName: "Transcript",
			Handler:    _Sessions_Transcript_Handler,
		},
		{
			MethodName: "EventDetails",
			Handler:    _Sessions_EventDetails_Handler,
		},
		{
			MethodName: "Background",
			Handler:    _Sessions_Background_Handler,
		},
		{
			MethodName: "Models",
			Handler:    _Sessions_Models_Handler,
		},
		{
			MethodName: "Open",
			Handler:    _Sessions_Open_Handler,
		},
		{
			MethodName: "Projects",
			Handler:    _Sessions_Projects_Handler,
		},
		{
			MethodName: "Down",
			Handler:    _Sessions_Down_Handler,
		},
		{
			MethodName: "AuxRun",
			Handler:    _Sessions_AuxRun_Handler,
		},
		{
			MethodName: "AuxCancel",
			Handler:    _Sessions_AuxCancel_Handler,
		},
		{
			MethodName: "AuxStatus",
			Handler:    _Sessions_AuxStatus_Handler,
		},
		{
			MethodName: "AuxPrefer",
			Handler:    _Sessions_AuxPrefer_Handler,
		},
		{
			MethodName: "AuxForget",
			Handler:    _Sessions_AuxForget_Handler,
		},
		{
			MethodName: "AuxConfig",
			Handler:    _Sessions_AuxConfig_Handler,
		},
		{
			MethodName: "AuxSetConfig",
			Handler:    _Sessions_AuxSetConfig_Handler,
		},
		{
			MethodName: "AuxModels",
			Handler:    _Sessions_AuxModels_Handler,
		},
		{
			MethodName: "AuxLoginInfo",
			Handler:    _Sessions_AuxLoginInfo_Handler,
		},
		{
			MethodName: "PurgeSession",
			Handler:    _Sessions_PurgeSession_Handler,
		},
		{
			MethodName: "GetHistoryPolicy",
			Handler:    _Sessions_GetHistoryPolicy_Handler,
		},
		{
			MethodName: "SetHistoryPolicy",
			Handler:    _Sessions_SetHistoryPolicy_Handler,
		},
		{
			MethodName: "GetHistoryFloor",
			Handler:    _Sessions_GetHistoryFloor_Handler,
		},
		{
			MethodName: "MarkHistoryTrimmable",
			Handler:    _Sessions_MarkHistoryTrimmable_Handler,
		},
		{
			MethodName: "PutSecretFile",
			Handler:    _Sessions_PutSecretFile_Handler,
		},
		{
			MethodName: "DeleteSecretFile",
			Handler:    _Sessions_DeleteSecretFile_Handler,
		},
		{
			MethodName: "GetSkills",
			Handler:    _Sessions_GetSkills_Handler,
		},
		{
			MethodName: "AddSkill",
			Handler:    _Sessions_AddSkill_Handler,
		},
		{
			MethodName: "RemoveSkill",
			Handler:    _Sessions_RemoveSkill_Handler,
		},
		{
			MethodName: "SetSkillDefault",
			Handler:    _Sessions_SetSkillDefault_Handler,
		},
		{
			MethodName: "SetProjectSkill",
			Handler:    _Sessions_SetProjectSkill_Handler,
		},
		{
			MethodName: "ClearProjectSkill",
			Handler:    _Sessions_ClearProjectSkill_Handler,
		},
		{
			MethodName: "SyncSkills",
			Handler:    _Sessions_SyncSkills_Handler,
		},
		{
			MethodName: "RenderDevcontainer",
			Handler:    _Sessions_RenderDevcontainer_Handler,
		},
		{
			MethodName: "GetMcpServers",
			Handler:    _Sessions_GetMcpServers_Handler,
		},
		{
			MethodName: "PutMcpServer",
			Handler:    _Sessions_PutMcpServer_Handler,
		},
		{
			MethodName: "RemoveMcpServer",
			Handler:    _Sessions_RemoveMcpServer_Handler,
		},
		{
			MethodName: "SetMcpServerDefault",
			Handler:    _Sessions_SetMcpServerDefault_Handler,
		},
		{
			MethodName: "SetProjectMcpServer",
			Handler:    _Sessions_SetProjectMcpServer_Handler,
		},
		{
			MethodName: "ClearProjectMcpServer",
			Handler:    _Sessions_ClearProjectMcpServer_Handler,
		},
		{
			MethodName: "McpSessions",
			Handler:    _Sessions_McpSessions_Handler,
		},
		{
			MethodName: "SyncMcpServers",
			Handler:    _Sessions_SyncMcpServers_Handler,
		},
		{
			MethodName: "McpLogs",
			Handler:    _Sessions_McpLogs_Handler,
		},
		{
			MethodName: "RestartMcp",
			Handler:    _Sessions_RestartMcp_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _Sessions_Watch_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Search",
			Handler:       _Sessions_Search_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "AuxEvents",
			Handler:       _Sessions_AuxEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cxz.proto",
}
