// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: cxz.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Sessions_Create_FullMethodName    = "/cxz.runtime.Sessions/Create"
	Sessions_List_FullMethodName      = "/cxz.runtime.Sessions/List"
	Sessions_Get_FullMethodName       = "/cxz.runtime.Sessions/Get"
	Sessions_Send_FullMethodName      = "/cxz.runtime.Sessions/Send"
	Sessions_Reply_FullMethodName     = "/cxz.runtime.Sessions/Reply"
	Sessions_Interrupt_FullMethodName = "/cxz.runtime.Sessions/Interrupt"
	Sessions_Resume_FullMethodName    = "/cxz.runtime.Sessions/Resume"
	Sessions_Stop_FullMethodName      = "/cxz.runtime.Sessions/Stop"
	Sessions_Watch_FullMethodName     = "/cxz.runtime.Sessions/Watch"
	Sessions_History_FullMethodName   = "/cxz.runtime.Sessions/History"
	Sessions_Open_FullMethodName      = "/cxz.runtime.Sessions/Open"
	Sessions_Projects_FullMethodName  = "/cxz.runtime.Sessions/Projects"
	Sessions_Down_FullMethodName      = "/cxz.runtime.Sessions/Down"
)

// SessionsClient is the client API for Sessions service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SessionsClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*Session, error)
	List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SessionList, error)
	Get(ctx context.Context, in *SessionRef, opts ...grpc.CallOption) (*Session, error)
	Send(ctx context.Context, in *Input, opts ...grpc.CallOption) (*Receipt, error)
	Reply(ctx context.Context, in *Answer, opts ...grpc.CallOption) (*Receipt, error)
	Interrupt(ctx context.Context, in *Control, opts ...grpc.CallOption) (*Receipt, error)
	Resume(ctx context.Context, in *Control, opts ...grpc.CallOption) (*Session, error)
	Stop(ctx context.Context, in *Control, opts ...grpc.CallOption) (*Receipt, error)
	Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	History(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (*EventBatch, error)
	Open(ctx context.Context, in *ProjectRequest, opts ...grpc.CallOption) (*Session, error)
	Projects(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProjectList, error)
	Down(ctx context.Context, in *ProjectRequest, opts ...grpc.CallOption) (*Receipt, error)
}

type sessionsClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionsClient(cc grpc.ClientConnInterface) SessionsClient {
	return &sessionsClient{cc}
}

func (c *sessionsClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, Sessions_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SessionList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionList)
	err := c.cc.Invoke(ctx, Sessions_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) Get(ctx context.Context, in *SessionRef, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, Sessions_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) Send(ctx context.Context, in *Input, opts ...grpc.CallOption) (*Receipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Receipt)
	err := c.cc.Invoke(ctx, Sessions_Send_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) Reply(ctx context.Context, in *Answer, opts ...grpc.CallOption) (*Receipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Receipt)
	err := c.cc.Invoke(ctx, Sessions_Reply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) Interrupt(ctx context.Context, in *Control, opts ...grpc.CallOption) (*Receipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Receipt)
	err := c.cc.Invoke(ctx, Sessions_Interrupt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) Resume(ctx context.Context, in *Control, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, Sessions_Resume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) Stop(ctx context.Context, in *Control, opts ...grpc.CallOption) (*Receipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Receipt)
	err := c.cc.Invoke(ctx, Sessions_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Sessions_ServiceDesc.Streams[0], Sessions_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sessions_WatchClient = grpc.ServerStreamingClient[Event]

func (c *sessionsClient) History(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (*EventBatch, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventBatch)
	err := c.cc.Invoke(ctx, Sessions_History_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) Open(ctx context.Context, in *ProjectRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, Sessions_Open_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) Projects(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProjectList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectList)
	err := c.cc.Invoke(ctx, Sessions_Projects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionsClient) Down(ctx context.Context, in *ProjectRequest, opts ...grpc.CallOption) (*Receipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Receipt)
	err := c.cc.Invoke(ctx, Sessions_Down_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionsServer is the server API for Sessions service.
// All implementations must embed UnimplementedSessionsServer
// for forward compatibility.
type SessionsServer interface {
	Create(context.Context, *CreateRequest) (*Session, error)
	List(context.Context, *Empty) (*SessionList, error)
	Get(context.Context, *SessionRef) (*Session, error)
	Send(context.Context, *Input) (*Receipt, error)
	Reply(context.Context, *Answer) (*Receipt, error)
	Interrupt(context.Context, *Control) (*Receipt, error)
	Resume(context.Context, *Control) (*Session, error)
	Stop(context.Context, *Control) (*Receipt, error)
	Watch(*WatchRequest, grpc.ServerStreamingServer[Event]) error
	History(context.Context, *WatchRequest) (*EventBatch, error)
	Open(context.Context, *ProjectRequest) (*Session, error)
	Projects(context.Context, *Empty) (*ProjectList, error)
	Down(context.Context, *ProjectRequest) (*Receipt, error)
	mustEmbedUnimplementedSessionsServer()
}

// UnimplementedSessionsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSessionsServer struct{}

func (UnimplementedSessionsServer) Create(context.Context, *CreateRequest) (*Session, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedSessionsServer) List(context.Context, *Empty) (*SessionList, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedSessionsServer) Get(context.Context, *SessionRef) (*Session, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedSessionsServer) Send(context.Context, *Input) (*Receipt, error) {
	return nil, status.Error(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedSessionsServer) Reply(context.Context, *Answer) (*Receipt, error) {
	return nil, status.Error(codes.Unimplemented, "method Reply not implemented")
}
func (UnimplementedSessionsServer) Interrupt(context.Context, *Control) (*Receipt, error) {
	return nil, status.Error(codes.Unimplemented, "method Interrupt not implemented")
}
func (UnimplementedSessionsServer) Resume(context.Context, *Control) (*Session, error) {
	return nil, status.Error(codes.Unimplemented, "method Resume not implemented")
}
func (UnimplementedSessionsServer) Stop(context.Context, *Control) (*Receipt, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedSessionsServer) Watch(*WatchRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedSessionsServer) History(context.Context, *WatchRequest) (*EventBatch, error) {
	return nil, status.Error(codes.Unimplemented, "method History not implemented")
}
func (UnimplementedSessionsServer) Open(context.Context, *ProjectRequest) (*Session, error) {
	return nil, status.Error(codes.Unimplemented, "method Open not implemented")
}
func (UnimplementedSessionsServer) Projects(context.Context, *Empty) (*ProjectList, error) {
	return nil, status.Error(codes.Unimplemented, "method Projects not implemented")
}
func (UnimplementedSessionsServer) Down(context.Context, *ProjectRequest) (*Receipt, error) {
	return nil, status.Error(codes.Unimplemented, "method Down not implemented")
}
func (UnimplementedSessionsServer) mustEmbedUnimplementedSessionsServer() {}
func (UnimplementedSessionsServer) testEmbeddedByValue()                  {}

// UnsafeSessionsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionsServer will
// result in compilation errors.
type UnsafeSessionsServer interface {
	mustEmbedUnimplementedSessionsServer()
}

func RegisterSessionsServer(s grpc.ServiceRegistrar, srv SessionsServer) {
	// If the following call panics, it indicates UnimplementedSessionsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Sessions_ServiceDesc, srv)
}

func _Sessions_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).List(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).Get(ctx, req.(*SessionRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Input)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_Send_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).Send(ctx, req.(*Input))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_Reply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Answer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).Reply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_Reply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).Reply(ctx, req.(*Answer))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_Interrupt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Control)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).Interrupt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_Interrupt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).Interrupt(ctx, req.(*Control))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_Resume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Control)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).Resume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_Resume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).Resume(ctx, req.(*Control))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Control)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).Stop(ctx, req.(*Control))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SessionsServer).Watch(m, &grpc.GenericServerStream[WatchRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sessions_WatchServer = grpc.ServerStreamingServer[Event]

func _Sessions_History_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).History(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_History_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).History(ctx, req.(*WatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_Open_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).Open(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_Open_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).Open(ctx, req.(*ProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_Projects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).Projects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_Projects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).Projects(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sessions_Down_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionsServer).Down(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sessions_Down_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionsServer).Down(ctx, req.(*ProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Sessions_ServiceDesc is the grpc.ServiceDesc for Sessions service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sessions_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cxz.runtime.Sessions",
	HandlerType: (*SessionsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Sessions_Create_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Sessions_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Sessions_Get_Handler,
		},
		{
			MethodName: "Send",
			Handler:    _Sessions_Send_Handler,
		},
		{
			MethodName: "Reply",
			Handler:    _Sessions_Reply_Handler,
		},
		{
			MethodName: "Interrupt",
			Handler:    _Sessions_Interrupt_Handler,
		},
		{
			MethodName: "Resume",
			Handler:    _Sessions_Resume_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Sessions_Stop_Handler,
		},
		{
			MethodName: "History",
			Handler:    _Sessions_History_Handler,
		},
		{
			MethodName: "Open",
			Handler:    _Sessions_Open_Handler,
		},
		{
			MethodName: "Projects",
			Handler:    _Sessions_Projects_Handler,
		},
		{
			MethodName: "Down",
			Handler:    _Sessions_Down_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _Sessions_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cxz.proto",
}
